## aowlspt/settingshub — serves the full SPT server config surface to the F12
## in-game settings screen.
##
## The problem. The revamped settings screen (the D3D11 overlay F12 opens) draws
## a page per mod from the schema each mod serves at `/aowlspt/settings/<guid>`,
## plus **every** SPT server config value, so a player can see the whole surface
## in one place. The 28 SPT config pages — 323 scalar values and 197 nested
## lists/dictionaries — are a fixed catalogue generated by
## `tools/genspt_settings.py` into `reference/spt-config-settings.json`. aowlspt
## is a from-scratch emulator with no SPT `ConfigServer`; it consumes none of
## `configs/*.json`, so every one of these values is **shown but flagged
## not-implemented**. That honesty is the point: the player sees the whole thing
## and is told plainly which parts do nothing yet.
##
## What this mod does. It embeds that catalogue at build time (`staticRead`, so
## there is no runtime file to deploy) and serves it in the two small shapes the
## overlay's worker fetches — an index the nav is built from, and one page at a
## time so no single response is large:
##
##   GET /aowlspt/settings/spt/index      -> {"pages":[{id,label,count,done}...]}
##   GET /aowlspt/settings/spt/page/<id>  -> that page, {settings:[...],nested:[...]}
##
## It has since grown the CROSS-MOD half of the same surface, which is what a
## native settings tab consumes:
##
##   GET  /aowlspt/settings/index         -> {"mods":[{guid,name,count,done}...]}
##   GET  /aowlspt/settings/index/full    -> the same list, each mod carrying its
##                                           whole schema with current values
##                                           (also `/index?full=1`)
##   GET  /aowlspt/keybinds               -> every keybind of every loaded mod
##   POST /aowlspt/settings/<guid>/set    -> {key,value}; answers with the value
##                                           AS STORED, read back, not echoed
##
## READ THE LAZY-FETCH WARNING above `onIndexFull` before calling either of the
## two big ones from inside the game process: fetching a schema before the
## character/mode screen has been answered has taken the client down twice, and
## the reason is the shared sync slot, not the payload.
##
## It runs **server-side**, because the backend the overlay talks to
## (127.0.0.1:443) is where server-side routes register; a client-only mod's
## routes never reach it. The mod does nothing else — no runtime, no patches — so
## it is a no-op mod that happens to carry a large read-only catalogue.

import aowlspt
import aowlspt/server as sv      # serve, servePrefix, pathAfter, obj, arr, put, done
import aowlspt/json as jr        # field/each/child/count/asText/raw — reading the catalogue
import aowlspt/settings          # SettingsIndexQuery/Announce — the mod-schema broadcast
import sptsurface                # sptSurfaceText() — the embedded SPT config surface

const
  ModGuid = "aowl.settingshub"
  ModName = "SPT Settings Surface"
  ModAuthor = "savannt"
  ModVersion = "4.1.0"

  IndexRoute = "/aowlspt/settings/spt/index"
  PagePrefix = "/aowlspt/settings/spt/page/"
  ModsIndexRoute = "/aowlspt/settings/index"
  ModsIndexFullRoute = "/aowlspt/settings/index/full"
    ## Every mod AND every row, in one document. Exact, so it beats the
    ## `ClientPagePrefix` fallback below (which would otherwise read `index` as
    ## a guid).
  KeybindsRoute = "/aowlspt/keybinds"
  ClientPublishPeriodMs = 5000
    ## How long a client-side page may legitimately be missing for. This
    ## MIRRORS `cSbPeriodMs` in the host bridge (host/Aowlspt.Host.Il2Cpp/
    ## settingsbridge.nim) -- the two processes cannot share a constant, so
    ## if that cycle changes, change this, or the panel will call a normal
    ## wait a failure.
  ClientSyncRoute = "/aowlspt/settings/client/sync"
  ClientStatusPrefix = "/aowlspt/settings/client/status/"
    ## Read-only. Longer than `ClientPagePrefix`, and the backend gives the
    ## LONGEST prefix priority, so this wins over the page fallback.
  ClientPagePrefix = "/aowlspt/settings/"
    ## A FALLBACK prefix, deliberately. `matchRoute` in the backend gives an
    ## exact route priority over any prefix and the longest prefix priority
    ## among prefixes, so every server-side mod's own exact
    ## `/aowlspt/settings/<guid>` (and `/reset`), plus this hub's exact
    ## `/aowlspt/settings/index` and the longer `/aowlspt/settings/spt/page/`,
    ## all still win. Only a guid NOBODY registered lands here -- which is
    ## exactly a client-side mod. The F12 overlay therefore needs no change at
    ## all: it keeps fetching and POSTing the same URLs it always has.

## The whole SPT surface, ~108 KB of JSON, reassembled once from the string
## chunks the generated `sptsurface` module carries. nimony has no compile-time
## file read (`staticRead`/`slurp` are runtime only), so the catalogue is baked
## into source by `tools/gen_sptsurface.py` rather than read from disk -- which
## is what lets this mod ship as a single DLL with no file beside it. Assembled
## once in `onLoad` and held, rather than rebuilt per request.
var sptSurface: string = ""

proc onIndex(url, body, session: string): string =
  ## The page list, with each page's value count and how many are implemented
  ## (zero, for all of them, today) so the nav can say so without loading it.
  let pages = jr.field(sptSurface, "pages")
  var a = arr()
  for p in jr.each(pages):
    var o = obj()
    o.put("id", jr.asText(jr.child(p, "id"), ""))
    o.put("label", jr.asText(jr.child(p, "label"), ""))
    o.put("count", jr.count(jr.child(p, "settings")) + jr.count(jr.child(p, "nested")))
    o.put("done", 0)
    a.add o
  var root = obj()
  root.put("pages", a)
  result = done(root).text

proc onPage(url, body, session: string): string =
  ## One page, verbatim out of the catalogue — its own `{settings,nested}`
  ## object, which is exactly the shape the overlay's reader consumes.
  let want = pathAfter(url, PagePrefix)
  let pages = jr.field(sptSurface, "pages")
  for p in jr.each(pages):
    if jr.asText(jr.child(p, "id"), "") == want:
      return jr.raw(p)
  result = "{\"settings\":[],\"nested\":[],\"err\":\"no such SPT page\"}"

## The cross-mod aggregation: `/aowlspt/settings/index` -- the list of mods
## that have declared a settings schema, per the mod-settings-api design
## doc §2/§6. Each mod's `declareSettings()` (in `aowlspt/settings`) is
## per-mod-process-private, so this mod cannot walk another mod's state
## directly; it broadcasts `SettingsIndexQuery` and every mod that has ever
## declared settings replies synchronously with `SettingsIndexAnnounce`
## (`aowlspt.nim`'s `emit`/`deliverEvent` calls every subscriber before the
## broadcasting `emit` call returns), so the collected list is complete by
## the time this handler builds its response -- no load-order dependency,
## because the broadcast happens per request, not at mod-load time.
var gAnnounced: seq[string] = @[]

proc onAnnounce(payload: string): string =
  ## One mod's reply to the index query, collected for the in-flight
  ## `/aowlspt/settings/index` request that triggered it.
  gAnnounced.add payload
  result = ""

## The CLIENT half of the index.
##
## A mod whose `sides` is `{sideClient}` -- `mods/graphics` and the client
## halves of `mods/admin` and `mods/fov` -- is not loaded in THIS process at
## all, so the `SettingsIndexQuery` broadcast above cannot reach it and it has
## never appeared in the F12 nav. It is not a rendering fault: the mod is in a
## different process with no HTTP listener (the client host refuses
## `route_register`).
##
## So the client host pushes instead. `host/Aowlspt.Host.Il2Cpp/settingsbridge.nim`
## runs the same broadcast INSIDE the game process over the event bus and POSTs
## the result here, one mod per request:
##
##   POST /aowlspt/settings/client/sync   {"guid","name","count","done","rows":[...]}
##     -> {"ok":true,"pending":[{"guid","key","value"}...]}
##
## and this hub then answers `GET /aowlspt/settings/<that guid>` out of what
## was pushed, off a fallback prefix that an exact route always beats.
##
## The reply carries any edits made in F12 on a client page since the last
## sync; the host emits each one at the owning mod, which persists it AND
## hot-applies it in the process that owns the runtime. The next sync pushes
## the re-read rows back, so the panel shows what the mod actually kept.
##
## This is deliberately NOT "give graphics a server side". A server side would
## make the page appear while the edit landed in the wrong process -- a control
## that moves and changes nothing, which is worse than an absent page.
type
  ClientPage = object
    guid, name: string
    version: string     ## as the game process reported it, or "" if it did not

    count, done: int
    rows: string        ## the schema array, verbatim as the mod emitted it
    stamp: int          ## sync number this page last arrived on
    pushes: int         ## how many times THIS guid has been pushed, ever

var gClientPages: seq[ClientPage] = @[]
var gClientPending: seq[string] = @[]   ## queued edits, oldest first
var gClientSyncs = 0

# The assembled `/aowlspt/settings/index` reply, cached.
#
# WHY. Every GET of that route used to rebuild the whole list by broadcasting
# `SettingsIndexQuery` to every server mod (and, until the duplicate "Settings
# Panel" proxy page was removed, a second `SettingsPageQuery` broadcast purely
# to count that page's rows) -- on
# EVERY request. The overlay/settings surface polls this route continuously at
# an idle main menu (measured), so that was a fan-out to every declaring mod,
# several times a second, producing nothing new: the server-side half of the
# index is STATIC after load (`count`/`done` come from the declared schema, not
# from values -- see `onIndexQuery` in aowlspt/settings) and the panel's row
# count only changes when uihub re-declares, which it never does at runtime.
#
# So the ONLY input that can change the reply at runtime is `gClientPages`,
# pushed over `/settings/client/sync`. The cache is invalidated there, and only
# when a push actually DIFFERS from what that guid last sent -- an unchanged
# re-push (the bridge's 5s idle heartbeat) leaves the cache valid, so a truly
# idle menu serves this route from memory with no broadcast at all. A real
# settings change still propagates: it flips `gClientCacheValid` the moment the
# owning value moves, so the next poll rebuilds.
var gIndexCache = ""
var gIndexCacheValid = false

proc clientIndexOf(guid: string): int =
  result = -1
  for i, p in gClientPages:
    if p.guid == guid: return i

proc onClientSync(url, body, session: string): string =
  ## One client-side mod's page, pushed up from the game process; the reply
  ## drains the edit queue back down. Both directions in one request, because
  ## the host's POST slot is single-shot and shared.
  let g = jr.field(body, "guid")
  var root = obj()
  if not g.exists or jr.asText(g, "").len == 0:
    root.put("ok", false)
    root.put("err", "a client settings sync must name a guid")
    return done(root).text
  inc gClientSyncs
  var pg = ClientPage(guid: jr.asText(g, ""),
                      name: jr.asText(jr.field(body, "name"), ""),
                      version: jr.asText(jr.field(body, "version"), ""),
                      count: jr.asInt(jr.field(body, "count"), 0),
                      done: jr.asInt(jr.field(body, "done"), 0),
                      rows: jr.raw(jr.field(body, "rows")),
                      stamp: gClientSyncs)
  if pg.name.len == 0: pg.name = pg.guid
  if pg.rows.len == 0: pg.rows = "[]"
  let i = clientIndexOf(pg.guid)
  if i >= 0:
    # Only a CHANGE to what the index actually shows (name/count/done) or to the
    # rows invalidates the cache. An identical re-push -- the bridge's idle
    # heartbeat -- must not, or the cache would rebuild every 5s for nothing.
    let prev = gClientPages[i]
    if prev.name != pg.name or prev.count != pg.count or
       prev.done != pg.done or prev.rows != pg.rows or
       prev.version != pg.version:
      gIndexCacheValid = false
    pg.pushes = prev.pushes + 1
    gClientPages[i] = pg
  else:
    gIndexCacheValid = false   # a new guid always changes the list
    pg.pushes = 1
    gClientPages.add pg
  root.put("ok", true)
  var pend = arr()
  for e in gClientPending:
    pend.add sv.raw(e)
  gClientPending = @[]
  root.put("pending", pend)
  result = done(root).text

# ---------------------------------------------------------------------------
# THE WRITE, for any mod, over ONE route
# ---------------------------------------------------------------------------
#
#   POST /aowlspt/settings/<guid>/set   {"key":"...","value":<json literal>}
#
#     -> {"ok":bool, "guid":str, "key":str,
#         "value":<literal AS STORED>,      -- omitted when nothing could be read
#         "stored":bool,                    -- the write reached config.json
#         "pending":bool,                   -- queued for the game process
#         "effect":"applied|restart|ignored|nohook|unreported",
#         "err":str}                        -- only when something went wrong
#
# WHY A NEW ROUTE AND NOT THE EXISTING `POST /aowlspt/settings/<guid>`. That
# one answers with the WHOLE schema array, and on failure with
# `{"err":..,"rows":[..]}` -- two shapes, both large, neither of which names
# the value that is now in force. A caller wanting "did my write take?" had to
# re-fetch the page and diff it. `/set` answers that question directly, and the
# `value` it answers with is READ BACK OUT OF THE STORE after the write (and
# after the owning mod's apply hook has run), never echoed from the request:
# fact #135 is a POST answered 200 with the value unchanged, and an echo cannot
# tell those apart.
#
# It works for EVERY mod, including the ones that register their own settings
# routes by hand and the client-side ones that have no HTTP surface at all,
# because it does not call a route: it emits `SettingsApplyQuery` on the
# in-process bus and reads the owning mod's `SettingsApplyAnnounce` reply. That
# broadcast is synchronous (`deliverEvent` calls every subscriber before `emit`
# returns), so the reply is in hand by the time this handler builds its answer.
#
# The `<guid>/reset` route each mod already registers is untouched.
var gApplyAnnounced: seq[string] = @[]

proc onApplyAnnounce(payload: string): string =
  # Bounded. This collector is armed for the whole process lifetime but is only
  # ever DRAINED by `settingsSet` immediately after its own broadcast; an
  # announce raised by anything else would otherwise accumulate forever. 32 is
  # far more than the one reply a single broadcast produces.
  if gApplyAnnounced.len > 32:
    gApplyAnnounced = @[]
  gApplyAnnounced.add payload
  result = ""

proc setReplyErr(guid, key, msg: string): string =
  var o = obj()
  o.put("ok", false)
  o.put("guid", guid)
  o.put("key", key)
  o.put("stored", false)
  o.put("pending", false)
  o.put("err", msg)
  result = done(o).text

proc settingsSet(guid, body: string): string =
  ## The `<guid>/set` write. `guid` has already been split off the url.
  let k = jr.field(body, "key")
  let key = jr.asText(k, "")
  if not k.exists or key.len == 0:
    return setReplyErr(guid, "",
      "a settings write must be {\"key\":\"<configKey>\",\"value\":<literal>}")
  let v = jr.field(body, "value")
  if not v.exists:
    return setReplyErr(guid, key,
      "the body carried no \"value\"; a write with no value is not a reset -- " &
      "POST /aowlspt/settings/" & guid & "/reset for that")
  let valueRaw = jr.raw(v)
  # A CLIENT-SIDE mod is not in this process. The edit is queued for the game
  # process exactly as `onClientPage` queues it, and the reply says `pending`
  # with `stored:false` -- it has NOT been stored yet and saying otherwise is
  # the half-working control this whole mechanism exists to prevent. Poll
  # `/aowlspt/settings/client/status/<guid>?key=<key>` for where it is.
  let ci = clientIndexOf(guid)
  if ci >= 0:
    var q = obj()
    q.put("guid", guid)
    q.put("key", key)
    q.put("value", sv.raw(valueRaw))
    if gClientPending.len >= 64:
      return setReplyErr(guid, key,
        "the client settings edit queue is full (64); this edit was DROPPED " &
        "rather than growing the queue without bound")
    gClientPending.add done(q).text
    var o = obj()
    o.put("ok", true)
    o.put("guid", guid)
    o.put("key", key)
    o.put("stored", false)
    o.put("pending", true)
    o.put("client", true)
    o.put("statusRoute", "/aowlspt/settings/client/status/" & guid & "?key=" & key)
    o.put("waitMs", ClientPublishPeriodMs)
    # The value AS IT STANDS NOW, out of the rows the game process last pushed
    # -- which is necessarily the OLD one, because the write has not left this
    # process yet. Carried so the panel has something true to draw;
    # `pending:true` and `stored:false` are what say it is not the value that
    # was just asked for.
    for row in jr.each(jr.whole(gClientPages[ci].rows)):
      if jr.asText(jr.child(row, "key"), "") == key:
        let cv = jr.child(row, "value")
        if cv.exists:
          o.put("value", sv.raw(jr.raw(cv)))
    o.put("note", "queued for the game process, which owns this mod; `value` " &
                  "is the one still in force, not the one just written")
    return done(o).text
  gApplyAnnounced = @[]
  var q = obj()
  q.put("guid", guid)
  q.put("key", key)
  q.put("value", sv.raw(valueRaw))
  discard emit(settings.SettingsApplyQuery, done(q).text)
  for a in gApplyAnnounced:
    if jr.asText(jr.field(a, "guid"), "") != guid:
      continue
    let okStored = jr.asBool(jr.field(a, "ok"), false)
    var o = obj()
    o.put("ok", okStored)
    o.put("guid", guid)
    o.put("key", key)
    o.put("stored", okStored)
    o.put("pending", false)
    let rv = jr.field(a, "value")
    if rv.exists:
      o.put("value", sv.raw(jr.raw(rv)))
    let ef = jr.field(a, "effect")
    if ef.exists:
      o.put("effect", jr.asText(ef, ""))
    let ed = jr.field(a, "effectDetail")
    if ed.exists:
      o.put("effectDetail", jr.asText(ed, ""))
    let er = jr.field(a, "err")
    if er.exists:
      o.put("err", jr.asText(er, ""))
    return done(o).text
  # NOBODY ANSWERED. Not "the write failed": no mod with this guid is loaded in
  # this process and none has ever pushed a client page either, so the write
  # was never attempted. Said plainly, because "ok:false" alone would send a
  # reader hunting for a store fault that did not happen.
  result = setReplyErr(guid, key,
    "no mod with guid '" & guid & "' answered the settings apply broadcast " &
    "and no client-side page has ever been pushed for it, so NOTHING WAS " &
    "WRITTEN. Either the guid is wrong or that mod is not loaded (check " &
    "/aowlspt/mods/list and mods\\aowlspt-selection.json)")

proc onClientPage(url, body, session: string): string =
  ## `GET /aowlspt/settings/client/page/<guid>` -- the rows the host last
  ## pushed. On a POST the edit is QUEUED for the host rather than applied
  ## here: this process does not own the mod, and pretending otherwise is
  ## exactly the half-working control this mechanism exists to prevent. The
  ## reply is the rows as they stand NOW (unchanged, necessarily), so a caller
  ## that verifies by re-reading sees the old value until the host has actually
  ## applied it -- which is the truth, and is what fact #135 says to check.
  var want = pathAfter(url, ClientPagePrefix)
  # Strip a query string and a trailing `/reset` -- this prefix sees the raw
  # url, unlike an exact route.
  var cut = -1
  for ci in 0 ..< want.len:
    if want[ci] == '?':
      cut = ci
      break
  if cut >= 0: want = want.substr(0, cut - 1)
  # `<guid>/set` is handled for EVERY mod, client-side or not, and so is caught
  # before the client-page lookup below: a server-side mod registers its own
  # exact `/aowlspt/settings/<guid>` route, but nobody registers `<guid>/set`,
  # so this fallback prefix is the only thing that sees it.
  if want.len > 4 and want.substr(want.len - 4, want.len - 1) == "/set":
    return settingsSet(want.substr(0, want.len - 5), body)
  var isReset = false
  if want.len > 6 and want.substr(want.len - 6, want.len - 1) == "/reset":
    isReset = true
    want = want.substr(0, want.len - 7)
  let i = clientIndexOf(want)
  if i < 0:
    # WAITING, not broken -- and the panel must be able to tell them apart.
    #
    # A client-side page exists only once the game process has pushed it,
    # and that bridge runs on a ~5s cycle, so a page opened seconds after
    # the client came up is legitimately absent for a few seconds. The old
    # reply called that an `err`, which the panel rendered as an
    # indefinite spinner: the one state that looks identical to a mod that
    # will never answer. `waiting` says which it is, and `waitMs` says how
    # long is reasonable, so the panel can show a bounded wait and then a
    # real failure.
    var w = obj()
    w.put("waiting", true)
    w.put("guid", want)
    w.put("waitMs", ClientPublishPeriodMs)
    w.put("err", "waiting for " & want &
                 " to publish (client-side, up to " &
                 $(ClientPublishPeriodMs div 1000) & "s)")
    w.put("rows", done(arr()))
    return done(w).text
  if isReset:
    # A reset is an edit like any other from here: the host owns the mod and
    # the mod owns its defaults, so the request is queued with no key and the
    # owning process resolves it. Queueing it here as if it were applied is
    # the one thing that must not happen.
    var r = obj()
    r.put("guid", want)
    r.put("reset", true)
    if jr.field(body, "key").exists:
      r.put("key", jr.asText(jr.field(body, "key"), ""))
    if gClientPending.len < 64:
      gClientPending.add done(r).text
    return gClientPages[i].rows
  if body.len > 0:
    let k = jr.field(body, "key")
    if not k.exists or jr.asText(k, "").len == 0:
      var e = obj()
      e.put("err", "a client settings write must be {\"key\":..,\"value\":..}")
      e.put("rows", sv.raw(gClientPages[i].rows))
      return done(e).text
    var q = obj()
    q.put("guid", want)
    q.put("key", jr.asText(k, ""))
    q.put("value", sv.raw(jr.raw(jr.field(body, "value"))))
    if gClientPending.len < 64:
      gClientPending.add done(q).text
      info "settingshub: queued a client settings edit for " & want &
           " (key=" & jr.asText(k, "") & "); the game process applies it on " &
           "its next sync"
    else:
      warn "settingshub: the client settings edit queue is full (64); " &
           "dropping the edit for " & want & " rather than growing without bound"
  result = gClientPages[i].rows

proc clientPendingHas(guid, key: string): bool =
  ## Is an edit for exactly this (guid, key) still sitting in the queue --
  ## i.e. never yet handed to the game process? Bounded by the queue cap (64).
  for e in gClientPending:
    if jr.asText(jr.field(e, "guid"), "") == guid and
       jr.asText(jr.field(e, "key"), "") == key:
      return true
  false

proc onClientStatus(url, body, session: string): string =
  ## `GET /aowlspt/settings/client/status/<guid>?key=<key>` -- WHERE IN THE
  ## PIPELINE an edit is. Read-only; queues nothing, changes nothing.
  ##
  ## This route exists because the F12 panel could not previously tell "the
  ## value did not take" from "the value has not got there YET", and so
  ## reported a working write as NOT APPLIED. An edit to a client-side mod
  ## travels: POST -> queued here -> drained on the game's next
  ## `client/sync` push -> applied in the game process -> visible only on the
  ## push AFTER that. That is TWO pushes of this guid, not one, which is why
  ## a wall-clock patience tuned to one cycle went red on the working path.
  ##
  ##   {"known":bool,      -- has this guid ever pushed a page?
  ##    "pending":bool,    -- this exact (guid,key) is still queued, undrained
  ##    "pushes":int,      -- pushes of THIS guid, ever; monotonic
  ##    "stamp":int,       -- global sync number this page last arrived on
  ##    "syncs":int}       -- global sync count
  ##
  ## A caller confirms a write by waiting for `pending == false` AND
  ## `pushes >= pushes-at-POST + 2`, and only THEN comparing the row value.
  ## Before that window opens no verdict is available -- which is
  ## INCONCLUSIVE, not a failure.
  var want = pathAfter(url, ClientStatusPrefix)
  var key = ""
  var cut = -1
  for ci in 0 ..< want.len:
    if want[ci] == '?':
      cut = ci
      break
  if cut >= 0:
    let q = want.substr(cut + 1, want.len - 1)
    want = want.substr(0, cut - 1)
    if q.len > 4 and q.substr(0, 3) == "key=":
      key = q.substr(4, q.len - 1)
  var root = obj()
  root.put("guid", want)
  root.put("key", key)
  root.put("syncs", gClientSyncs)
  root.put("pending", key.len > 0 and clientPendingHas(want, key))
  root.put("pendingCount", gClientPending.len)
  let i = clientIndexOf(want)
  if i < 0:
    # NOT an error: either a server-side mod (whose store is authoritative
    # immediately, so a caller needs no pipeline window at all) or a
    # client-side page that has not published yet.
    root.put("known", false)
    root.put("pushes", 0)
    root.put("stamp", 0)
  else:
    root.put("known", true)
    root.put("pushes", gClientPages[i].pushes)
    root.put("stamp", gClientPages[i].stamp)
  result = done(root).text

proc onModsIndex(url, body, session: string): string =
  ## ONE ENTRY PER GUID. A mod whose `sides` include both the server and the
  ## client -- `aowl.sain`, `aowl.maps`, `aowl.admin` today -- is loaded TWICE,
  ## once in each process, and answers the index on both transports: the
  ## in-process `SettingsIndexQuery` broadcast here, and a
  ## `/aowlspt/settings/client/sync` push from `host/settingsbridge.nim`. This
  ## used to concatenate the two lists blind, so every such mod appeared twice
  ## in the nav under the same name -- MEASURED against the live backend as
  ## three duplicated pairs, which is what a player reported as "two 'Bot AI'
  ## listed under mods". It is not a Bot AI bug and never was; nesting
  ## morebots/waypoints under `aowl.sain` only made the pair conspicuous.
  ##
  ## The guid, not the name, is the identity -- two mods may not share a guid,
  ## and the name is a display string that can legitimately repeat. The SERVER
  ## announcement wins the row (it is authoritative for the stored value the
  ## moment it is written), and the client push contributes only the fact that
  ## a client transport also carries this page, as `client:true`. So the list
  ## stays exactly as long as the number of DISTINCT mods declaring settings,
  ## which is the property `tools/settingsdump.py` asserts.
  ##
  ## Served from cache when nothing that affects the reply has changed since it
  ## was last built -- see `gIndexCache`. This is what keeps an idle main menu
  ## quiet: the poll still arrives, but it no longer fans a `SettingsIndexQuery`
  ## and a `SettingsPageQuery` out to every mod on every request.
  if gIndexCacheValid and gIndexCache.len > 0:
    return gIndexCache
  gAnnounced = @[]
  discard emit(settings.SettingsIndexQuery, "")
  var guids: seq[string] = @[]
  var a = arr()
  for m in gAnnounced:
    let g = jr.asText(jr.field(m, "guid"), "")
    if g.len > 0:
      if guids.contains(g):
        # Two announcements for one guid on ONE transport should not happen;
        # if it ever does, the row is dropped rather than duplicated, and the
        # drop is said out loud instead of showing up as a mystery twin.
        warn "settings index: '" & g & "' announced twice on the server " &
             "transport; keeping the first and dropping the duplicate"
        continue
      guids.add g
    a.add sv.raw(m)
  # The client-side mods, from what the game process last pushed. Marked
  # `client:true` so a reader can tell which transport a page comes over --
  # and so `tools/settingsdump.py` can assert the NEGATIVE that matters: no
  # mod declaring settings is missing from this list.
  for p in gClientPages:
    if guids.contains(p.guid):
      # Already announced by the server-side half of the same mod. Not an
      # error and not a warning: this is the normal, expected shape for every
      # mod whose `sides` name both processes.
      continue
    guids.add p.guid
    var o = obj()
    o.put("guid", p.guid)
    o.put("name", p.name)
    o.put("version", p.version)
    o.put("count", p.count)
    o.put("done", p.done)
    o.put("client", true)
    a.add done(o)
  # This hub NO LONGER contributes a page of its own. It used to append one
  # named "Settings Panel" carrying uihub's `launchHint` row -- and the F12
  # overlay ALSO synthesises a built-in page with the identical label (see
  # `AOWL_OV_PANEL_PAGE` in `abi/aowlspt_overlay.h`). Two guids, one label:
  # the player saw the same page twice, one of them holding a single row that
  # the other already had ("Startup message"; both drive `g_ov.hintEnabled`).
  #
  # The proxy could not simply be deleted before, because the overlay's own
  # `hint` row persisted ONLY to the overlay prefs file, which the launch-time
  # `GET /aowlspt/settings/aowl.uihub` overwrites on every start -- so this
  # page was the only DURABLE off-switch for the launch toast. It is not any
  # more: `aowl_ov_panel_set` now mirrors a `hint` write back to
  # `POST /aowlspt/settings/aowl.uihub`, the same place that GET reads from,
  # and says so in the host log whether it succeeds or fails.
  #
  # `aowl.uihub` is untouched -- same guid, same route, same `launchHint` key,
  # same config.json -- so every existing saved value keeps working.
  var root = obj()
  root.put("mods", a)
  result = done(root).text
  # Cache only a list that actually gathered mods. An empty list means the
  # server-side broadcast raced mod load (or nothing declared yet); caching that
  # would pin an empty nav until the next client push. A non-empty list is the
  # steady state and is what the idle poll should be served from.
  if guids.len > 0:
    gIndexCache = result
    gIndexCacheValid = true

# ---------------------------------------------------------------------------
# THE WHOLE SURFACE IN ONE DOCUMENT -- and the keybinds cut of it
# ---------------------------------------------------------------------------
#
#   GET /aowlspt/settings/index/full     (also: /aowlspt/settings/index?full=1)
#   GET /aowlspt/keybinds
#
# WHY. `/aowlspt/settings/index` answers with a LIST OF MODS and nothing else,
# so a consumer that wants to draw the rows must then fetch
# `/aowlspt/settings/<guid>` once per mod. The F12 overlay does exactly that --
# `modsettingsrender.nim` walks `gModSetMods` fetching one page per tick -- and
# a native MODS tab would have had to reimplement the same N+1 walk. One
# document, one fetch, one parse.
#
# ============================ READ THIS BEFORE FETCHING =====================
# WHEN a consumer fetches this MATTERS, and getting it wrong has taken the
# client down. This is not about the payload size.
#
# The overlay's HTTP worker has ONE sync slot, shared. `mods/manager`'s live
# mod control (load/unload/toggle) borrows it, and so does any settings fetch.
# MEASURED, in the host's own log (`modsettingsrender.nim`, the msIdle branch):
# fetching the mod schema BEFORE the character/mode screen has been answered
# "starves live mod control and pushes its mod load/unload work into the menu
# transition, which took the client down twice". The host now DEFERS its index
# arm until the first tick after Submit, and says so in the log rather than
# declining silently.
#
# So: fetch this LAZILY -- on the tab actually being opened, after the profile
# screen has been answered -- and never on a poll. Nothing on this side can
# enforce that; the route has no way to know what screen the client is on. It
# is stated here because the constraint lives in the CALLER and the reason for
# it lives in a different repo directory.
# ============================================================================
#
# NOT CACHED, deliberately, unlike the compact index above. Every `value` in
# here is read out of the owning mod's `config.json` at request time, so a
# cache would serve a value that a write through `/set` (or through any of the
# mod's own routes, or by the mod itself) has already replaced -- a settings
# page showing a stale value is indistinguishable, to a player, from a write
# that did not persist. The compact index can be cached because it carries no
# values at all, only counts.
var gPageAnnounced: seq[string] = @[]

proc onPageAnnounce(payload: string): string =
  if gPageAnnounced.len > 32:   # bounded, for the same reason as gApplyAnnounced
    gPageAnnounced = @[]
  gPageAnnounced.add payload
  result = ""

proc rowsForGuid(guid: string): string =
  ## The full schema array of ONE server-side mod, as JSON text, over the same
  ## in-process broadcast the index uses (`SettingsPageQuery` ->
  ## `SettingsPageAnnounce`). Empty string when nobody answered -- which is a
  ## distinct outcome from `"[]"` ("answered, and declares nothing"), and the
  ## caller keeps them apart.
  gPageAnnounced = @[]
  discard emit(settings.SettingsPageQuery, guid)
  for a in gPageAnnounced:
    if jr.asText(jr.field(a, "guid"), "") == guid:
      let r = jr.field(a, "rows")
      if r.exists:
        return jr.raw(r)
  result = ""

proc fullModsArray(): JsonArray =
  ## One entry per DISTINCT guid, each carrying its full schema. Same identity
  ## rule as `onModsIndex` -- guid, not name, and the server transport wins a
  ## mod that is loaded on both sides -- so the two routes can never disagree
  ## about how many mods there are.
  ##
  ## `gAnnounced` is shared with `onModsIndex`; both reset it immediately
  ## before their own broadcast and read it immediately after, which is the
  ## same single-request-at-a-time assumption the index has always made.
  gAnnounced = @[]
  discard emit(settings.SettingsIndexQuery, "")
  var guids: seq[string] = @[]
  var a = arr()
  # By index, not by iterator: `rowsForGuid` below emits a second broadcast
  # from inside this loop, and while nothing subscribed to it appends to
  # `gAnnounced`, iterating a seq that a callback could touch is a hazard not
  # worth taking for the sake of one line.
  for mi in 0 ..< gAnnounced.len:
    let m = gAnnounced[mi]
    let g = jr.asText(jr.field(m, "guid"), "")
    if g.len == 0 or guids.contains(g):
      continue
    guids.add g
    var o = obj()
    o.put("guid", g)
    o.put("name", jr.asText(jr.field(m, "name"), g))
    o.put("version", jr.asText(jr.field(m, "version"), ""))
    o.put("enabled", true)
    o.put("client", false)
    o.put("count", jr.asInt(jr.field(m, "count"), 0))
    o.put("done", jr.asInt(jr.field(m, "done"), 0))
    o.put("pageRoute", "/aowlspt/settings/" & g)
    o.put("applyRoute", "/aowlspt/settings/" & g & "/set")
    o.put("resetRoute", "/aowlspt/settings/" & g & "/reset")
    let rows = rowsForGuid(g)
    if rows.len > 0:
      o.put("settings", sv.raw(rows))
    else:
      # It announced a count but did not answer the page query. An EMPTY
      # ARRAY, never a null and never an absent field: a consumer iterating
      # `settings` must not have to null-check, and `rowsMissing` says that
      # this emptiness is a failure to look rather than a mod with nothing to
      # declare -- three outcomes, not two.
      o.put("settings", sv.raw("[]"))
      o.put("rowsMissing", true)
    a.add o
  for p in gClientPages:
    if guids.contains(p.guid):
      continue
    guids.add p.guid
    var o = obj()
    o.put("guid", p.guid)
    o.put("name", p.name)
    # Whatever the game process sent, which today is nothing --
    # `host/settingsbridge.nim` does not yet forward a version. Empty means
    # "the push did not say", never a number borrowed from somewhere else.
    o.put("version", p.version)
    o.put("enabled", true)
    o.put("client", true)
    o.put("count", p.count)
    o.put("done", p.done)
    o.put("pageRoute", "/aowlspt/settings/" & p.guid)
    o.put("applyRoute", "/aowlspt/settings/" & p.guid & "/set")
    o.put("resetRoute", "/aowlspt/settings/" & p.guid & "/reset")
    o.put("settings", sv.raw(p.rows))
    a.add o
  result = a

proc onIndexFull(url, body, session: string): string =
  ## `{"mods":[{guid,name,version,enabled,client,count,done,
  ##            pageRoute,applyRoute,resetRoute,settings:[row...]}...],
  ##   "enabledMeaning":"loaded"}`
  ##
  ## A row is exactly what `aowl/src/aowlspt/settings.nim`'s `toJson` emits:
  ##   key, label, type, default, value            -- always
  ##   min, max, step                              -- numeric rows with a range
  ##   options, optionLabels, optionsUrl           -- enum/select rows
  ##   colorFormat                                 -- colour rows, always
  ##   category, subcategory, path                 -- the GROUP, when grouped;
  ##                                                  `path` is the ordered
  ##                                                  segments to any depth
  ##   description                                 -- the help text, when given
  ##   implemented, appliesOn, keybind             -- always
  ## `type` is one of exactly: bool int float enum string keybind select color.
  ##
  ## `enabled` is `true` for every mod listed, and `enabledMeaning:"loaded"`
  ## says why that is not a tautology dressed as information: a mod that is
  ## installed and NOT selected is not loaded, so it never hears the broadcast
  ## and cannot appear here at all. This route can therefore only ever describe
  ## running mods. `/aowlspt/mods/list` (mods/manager) is the route that knows
  ## about the disabled ones.
  var root = obj()
  root.put("mods", fullModsArray())
  root.put("enabledMeaning", "loaded")
  result = done(root).text

proc textOf(j: JsonRef): string =
  ## A row value as DISPLAY TEXT, whatever JSON shape it has: a quoted string
  ## comes back unquoted, a number or a bool comes back as its literal. A
  ## keybind surface has to show one line of text per binding and the three
  ## shapes below all really occur (`"M"`, `114`, `true`).
  if not j.exists: return ""
  if jr.isText(j): return jr.asText(j, "")
  result = jr.raw(j)

proc keybindsOf(guid, rowsText: string): JsonArray =
  ## The keybind rows of one mod. THE PREDICATE IS THE DECLARED `keybind`
  ## FIELD and nothing else -- never a name match on "key", which gets this
  ## repo's real data wrong in both directions (it would miss `hotkeys` and
  ## `overlayToggleKey`, and it would wrongly include `mods/ammoloading`'s
  ## `hijackKey`, which is a BUNDLE NAME). See `Setting.keybind` and
  ## `isKeybind` in aowl/src/aowlspt/settings.nim.
  var a = arr()
  for row in jr.each(jr.whole(rowsText)):
    if not jr.asBool(jr.child(row, "keybind"), false):
      continue
    let key = jr.asText(jr.child(row, "key"), "")
    if key.len == 0:
      continue
    let ty = jr.asText(jr.child(row, "type"), "")
    let label = jr.asText(jr.child(row, "label"), "")
    let implemented = jr.asBool(jr.child(row, "implemented"), true)
    # THE THREE ROLES a keybind row really has. `stKeybind` is the only one
    # whose value IS a key name; the other two are a key that is stored as a
    # virtual-key CODE (`mods/debug`'s `overlayToggleKey` = 114) and the BOOL
    # GATE that has to be on before a key is polled at all (`hotkeys`). All
    # three belong on a keybinds page -- hiding the gate would show a key that
    # provably does nothing and no way to find out why -- but they are not
    # interchangeable, so the role is named rather than left to be guessed
    # from `type`.
    var role = "other"
    if ty == "keybind": role = "bind"
    elif ty == "int":   role = "vkcode"
    elif ty == "bool":  role = "gate"
    var o = obj()
    o.put("key", key)
    o.put("settingKey", key)
    # NEVER EMPTY: a row with no label falls back to its config key, because a
    # keybind list drawn with a blank action column is unusable and the key is
    # at least something the player can look up.
    o.put("action", (if label.len > 0: label else: key))
    o.put("description", jr.asText(jr.child(row, "description"), ""))
    # THE BOUND VALUE, under BOTH names.
    #
    # `currentBinding`/`defaultBinding` are the names this route has always
    # used; `value`/`default` are what the native Controls -> MODS page reads,
    # and are the names every OTHER settings surface in this repo uses for the
    # same two things (`toJson` in aowl/src/aowlspt/settings.nim emits exactly
    # `default` and `value`). Both pairs are emitted from the SAME row, so they
    # cannot disagree; the old names stay for compatibility with the F12
    # overlay, exactly as `key`/`settingKey` are kept as a pair.
    #
    # NO SEPARATE CONFIG READ HAPPENS HERE, deliberately. The row already came
    # through `fullModsArray()` -> `SettingsPageQuery` -> the owning mod's
    # `toJson`, whose `value` is `currentValueJson` -- the mod's own
    # `config.json` read, in the process that owns the file. A second reader
    # here would be a second answer to "what is bound", and the two would
    # diverge the moment a write landed between them.
    let vRow = jr.child(row, "value")
    let dRow = jr.child(row, "default")
    let vKnown = vRow.exists and not jr.isNull(vRow)
    let dKnown = dRow.exists and not jr.isNull(dRow)
    o.put("currentBinding", textOf(vRow))
    o.put("defaultBinding", textOf(dRow))
    if vKnown:
      o.put("value", textOf(vRow))
    else:
      # THREE OUTCOMES, NOT TWO. The row declared itself a keybind but the
      # settings store carries no value for its key -- so the page must show
      # "unknown", not a blank that reads as "unbound". Omitting the field
      # instead would make a consumer's `entry.value` undefined, which is
      # indistinguishable from this route being too old to serve it.
      o.put("value", sv.jnull())
      o.put("error", "unknown setting key")
    if dKnown:
      o.put("default", textOf(dRow))
    else:
      o.put("default", sv.jnull())
    o.put("valueType", ty)
    o.put("role", role)
    # A gate is not rebindable (it is a switch, not a key), and neither is a
    # row the owning mod declared unimplemented -- rebinding a key that is not
    # wired to anything is the control-that-changes-nothing failure.
    o.put("rebindable", implemented and (role == "bind" or role == "vkcode"))
    o.put("implemented", implemented)
    o.put("category", jr.asText(jr.child(row, "category"), ""))
    o.put("applyRoute", "/aowlspt/settings/" & guid & "/set")
    a.add o
  result = a

proc onKeybinds(url, body, session: string): string =
  ## `GET /aowlspt/keybinds` -> every keybind of every loaded mod.
  ##
  ##   {"mods":[{"guid","name","version","client",
  ##             "keybinds":[{"key","settingKey","action","description",
  ##                          "value","default",
  ##                          "currentBinding","defaultBinding","valueType",
  ##                          "role","rebindable","implemented","category",
  ##                          "applyRoute","error"}...]}...]}
  ##
  ## `value` is THE KEY THE PLAYER HAS BOUND RIGHT NOW, as display text, and
  ## `default` the one the mod declared; `currentBinding`/`defaultBinding` are
  ## the older names for the same two values and are kept for the F12 overlay,
  ## the same way `key`/`settingKey` are kept as a pair. `value` is a JSON
  ## STRING whenever the store knows the key and `null` -- with
  ## `"error":"unknown setting key"` beside it -- when it does not. It is never
  ## absent: an omitted field reads to a consumer as "this backend is too old
  ## to answer", which is a different fact.
  ##
  ## EVERY loaded mod appears, including one with no keys at all: its
  ## `keybinds` is `[]`. An absent entry would be indistinguishable from a mod
  ## that failed to answer, and this route is meant to be the answer to "what
  ## can I bind", which includes "this mod, nothing".
  ##
  ## Writing a binding is `POST <applyRoute> {"key":<settingKey>,"value":...}`,
  ## where the value literal must match `valueType`: a JSON STRING for `bind`
  ## (`"M"`), a JSON NUMBER for `vkcode` (`114`), a bool for `gate`. That is
  ## why `valueType` is carried per row -- writing the wrong shape persists it
  ## verbatim into the mod's config.json, where the mod's own parser will read
  ## its default instead and the key will silently do nothing.
  ##
  ## Same lazy-fetch rule as `/aowlspt/settings/index/full`; see the warning
  ## above it.
  ## Built from the SAME `fullModsArray()` the full index serves, and filtered
  ## afterwards, so the two routes cannot drift into disagreeing about which
  ## mods exist or what a row's current value is.
  let full = sv.text(done(fullModsArray()))
  var a = arr()
  for m in jr.each(jr.whole(full)):
    let g = jr.asText(jr.child(m, "guid"), "")
    var o = obj()
    o.put("guid", g)
    o.put("name", jr.asText(jr.child(m, "name"), g))
    o.put("version", jr.asText(jr.child(m, "version"), ""))
    o.put("client", jr.asBool(jr.child(m, "client"), false))
    o.put("keybinds", keybindsOf(g, jr.raw(jr.child(m, "settings"))))
    a.add o
  var root = obj()
  root.put("mods", a)
  result = done(root).text

proc urlHasFull(url: string): bool =
  ## Is `full=1` anywhere in this url's query string? Hand-rolled rather than
  ## parsed: the only parameter this route has ever taken is this one, and a
  ## half-written query parser is a thing to maintain for no gain.
  result = false
  if url.len < 6:
    return
  for i in 0 .. url.len - 6:
    if url.substr(i, i + 5) == "full=1":
      return true

proc onIndexRoute(url, body, session: string): string =
  ## `/aowlspt/settings/index`. COMPACT by default -- byte-for-byte the reply
  ## it has always given, because the F12 overlay POLLS this route at an idle
  ## main menu and fattening it with every row of every mod would put the whole
  ## schema on the wire several times a second for nothing. `?full=1` is the
  ## same document `/aowlspt/settings/index/full` serves, for a caller that
  ## wants one fetch instead of N+1 -- and that caller must read the lazy-fetch
  ## warning above `onIndexFull` first.
  if urlHasFull(url):
    return onIndexFull(url, body, session)
  result = onModsIndex(url, body, session)

proc onLoad(): Status =
  if side() != sideServer:
    info "the SPT settings surface is a server mod; nothing to do on this side"
    return Ok
  sptSurface = sptSurfaceText()
  if serve(IndexRoute, onIndex) != Ok:
    warn "could not register the SPT settings index route"
  if servePrefix(PagePrefix, onPage) != Ok:
    warn "could not register the SPT settings page route"
  if serve(ModsIndexRoute, onIndexRoute) != Ok:
    warn "could not register " & ModsIndexRoute
  if serve(ModsIndexFullRoute, onIndexFull) != Ok:
    warn "could not register " & ModsIndexFullRoute &
         " -- a native settings tab will have to fall back to N+1 per-mod " &
         "fetches"
  if serve(KeybindsRoute, onKeybinds) != Ok:
    warn "could not register " & KeybindsRoute &
         " -- a keybinds page will have nothing to list"
  if serve(ClientSyncRoute, onClientSync) != Ok:
    warn "could not register " & ClientSyncRoute &
         " -- client-side mods will stay invisible in the F12 settings nav"
  if servePrefix(ClientStatusPrefix, onClientStatus) != Ok:
    warn "could not register " & ClientStatusPrefix &
         " -- the F12 panel will fall back to a wall-clock wait and may " &
         "report a slow-but-working client edit as NOT APPLIED"
  if servePrefix(ClientPagePrefix, onClientPage) != Ok:
    warn "could not register " & ClientPagePrefix
  if on(settings.SettingsIndexAnnounce, onAnnounce) != Ok:
    warn "could not subscribe to " & settings.SettingsIndexAnnounce &
         " -- " & ModsIndexRoute & " will always report an empty mod list"
  if on(settings.SettingsPageAnnounce, onPageAnnounce) != Ok:
    warn "could not subscribe to " & settings.SettingsPageAnnounce &
         " -- " & ModsIndexFullRoute & " will list every mod with an EMPTY " &
         "settings array and rowsMissing:true"
  if on(settings.SettingsApplyAnnounce, onApplyAnnounce) != Ok:
    warn "could not subscribe to " & settings.SettingsApplyAnnounce &
         " -- every POST to /aowlspt/settings/<guid>/set will report that " &
         "nobody answered, even when the write went through"
  let pages = jr.field(sptSurface, "pages")
  success ModName & " " & ModVersion & " serving " & $jr.count(pages) &
          " SPT config pages (all not implemented yet)"
  Ok

exportMod(
  guid = ModGuid,
  name = ModName,
  author = ModAuthor,
  version = ModVersion,
  sptRange = "*",
  sides = {sideServer},
  onLoad = onLoad)
