## ===========================================================================
## dlssrows.nim -- the DLSS section on the stock GRAPHICS page (the GENERAL
## subtab), built by INSTANTIATING THE GAME'S OWN SETTINGS-ROW PREFABS.
##
## Same mechanism as `postfxrows.nim`, a different tab and a different mod:
## five rows for `aowl.dlss` go into the container the game's own 33 Graphics
## rows live in, so they look like -- because they ARE -- stock controls.
##
## WHERE THE ROWS GO, AND HOW THAT WAS OBTAINED
## --------------------------------------------
## `EFT.UI.Settings.GraphicsSettingsTab`, offsets read from
## `Il2CppMetadataRegistration.fieldOffsets` (`tools/fldoff.py fields
## EFT.UI.Settings.GraphicsSettingsTab`, the System.String self-check passing),
## never guessed and NOT shared with `PostFXSettingsTab`, whose numbers differ:
##
##     0x98  _settingsContainer         Transform            <- THE ROW PARENT
##     0xb0  _dropDownTemplate          SettingDropDown      (declined, below)
##     0xb8  _toggleTemplate            SettingToggle        <- PREFAB
##     0xc0  _selectSliderTemplate      SettingSelectSlider  (declined, below)
##     0xc8  _selectFloatSliderTemplate SettingFloatSlider   <- PREFAB
##
## `_settingsContainer` is the same object a live walk measured on the deployed
## build as holding "exactly the 33 stock rows and none of ours" (see the
## STOCK-GEOMETRY BASELINE note in `modstab.nim`), which is why it is the
## parent rather than the panel root: the panel's LayoutGroup drives it.
##
## The tab COMPONENT is reached by WALKING from `gGfxPanelT` -- the live
## "Graphics Settings" panel transform the subtab feature already located and
## validated -- and never by an offset that can read null.
##
## THE TWO CHOICES ARE DROPDOWNS -- and what had to be measured first
## ------------------------------------------------------------------
## "DLSS version" and "Upscaler" are choices. They were STEP-VALUED SLIDERS
## until 2026-09-04, because every declared bind on `SettingDropDown` and
## `SettingSelectSlider` (`BindTo`, `BindToEnum`, `UpdateDropDownValue`, all
## three `BindIndexTo` overloads) is a GENERIC method with no entry in
## `methodPointers` and therefore no RVA offline. That is still true. What
## changed is that a dropdown does not NEED one of those binds: the widget is
## driven directly through three non-generic functions, and the selection is
## read off the widget instead of arriving as an event.
##
##   `SettingDropDown.DropDown` @0xA8            -> the EFT.UI.DropDownBox
##   `BaseDropDownBox::Show(IEnumerable<string>, Func<int,bool>)`  -- the items
##   `BaseDropDownBox::set_/get_CurrentIndex` @0x698560 / @0x698550  -- the value
##   `GraphicsSettingsTab._dropDownTemplate` @0xB0  -- the prefab
##
## `settingsbind.nim` gained an `sbdDropdown` kind for it, POLLED once per tick
## through `get_CurrentIndex` rather than through a drain: there is no
## `DropDownBox` detour to ride, and binding a second one to make an event
## would overwrite another feature's trampoline.
##
## THE ONE REAL HAZARD, and how it is settled. `Show` does not `isinst` its
## argument; it INTERFACE-DISPATCHES on it through the stub at RVA 0x52D0
## (disassembled), which walks the receiver's `interfaceOffsets`. A miss leaves
## a slow path whose throw would be MANAGED and therefore uncatchable by
## `aowl_p_p_seh`. Whether a `String[]` carries `IEnumerable<string>` CANNOT be
## answered offline -- IL2CPP builds array classes at runtime and every
## `Il2CppGenericClass.cached_class` in the metadata file is null -- so it is
## answered AT RUNTIME, in `nuDropDownShow`, by reading the same table with the
## same stride the stub reads before the call is made. A refusal there builds
## the row as a SLIDER instead, which is the shape that has been shipping.
##
## TOOLTIPS -- previously declined, now measured and built
## -------------------------------------------------------
## The earlier pass declined them, saying that constructing a
## `SettingsTooltipData` was "runtime type injection, PLAUSIBLE and UNPROVEN".
## That was wrong in two ways and is corrected rather than deleted:
##   * `il2cpp_object_new` is UNGATED (it is in `aowl_il2cpp_exports` and NOT
##     in `aowl_gate_rows`) and takes an ordinary klass pointer -- which is
##     borrowed from a LIVE donor, the stock DlssPreset row's own
##     `_tooltipSettingsHover@0x98 -> _tooltipData@0x20`. Nothing is injected.
##   * MEASURED `disasm 0x16fac00 --len 940`: `SetTooltip` does not KEEP the
##     object it is given. It constructs its own through
##     `SettingsTooltipData::.ctor(ESettingsOption)` @0x16FCD70 and copies the
##     fields across. So what we build is a TEMPLATE, and the six stores go
##     through `hostfieldwrite`'s typed gate over FieldRefs generated by
##     `tools/fieldrefs.py` (widths and is-reference bits DERIVED, never
##     spelled in this file).
## SetTooltip has THREE no-op paths (`_blocker@0x88` null, `TryGetTooltip`
## false, data null) and no throw path, so the verdict cannot be the call's
## return: it re-reads `_tooltipSettingsHover@0x98 -> _tooltipData@0x20 ->
## Text@0x20` off each row and requires the pointer to be the interned string
## that was handed over.
##
## THE VALUES ARE THE CONFIG'S, OR THE DECLARED DEFAULTS, AND THE LOG SAYS WHICH
## ---------------------------------------------------------------------------
## `sbdRegisterSlider` / `sbdRegisterToggle` seed each row from the mod's live
## `/aowlspt/settings/aowl.dlss` page when `modSettingsRender` has fetched one,
## and return whether they did. Rows that were not seeded show the DECLARED
## default, and the verdict counts them separately -- printing a default and
## letting it read as the player's setting is a confident wrong answer.
##
## NOTHING HERE APPLIES ANYTHING. Every one of these takes effect on the next
## launch: `aowlspt-launch` runs `tools/dlssapply.py` before the client starts
## (the DLL is open in this process and OptiScaler read its ini at attach) and
## prints the PASS/FAIL verdict in the boot log. The captions say so.
##
## SAFETY, against the eight rules
## -------------------------------
##  1. No detour is bound here at all. Every call is a direct call to a
##     byte-verified prologue through `nuikit`'s target table
##     (`nuTargetsBindOk()` is checked before the first one).
##  2. Every pointer hop is `nuOk`/`nuAlive`/`duOk`-guarded.
##  3. NO guard is opened: this runs inside `gfxTickBody`'s single
##     `aowl_p_p_seh`, which is not re-entrant.
##  4. Every loop is capped (`DlrMaxRows`).
##  5. Flag-gated `settingsDlssRows`, DEFAULT OFF, with `settingsDlssDropdowns`
##     and `settingsDlssTooltips` as their own DEFAULT-OFF sub-flags -- with
##     both off this file behaves exactly as it did before this change.
##     Inert without
##     `settingsPostFxSubtab` (which is what locates the Graphics panel) and
##     `nativeUiKit`.
##  6. Self-disables after `DlrMaxFaults`.
##  7. After the one-shot build the tick is two boolean tests; no allocation.
##  8. Nothing stock is ever written. The rows are OURS -- they are not added
##     to `SettingsTab._createdControls`, so the game never destroys them and
##     this file destroys them itself on every screen close, which is also what
##     stops them duplicating when the page is re-entered.
## ===========================================================================

const
  DlrMaxFaults = 3
  DlrMaxRows = 8
  DlrGuid = "aowl.dlss"

  ## MEASURED, see the header. GraphicsSettingsTab's own numbers.
  DlrOffGfxContainer  = 0x98'i32
  DlrOffToggleTmpl    = 0xb8'i32
  DlrOffFloatSliderTmpl = 0xc8'i32
  DlrOffDropDownTmpl  = 0xb0'i32
  ## SettingControl, for the tooltip diagnosis. MEASURED, `tools/fldoff.py
  ## fields EFT.UI.Settings.SettingDropDown`.
  DlrOffScBlocker     = 0x88'i32
  DlrOffScTooltipHover = 0x98'i32

var gDlrOn = false        ## `settingsDlssRows` -- read once at boot
var gDlrOff = false       ## self-disabled
var gDlrBuilt = false
var gDlrTried = 0
var gDlrFaults = 0
var gDlrSaid = false
var gDlrRowGo: seq[Il2CppPtr] = @[]
var gDlrRowKey: seq[string] = @[]
var gDlrBuiltN = 0
var gDlrSeeded = 0
var gDlrRefused = 0
var gDlrRowT: seq[Il2CppPtr] = @[]   ## each row's TRANSFORM, for placement
var gDlrRowCtrl: seq[Il2CppPtr] = @[]  ## each row's SettingControl, for tooltips
var gDlrRowTip: seq[string] = @[]      ## the tooltip body each row should show
var gDlrTipWant: seq[Il2CppPtr] = @[]  ## the INTERNED string handed to SetTooltip
## THE DROPDOWN LABEL. Parallel to `gDlrRowGo`: the `EFT.UI.DropDownBox` the
## builder already held (never re-found), and the caption list that row
## declares. Both are needed AFTER the build loop because the index a row ends
## up on is decided inside `sbdRegisterDropdown` from the player's config, and
## the label has to name whichever value that was.
var gDlrRowDdb: seq[Il2CppPtr] = @[]
var gDlrRowChoices: seq[seq[string]] = @[]
var gDlrPlaced = -1       ## rows whose sibling index READ BACK as asked
var gDlrPlaceWhy = ""     ## why placement did not happen, when it did not
var gDlrRestartShown = 0
var gDlrDropOn = false    ## `settingsDlssDropdowns` -- read once at boot
var gDlrTipsOn = false    ## `settingsDlssTooltips`  -- read once at boot
## THE DROPDOWN CENSUS. "asked for a dropdown", "got one", and "fell back to
## the slider" are three different outcomes and none of them may be inferred
## from either of the others.
var gDlrDropWanted = 0
var gDlrDropBuilt = 0
var gDlrDropWhy = ""
## THE TOOLTIP CENSUS. `gDlrTipVerified` is the only number that means the
## player can see a tooltip: it counts rows whose `_tooltipSettingsHover@0x98
## -> _tooltipData@0x20 -> Text@0x20` READ BACK as the exact interned string
## that was handed to SetTooltip.
## THE LABEL CENSUS. `gDlrLblVerified` is the only number that means the player
## can READ the value: it counts boxes whose `_currentValueText@0xf0` TMP reads
## back the chosen caption. `gDlrLblInconclusive` is the third outcome and is
## NOT folded into either of the other two -- a `DropDownBoxNewStyle` receiver
## has no `_currentValueText` field at all, so "could not look" must not print
## as "the label is wrong".
var gDlrLblAsked = 0
var gDlrLblCalled = 0
var gDlrLblVerified = 0
var gDlrLblInconclusive = 0
var gDlrLblWhy = ""
var gDlrTipAsked = 0
var gDlrTipCalled = 0
var gDlrTipVerified = 0
var gDlrTipWhy = ""
var gDlrTipKlass: Il2CppPtr = nil

type
  DlrKind = enum dlrToggle, dlrSlider, dlrDropdown

  DlrRow = object
    kind*: DlrKind
    key*: string
    label*: string
    fmt*: string        ## NumberSlider::Show format; "F0" for the steppers
    lo*, hi*, def*: float32
    defB*: bool
    ## For `dlrDropdown` only: the captions, in order, and the ONE-BASED
    ## default. The catalogue is the single place the choice text lives, so the
    ## row caption and the item list cannot say different things.
    choices*: seq[string]
    ## The tooltip body, condensed from the matching "//key" description in
    ## `mods/dlss/config.json`. A STATIC MIRROR, exactly like the ranges above
    ## -- it drifts if that file changes, and nothing here pretends otherwise.
    tip*: string

proc dlrS(key, label, fmt: string; lo, hi, def: float32;
          tip: string = ""): DlrRow =
  DlrRow(kind: dlrSlider, key: key, label: label, fmt: fmt,
         lo: lo, hi: hi, def: def, defB: false, choices: @[], tip: tip)

proc dlrB(key, label: string; def: bool; tip: string = ""): DlrRow =
  DlrRow(kind: dlrToggle, key: key, label: label, fmt: "",
         lo: 0.0'f32, hi: 0.0'f32, def: 0.0'f32, defB: def,
         choices: @[], tip: tip)

proc dlrD(key, label: string; choices: seq[string]; def: float32;
          tip: string = ""): DlrRow =
  ## A CHOICE row. `def` is ONE-BASED, the same number the config and the F12
  ## overlay carry. `lo`/`hi` mirror the choice count so the slider FALLBACK --
  ## used whenever the dropdown path refuses -- is identical to the stepper
  ## this file shipped before dropdowns existed.
  DlrRow(kind: dlrDropdown, key: key, label: label, fmt: "F0",
         lo: 1.0'f32, hi: float32(choices.len), def: def, defB: false,
         choices: choices, tip: tip)

proc dlrCatalogue(): seq[DlrRow] =
  ## The five settings `mods/dlss/dlss.nim:schema()` declares, with ITS ranges
  ## and ITS defaults. A STATIC MIRROR of that schema (the live values come
  ## from the fetch, the RANGES do not), so it drifts if the mod's schema
  ## changes -- `tools/dlssapply.py selftest` cross-checks the naming.
  ##
  ## THE " - applies on restart" SUFFIX IS CONDITIONAL, and the condition is
  ## the honest one. It is dropped only when `settingsRowsBind` is live, i.e.
  ## when a SAVE can actually reach `dlrOnSaved` and raise the game's own
  ## restart confirmation. With the bind OFF nothing observes the SAVE, no
  ## dialog can appear, and a caption that had quietly stopped saying so would
  ## leave the player with no statement anywhere that these need a restart.
  let sfx = (if sbdReady(): "" else: " - applies on restart")
  # THE CAPTION CARRIES THE CHOICE MAPPING only when the row ends up as a
  # SLIDER, and the text is DERIVED from `choices` in `dlrChoiceMap` at that
  # moment -- not written twice here. A dropdown captioned "1 = DLSS / 2 = FSR
  # 3.1" beside a box already reading "FSR 3.1" is two answers to one question,
  # and a mapping hard-coded here would disagree with `choices` the first time
  # either changed.
  @[dlrD("version", "DLSS version" & sfx,
         @["310.5.3", "310.7.0", "310.7.129"], 2.0'f32,
         "Which DLSS Super Resolution DLL to install. 310.5.3 is the one " &
         "shipped with the game and is the rollback target. Applies on the " &
         "next launch: the DLL is locked while the client runs."),
    dlrD("upscaler", "Upscaler" & sfx,
         @["DLSS", "FSR 3.1", "XeSS"], 1.0'f32,
         "OptiScaler's Dx11Upscaler. DLSS is the game's own, native DX11; " &
         "FSR 3.1 and XeSS go through OptiScaler's DX11-on-DX12 bridge. Only " &
         "takes effect when OptiScaler is installed beside the executable. " &
         "Applies on the next launch."),
    dlrB("nrEnabled", "DLSS 5 re-lighting" & sfx, false,
         "OptiScaler [DlssNr] Enabled -- the leaked neural re-lighting pass. " &
         "An unsigned third-party rebuild of a leaked NVIDIA binary, with a " &
         "stated 616.56 driver minimum, bridged onto D3D12 -- which REPLACES " &
         "DLSS with FSR/XeSS while it is on. Off by default. See docs/DLSSNR.md."),
    dlrS("nrWorkingScale", "DLSS 5 working scale" & sfx,
         "F2", 0.25'f32, 1.0'f32, 0.25'f32,
         "OptiScaler [DlssNr] WorkingScale, 0.25 to 1 -- the fraction of the " &
         "frame the model works on. Cost falls with the SQUARE of this. " &
         "Applies on the next launch."),
    dlrS("nrIntensity", "DLSS 5 intensity" & sfx,
         "F2", 0.0'f32, 2.0'f32, 1.0'f32,
         "OptiScaler [DlssNr] Intensity, 0 to 2 -- how hard the model's " &
         "re-lighting reads. Applies on the next launch.")]

proc dlrChoiceMap(r: DlrRow): string =
  ## "  (1 = DLSS / 2 = FSR 3.1 / 3 = XeSS)" -- the caption suffix a CHOICE row
  ## needs when it is built as a stepper slider instead of a dropdown, derived
  ## from the catalogue's own `choices` so the two can never disagree.
  result = ""
  if r.choices.len == 0: return
  var acc = "  ("
  var i = 0
  while i < r.choices.len and i < 16:
    if i > 0: acc = acc & " / "
    acc = acc & $(i + 1) & " = " & r.choices[i]
    i = i + 1
  acc & ")"

proc dlrNoteFault(what: string) =
  inc gDlrFaults
  warn "dlss rows: " & what & " (fault " & $gDlrFaults & " of " &
       $DlrMaxFaults & ")"
  if gDlrFaults >= DlrMaxFaults:
    gDlrOff = true
    warn "dlss rows: self-disabled for this session after " & $gDlrFaults &
         " fault(s). No row of ours is left in the Graphics page."

proc dlrDestroyAll(): int =
  ## Tear down every row WE made. The game never will: they are deliberately
  ## not in `SettingsTab._createdControls` (that list is an instantiated
  ## generic whose layout is not reachable offline, and a raw write into one is
  ## a fabricated offset into a collection the game then iterates).
  result = 0
  var i = 0
  while i < gDlrRowGo.len and i < DlrMaxRows:
    let go = gDlrRowGo[i]
    if go != nil and duOk(go, 0x20'i32) and iUnityAlive(go):
      if nuDestroy(go): result = result + 1
    i = i + 1
  gDlrRowGo = @[]
  gDlrRowKey = @[]
  gDlrRowT = @[]
  gDlrRowCtrl = @[]
  gDlrRowTip = @[]
  gDlrTipWant = @[]
  gDlrRowDdb = @[]
  gDlrRowChoices = @[]
  gDlrDropWanted = 0
  gDlrDropBuilt = 0
  gDlrDropWhy = ""
  gDlrTipAsked = 0
  gDlrTipCalled = 0
  gDlrTipVerified = 0
  gDlrTipWhy = ""
  gDlrPlaced = -1
  gDlrPlaceWhy = ""
  gDlrBuilt = false
  gDlrBuiltN = 0
  gDlrSeeded = 0
  gDlrRefused = 0

proc dlrTab(): Il2CppPtr =
  ## The live `GraphicsSettingsTab` COMPONENT, by WALKING from the validated
  ## "Graphics Settings" panel transform. `modsComponent` refuses a GameObject
  ## receiver up front, which is the fault this walk would otherwise take.
  result = nil
  if gGfxPanelT == nil or not duOk(gGfxPanelT, 0x20'i32): return
  if not iUnityAlive(gGfxPanelT): return
  result = modsComponent(gGfxPanelT, "GraphicsSettingsTab")
  if result != nil and not nuOk(result, DlrOffFloatSliderTmpl + 8'i32):
    result = nil

proc dlrMakeRow(prefab, parent: Il2CppPtr; r: DlrRow; asDropdown: bool;
                sliderOut, ctrlOut, ddbOut: var Il2CppPtr): Il2CppPtr =
  ## ONE row, the game's own way. No `SetSiblingIndex` is called: `Instantiate`
  ## appends, which puts our section AFTER the stock rows -- and any index we
  ## chose would REORDER controls the game created, which is a write to stock
  ## state this file does not make.
  result = nil
  sliderOut = nil
  ctrlOut = nil
  ddbOut = nil
  let row = nuInstantiateUnder(prefab, parent)
  if row == nil: return
  let go = nuGameObjectOf(row)
  if go == nil:
    warn "dlss rows: the instantiated row for '" & r.key & "' has no " &
         "reachable GameObject, so it could be neither shown nor torn down. " &
         "Refusing this row."
    return
  # `SetText` takes a LOCALIZATION KEY; an aowlspt setting has no BSG locale
  # entry, so the literal renders as itself. A raw `m_text` store would be
  # clobbered by `LocalizedText`, which is why the setter is called.
  let caption = (if r.kind == dlrDropdown and not asDropdown:
                   r.label & dlrChoiceMap(r) else: r.label)
  if not nuRowSetText(row, caption):
    warn "dlss rows: SetText refused for '" & r.key & "'; the row would carry " &
         "the PREFAB's own caption, which reads as a stock setting that is " &
         "not there. Refusing this row."
    discard nuDestroy(go)
    return
  discard nuRowSetName(row, "aowlspt-dlss-" & r.key)
  if asDropdown:
    # A CLONED `SettingDropDown`. The widget is reached through
    # `SettingDropDown.DropDown` @0xA8 and filled by CALLING the game's own
    # `Show` -- see `nuDropDownShow`, which refuses unless the receiver's own
    # vtable slot 24 resolves to one of three byte-verified bodies AND the
    # String[] it built really carries `IEnumerable<string>` in the interface
    # table `Show` dispatches against.
    let ddb = nuDropDownOf(row)
    if ddb == nil:
      gDlrDropWhy = "SettingDropDown.DropDown @0xA8 read null or unreadable " &
                    "on the cloned row, so there is no DropDownBox to fill"
      discard nuDestroy(go)
      return
    var why = ""
    if not nuDropDownShow(ddb, r.choices, why):
      gDlrDropWhy = why
      discard nuDestroy(go)
      return
    ddbOut = ddb
  elif r.kind == dlrSlider or r.kind == dlrDropdown:
    let sl = nuRowSlider(row)
    if sl == nil:
      warn "dlss rows: '" & r.key & "' instantiated but its inner NumberSlider " &
           "(SettingFloatSlider.Slider @0xa8) read null, so the row would show " &
           "a slider with no range and no value. Refusing it."
      discard nuDestroy(go)
      return
    if not nuSliderShow(sl, r.lo, r.hi, r.fmt):
      warn "dlss rows: NumberSlider::Show refused for '" & r.key & "' (range " &
           nuF(r.lo) & ".." & nuF(r.hi) & "). Refusing this row."
      discard nuDestroy(go)
      return
    discard nuSliderSetValue(sl, r.def)
    sliderOut = sl
  discard nuSetActive(go, true)
  ctrlOut = row
  result = go

## ---------------------------------------------------------------------------
## PLACEMENT -- our section sits DIRECTLY AFTER the stock DLSS pair
##
## `Instantiate` appends, so without this the five rows land at the BOTTOM of
## the Graphics page, far from the two stock rows they belong with
## ("Setting14: NvidiaDlss" and "Setting15: DlssPreset"). Order inside the row
## container is the container's LayoutGroup's business and sibling index is how
## the game itself orders its own rows, so it is the only ordering that
## survives a relayout.
##
## THE ANCHOR IS FOUND BY NAME, ON THE LIVE CONTAINER, EVERY BUILD -- never by
## a remembered index. "Setting15" is a POSITION in BSG's own list: a patch
## that adds one graphics setting renumbers it, and an index we cached would
## then insert our block in the middle of an unrelated stock section while
## every call still succeeded. The name that carries meaning is `DlssPreset`,
## so that is the substring matched, and the numeric prefix is not required.
##
## THE VERDICT IS A READBACK THROUGH `Transform::GetSiblingIndex`, which is a
## different function from the one that wrote it (both named in the nativeui
## positional self-check for exactly that reason). It can FAIL: if the write
## did not take, or Unity clamped it, the index read back differs from the one
## asked for and the count says so.
const DlrMaxScanChildren = 128
const DlrAnchorName = "DlssPreset"

proc dlrFindAnchor(parent: Il2CppPtr; outIdx: var int32; why: var string): bool =
  ## The sibling index of the stock `Setting15: DlssPreset` row under
  ## `parent`, by walking the container's children and reading each
  ## GameObject's own name. Bounded by `DlrMaxScanChildren` and every hop
  ## validated: a corrupt `childCount` inside a frame is an infinite loop on
  ## the Unity main thread.
  result = false
  outIdx = -1'i32
  why = ""
  var n = 0
  if not iChildCount(parent, n):
    why = "the row container did not answer childCount"
    return
  if n <= 0 or n > DlrMaxScanChildren:
    why = "the row container reported " & $n & " child(ren), which is outside " &
          "the 1.." & $DlrMaxScanChildren & " range this walk accepts"
    return
  var i = 0
  var seen = 0
  while i < n and i < DlrMaxScanChildren:
    let c = iChildAt(parent, i)
    if c != nil and duOk(c, 0x20'i32) and iUnityAlive(c):
      seen = seen + 1
      let nm = iObjName(c)
      if nm.len > 0 and modsNameHas(nm, DlrAnchorName):
        outIdx = int32(i)
        return true
    i = i + 1
  why = "no child of the row container has a name containing '" &
        DlrAnchorName & "' (" & $seen & " of " & $n & " children were live " &
        "and named). The stock DLSS pair is not on this page on this build"
  false

proc dlrPlaceRows(parent: Il2CppPtr) =
  ## Move every row of ours to sit immediately after the anchor, in catalogue
  ## order, and READ BACK where each one landed.
  ##
  ## The moves go in ascending order for a reason: our rows start at the END of
  ## the container, so moving the first to `anchor+1` shifts everything between
  ## `anchor+1` and its old slot up by one -- the anchor itself does not move,
  ## because it sits BELOW the insertion point. Re-reading the anchor between
  ## moves would therefore be wrong as often as it was right.
  gDlrPlaced = -1
  gDlrPlaceWhy = ""
  if gDlrRowT.len == 0:
    gDlrPlaceWhy = "no row transform was captured, so nothing could be moved"
    return
  var anchorIdx = -1'i32
  var why = ""
  if not dlrFindAnchor(parent, anchorIdx, why):
    gDlrPlaceWhy = why
    return
  var ok = 0
  var k = 0
  while k < gDlrRowT.len and k < DlrMaxRows:
    let t = gDlrRowT[k]
    let want = anchorIdx + 1'i32 + int32(k)
    if t != nil and duOk(t, 0x20'i32) and iUnityAlive(t) and
       nuSetSiblingIndex(t, want):
      let (readOk, got) = nuSiblingIndex(t)
      if readOk and got == want: ok = ok + 1
    k = k + 1
  gDlrPlaced = ok

## ---------------------------------------------------------------------------
## TOOLTIPS -- the game's own hover tooltip, on our rows
##
## `SettingControl::SetTooltip(SettingsTooltipData, SettingsTooltip)` @0x16FAC00
## (UNIQUE, non-virtual, section `il2cpp`) does NOT keep the object it is
## handed: MEASURED `disasm 0x16fac00 --len 940`, it builds its own through
## `SettingsTooltipData::.ctor(ESettingsOption)` @0x16FCD70, copies the fields
## across (`mov rax,[rbp+0x20]` -> `mov [rdi+0x20],rax` is Text), and stores
## the hover area into `_tooltipSettingsHover@0x98`. It has THREE no-op paths
## -- `_blocker@0x88` null, `UiElementBlocker::TryGetTooltip` false, and a null
## data argument -- and NO throw path.
##
## So what we build is a TEMPLATE, and `true` from the call proves nothing.
## The verdict re-reads `_tooltipSettingsHover@0x98 -> _tooltipData@0x20 ->
## Text@0x20` off each row and requires the POINTER to be the exact interned
## string that was handed over, which is a property of the finished state and
## is falsifiable by every one of the three no-op paths.
const DlrMaxTipScan = 128

proc dlrDonorTooltipData(parent: Il2CppPtr): Il2CppPtr =
  ## A LIVE `SettingsTooltipData`, borrowed from the stock DlssPreset row, so
  ## that `il2cpp_object_new` gets a class pointer that came off an object the
  ## GAME made rather than out of any metadata lookup. Walked, never offset-ed
  ## into from nowhere: container child (matched on the same name the placement
  ## anchor uses) -> its `SettingDropDown` component -> `_tooltipSettingsHover`
  ## @0x98 -> `_tooltipData` @0x20.
  result = nil
  var n = 0
  if not iChildCount(parent, n): return
  if n <= 0 or n > DlrMaxTipScan: return
  var i = 0
  while i < n and i < DlrMaxTipScan:
    let c = iChildAt(parent, i)
    if c != nil and duOk(c, 0x20'i32) and iUnityAlive(c):
      let nm = iObjName(c)
      if nm.len > 0 and modsNameHas(nm, DlrAnchorName):
        let ctrl = modsComponent(c, "SettingDropDown")
        if ctrl != nil:
          let d = nuTooltipDataOf(ctrl)
          if d != nil: return d
        return
    i = i + 1

proc dlrMakeTooltipData(title, body: string; why: var string): Il2CppPtr =
  ## ONE `SettingsTooltipData` TEMPLATE for a DLSS row.
  ##
  ## The body of this proc MOVED to `nativeui.nim` as `nuMakeTooltipData` on
  ## 2026-09-04, unchanged, so that `postfxrows.nim` gets this exact mechanism
  ## rather than a second copy of it that could drift. The two row files are
  ## `include`d in the order postfx-then-dlss and cannot see each other;
  ## nativeui is `include`d before both. Nothing about the DLSS behaviour
  ## changes: the same donor klass, the same `frAdmit` gate, the same six
  ## typed stores, the same named refusals.
  nuMakeTooltipData(gDlrTipKlass, "dlssrows.tooltip", title, body, why)

proc dlrApplyTooltips(parent: Il2CppPtr) =
  ## Attach a tooltip to every row of ours that declares one, then VERIFY by
  ## reading the finished state back. Runs ONCE per build; nothing here is on a
  ## per-frame path and nothing here allocates after it has run.
  if not gDlrTipsOn or gDlrRowCtrl.len == 0: return
  gDlrTipKlass = nil
  let donor = dlrDonorTooltipData(parent)
  if donor == nil:
    gDlrTipWhy = "no live SettingsTooltipData could be borrowed from the " &
                 "stock '" & DlrAnchorName & "' row (no child of the row " &
                 "container carries that name, it has no SettingDropDown " &
                 "component, or its _tooltipSettingsHover@0x98 / " &
                 "_tooltipData@0x20 read null). Without a donor there is no " &
                 "class pointer to allocate against, and none is invented"
    return
  gDlrTipKlass = nuKlassOf(donor)
  if gDlrTipKlass == nil:
    gDlrTipWhy = "the donor SettingsTooltipData's object header did not read " &
                 "back a class pointer"
    return
  var i = 0
  while i < gDlrRowCtrl.len and i < DlrMaxRows:
    if gDlrRowTip[i].len > 0 and gDlrRowCtrl[i] != nil:
      gDlrTipAsked = gDlrTipAsked + 1
      var wb = ""
      var wd = ""
      let body = nuStrWhy(gDlrRowTip[i], wb)
      let data = dlrMakeTooltipData(gDlrRowKey[i], gDlrRowTip[i], wd)
      if data != nil and body != nil:
        gDlrTipWant[i] = body
        if nuSetTooltip(gDlrRowCtrl[i], data):
          gDlrTipCalled = gDlrTipCalled + 1
        else:
          warn "dlss rows: tooltip '" & gDlrRowKey[i] & "' -- the template " &
               "was BUILT and SetTooltip was refused before it was made (the " &
               "control did not validate, or the @0x16FAC00 prologue did not " &
               "verify). Nothing was called for this row."
      else:
        # ONE LINE PER FAILING ROW, naming the row AND the cause. The previous
        # version recorded only the FIRST failure into a shared string, so four
        # rows failing for one reason read as one row failing for another.
        warn "dlss rows: tooltip '" & gDlrRowKey[i] & "' NOT applied -- " &
             (if data == nil: wd else: "the body string: " & wb) & "."
        if gDlrTipWhy.len == 0:
          gDlrTipWhy = "first failure was '" & gDlrRowKey[i] & "': " &
                       (if data == nil: wd else: wb)
    i = i + 1
  # THE VERDICT, and it is a property of the FINISHED STATE: the tooltip the
  # control now carries must be the string we handed over. Reading back what we
  # wrote into our own template would be a check that cannot fail; this reads
  # the object the GAME constructed, through the control.
  #
  # A row that WAS called and does not read back is the case the coordinator
  # suspected on 2026-09-04 -- a prefab whose `_blocker@0x88` or
  # `_tooltipSettingsHover@0x98` is null, which makes SetTooltip a silent
  # no-op. That hypothesis is neither assumed nor dismissed here: both fields
  # are read and NAMED, so the next run says outright whether a hover area has
  # to be cloned from the stock row or whether the write simply did not land.
  var i2 = 0
  while i2 < gDlrRowCtrl.len and i2 < DlrMaxRows:
    if gDlrTipWant[i2] != nil:
      if nuTooltipTextOf(gDlrRowCtrl[i2]) == gDlrTipWant[i2]:
        gDlrTipVerified = gDlrTipVerified + 1
      else:
        let hov = (if nuOk(gDlrRowCtrl[i2], DlrOffScTooltipHover + 8'i32):
                     cNuGetRef(gDlrRowCtrl[i2], DlrOffScTooltipHover) else: nil)
        let blk = (if nuOk(gDlrRowCtrl[i2], DlrOffScBlocker + 8'i32):
                     cNuGetRef(gDlrRowCtrl[i2], DlrOffScBlocker) else: nil)
        warn "dlss rows: tooltip '" & gDlrRowKey[i2] & "' -- SetTooltip was " &
             "CALLED and the finished state does NOT carry our string. On " &
             "this row _tooltipSettingsHover@0x98 = " &
             (if hov == nil: "NULL" else: "0x" & hexOf(cast[uint64](hov))) &
             " and _blocker@0x88 = " &
             (if blk == nil: "NULL" else: "0x" & hexOf(cast[uint64](blk))) &
             ". A NULL blocker is SetTooltip's FIRST no-op path and means " &
             "this prefab needs a SettingsHoverTooltipArea cloned from the " &
             "stock '" & DlrAnchorName & "' row before any tooltip can " &
             "attach; a non-null blocker with a null hover area means " &
             "TryGetTooltip answered false. Either way this row shows NO " &
             "tooltip and is not counted as a pass."
    i2 = i2 + 1

## ---------------------------------------------------------------------------
## THE DROPDOWN LABEL -- what "Blank item" actually was
##
## OBSERVED on the deployed build 61238a816f58 (the player, looking at the
## Graphics page): the two DLSS choice rows read "Blank item". OBSERVED in the
## host log for the same boot: "DROPDOWNS -- 2 of 2 ... filled by CALLING the
## game's own Show" and "5 of 5 show the player's CONFIG value". Both log lines
## were true and neither was about the label.
##
## MEASURED, and this is the whole diagnosis: `set_CurrentIndex` @0x698560 is
## `mov [rcx+0xE8], edx ; ret` (`disasm 0x698560`). It stores the index and
## refreshes nothing. The game itself never calls it alone -- `UpdateValue`
## @0x16AEAC0 writes the same field and then tail-dispatches through
## `[klass+0x308]/[klass+0x310]` with `_values[i]`'s string (`disasm 0x16aeac0
## --len 470`, +0x121 onward). `BaseDropDownBox::SetLabelText` @0x16AEE60 is
## seventeen bytes performing exactly that dispatch (`disasm 0x16aee60`). So
## the box was correctly SELECTED and never TOLD to redraw, and "Blank item" is
## the caption the cloned prefab was authored with.
##
## THE INDEX IS READ BACK FROM THE CONTROL, NOT REMEMBERED. Which choice a row
## ends on is decided inside `sbdRegisterDropdown` from the player's config,
## clamped to the choice count, and this file does not see that number. Asking
## `get_CurrentIndex` @0x698550 -- a DIFFERENT function from the one that
## wrote it -- is both the only way to know and the only way this stays correct
## if the seed changes.
##
## THE VERDICT IS THE TMP, NOT THE CALL. `nuDropDownSetLabel` returning true
## means a call was made. What the player reads is
## `DropDownBox._currentValueText@0xf0`, which the game's own `SetTextInternal`
## writes (`disasm 0x16b0c40`), so reading THAT back and comparing it to the
## caption is a property of the finished state. Its being null is a THIRD
## outcome -- a `DropDownBoxNewStyle` has no such field -- and is counted apart.
proc dlrApplyDropdownLabels() =
  ## Refresh the visible caption of every dropdown row we built, then judge by
  ## reading the label TMP. Runs ONCE per build, off any per-frame path, and
  ## allocates only the interned caption strings, which the intern table holds
  ## for the session.
  if gDlrRowDdb.len == 0: return
  var i = 0
  while i < gDlrRowDdb.len and i < DlrMaxRows:
    let ddb = gDlrRowDdb[i]
    if ddb == nil:
      i = i + 1
      continue
    gDlrLblAsked = gDlrLblAsked + 1
    let (readable, idx) = nuDropDownIndex(ddb)
    if not readable:
      gDlrLblInconclusive = gDlrLblInconclusive + 1
      if gDlrLblWhy.len == 0:
        gDlrLblWhy = "'" & gDlrRowKey[i] & "': get_CurrentIndex @0x698550 " &
                     "did not answer, so there is no chosen value to name " &
                     "and NOTHING was written to the label"
      i = i + 1
      continue
    let choices = gDlrRowChoices[i]
    if idx < 0'i32 or int(idx) >= choices.len:
      gDlrLblInconclusive = gDlrLblInconclusive + 1
      if gDlrLblWhy.len == 0:
        gDlrLblWhy = "'" & gDlrRowKey[i] & "': the box reports index " & $idx &
                     " and this row declares " & $choices.len & " choice(s), " &
                     "so the caption for that index is not knowable here. " &
                     "NOTHING was written -- inventing a string would put a " &
                     "caption on screen that names no real value"
      i = i + 1
      continue
    let want = choices[int(idx)]
    var w = ""
    if not nuDropDownSetLabel(ddb, want, w):
      if gDlrLblWhy.len == 0:
        gDlrLblWhy = "'" & gDlrRowKey[i] & "': " & w
      i = i + 1
      continue
    gDlrLblCalled = gDlrLblCalled + 1
    # THE READBACK. A different object from anything written above: the TMP the
    # game's own SetTextInternal drives.
    let tmp = nuDropDownLabelTmp(ddb)
    if tmp == nil:
      gDlrLblInconclusive = gDlrLblInconclusive + 1
      if gDlrLblWhy.len == 0:
        gDlrLblWhy = "'" & gDlrRowKey[i] & "': SetLabelText was CALLED and " &
                     "_currentValueText@0xf0 read null, so the label could " &
                     "not be examined. That field is declared by DropDownBox " &
                     "and not by DropDownBoxNewStyle, so this is most likely " &
                     "'this clone is a NewStyle box', which is INCONCLUSIVE " &
                     "and not a failure"
      i = i + 1
      continue
    let got = nuGetText(tmp)
    if got == want:
      gDlrLblVerified = gDlrLblVerified + 1
    else:
      warn "dlss rows: LABEL '" & gDlrRowKey[i] & "' -- SetLabelText " &
           "@0x16AEE60 was called with '" & want & "' (index " & $idx &
           ") and the box's own _currentValueText@0xf0 now reads '" & got &
           "'. The player sees that second string, not the first."
      if gDlrLblWhy.len == 0:
        gDlrLblWhy = "'" & gDlrRowKey[i] & "': the label reads '" & got &
                     "' after the call, not '" & want & "'"
    i = i + 1

proc dlrBuild(): bool =
  ## Build the five rows into the live Graphics panel. Called ONCE, from the
  ## tick, only after that panel has actually been observed up.
  result = false
  if gDlrBuilt or gDlrOff or not gDlrOn: return
  inc gDlrTried
  if not nuTargetsBindOk():
    dlrNoteFault("the aowl_nu_targets POSITIONAL self-check FAILED, so every " &
                 "call this file makes would go to the wrong method with the " &
                 "wrong frame. Nothing was built.")
    return
  let tab = dlrTab()
  if tab == nil:
    dlrNoteFault("the GraphicsSettingsTab component could not be reached by " &
                 "walking from the live 'Graphics Settings' panel transform. " &
                 "Without it there is no row parent and no prefab, so nothing " &
                 "was built.")
    return
  let parent = (if nuOk(tab, DlrOffGfxContainer + 8'i32):
                  cNuGetRef(tab, DlrOffGfxContainer) else: nil)
  if not nuOk(parent, 0x10'i32) or not nuAlive(parent):
    dlrNoteFault("GraphicsSettingsTab._settingsContainer @0x98 read null, " &
                 "unreadable or not a live Unity object. That field is " &
                 "serialized and is populated when the prefab loads, so this " &
                 "is 'asked too early' rather than a wrong offset. Nothing " &
                 "was built and nothing was parented anywhere.")
    return
  let togPrefab = (if nuOk(tab, DlrOffToggleTmpl + 8'i32):
                     cNuGetRef(tab, DlrOffToggleTmpl) else: nil)
  # `GraphicsSettingsTab._dropDownTemplate` @0xB0 -- MEASURED
  # (`tools/fldoff.py field EFT.UI.Settings.GraphicsSettingsTab
  # _dropDownTemplate`), and NULL-CAPABLE like every other serialized template
  # here. Fetched unconditionally so the census can say "the flag was on and
  # the prefab was missing", which is not the same as "the flag was off".
  let ddPrefab = (if nuOk(tab, DlrOffDropDownTmpl + 8'i32):
                    cNuGetRef(tab, DlrOffDropDownTmpl) else: nil)
  let sliPrefab = (if nuOk(tab, DlrOffFloatSliderTmpl + 8'i32):
                     cNuGetRef(tab, DlrOffFloatSliderTmpl) else: nil)
  if not nuOk(togPrefab, 0x10'i32) and not nuOk(sliPrefab, 0x10'i32):
    dlrNoteFault("NEITHER _toggleTemplate @0xb8 nor " &
                 "_selectFloatSliderTemplate @0xc8 read back as a live " &
                 "object, so there is no prefab to instantiate. Refusing to " &
                 "fall back to building controls from scratch.")
    return
  let rows = dlrCatalogue()
  gDlrRowGo = @[]
  gDlrRowKey = @[]
  gDlrRowT = @[]
  gDlrRowCtrl = @[]
  gDlrRowTip = @[]
  gDlrTipWant = @[]
  var built = 0
  var refused = 0
  var seeded = 0
  var i = 0
  while i < rows.len and i < DlrMaxRows:
    let r = rows[i]
    let prefab = (if r.kind == dlrToggle: togPrefab else: sliPrefab)
    if not nuOk(prefab, 0x10'i32):
      refused = refused + 1
      i = i + 1
      continue
    var sl: Il2CppPtr = nil
    var ct: Il2CppPtr = nil
    var dd: Il2CppPtr = nil
    # THE DROPDOWN IS TRIED FIRST AND FALLS BACK, NEVER THE OTHER WAY. A
    # refusal at any of the six proofs inside `nuDropDownShow` leaves the row
    # as the stepper slider that has been shipping -- a working control, not a
    # missing one -- and the census records that it happened and why.
    var wantDrop = (r.kind == dlrDropdown and gDlrDropOn and
                    nuOk(ddPrefab, 0x10'i32))
    if r.kind == dlrDropdown and gDlrDropOn:
      gDlrDropWanted = gDlrDropWanted + 1
      if not wantDrop and gDlrDropWhy.len == 0:
        gDlrDropWhy = "GraphicsSettingsTab._dropDownTemplate @0xB0 did not " &
                      "read back as a live object, so there is no dropdown " &
                      "prefab to clone"
    var go: Il2CppPtr = nil
    if wantDrop:
      go = dlrMakeRow(ddPrefab, parent, r, true, sl, ct, dd)
      if go == nil:
        wantDrop = false
    if go == nil:
      go = dlrMakeRow(prefab, parent, r, false, sl, ct, dd)
    if go != nil:
      gDlrRowGo.add go
      gDlrRowKey.add r.key
      # The row's TRANSFORM, captured HERE rather than re-found by name later:
      # a second lookup could bind a different object and the placement
      # readback would then be true of something that is not our row.
      gDlrRowT.add nuTransformOf(go)
      gDlrRowCtrl.add ct
      gDlrRowTip.add r.tip
      gDlrTipWant.add nil
      # The DropDownBox this row ended up with (nil for a slider or a toggle,
      # and nil for a choice row that FELL BACK to the stepper), plus the
      # captions it declares. Captured HERE, from the pointers this loop
      # already holds, so the label pass cannot bind a different object.
      gDlrRowDdb.add (if wantDrop: dd else: nil)
      gDlrRowChoices.add r.choices
      built = built + 1
      # THE VALUE BINDING (settingsbind.nim, flag `settingsRowsBind`, default
      # OFF -- with it off both calls do nothing and the row is a real control
      # that changes nothing). The pointers handed over are the ones this loop
      # ALREADY HOLDS; nothing is re-found by name or by index later.
      if wantDrop and dd != nil:
        gDlrDropBuilt = gDlrDropBuilt + 1
        if sbdRegisterDropdown(DlrGuid, r.key, dd,
                               int32(r.choices.len), int32(r.def + 0.5'f32)):
          seeded = seeded + 1
      elif r.kind == dlrToggle:
        if sbdRegisterToggle(DlrGuid, r.key, ct, r.defB):
          seeded = seeded + 1
      elif sl != nil:
        if sbdRegisterSlider(DlrGuid, r.key, sl, r.lo, r.hi, r.def):
          seeded = seeded + 1
    else:
      refused = refused + 1
    i = i + 1
  if built == 0:
    dlrNoteFault("zero rows were built out of " & $rows.len & " declared (" &
                 $refused & " refused). Nothing is left in the Graphics page.")
    discard dlrDestroyAll()
    return
  gDlrBuilt = true
  gDlrBuiltN = built
  gDlrSeeded = seeded
  gDlrRefused = refused
  dlrPlaceRows(parent)
  # AFTER the seed, because the caption must name whichever value the seed
  # chose, and the seed happens inside sbdRegisterDropdown in the loop above.
  dlrApplyDropdownLabels()
  dlrApplyTooltips(parent)
  result = true

proc dlrSeedSourceText(): string =
  ## WHICH SOURCE ANSWERED. Before the disk fallback existed this line asserted
  ## a cause -- "because no /aowlspt/settings/aowl.dlss page had been fetched"
  ## -- which was a guess dressed as a measurement: nothing had asked the file
  ## on disk at all. Now both sources are counted and the line reports them.
  let (page, disk) = sbdSeedSource()
  "Seeds came from: the fetched schema page " & $page & " time(s), the " &
  "DEPLOYED mods/dlss/config.json (modhost.configRead, the same reader the " &
  "backend uses) " & $disk & " time(s). A row counted in neither had no " &
  "value under its key in either source."

proc dlrVerdict() =
  ## ONE line per visit to the page, and it states which values are on screen.
  if gDlrSaid or not gDlrBuilt: return
  gDlrSaid = true
  okLog "dlss rows: " & $gDlrBuiltN & " row(s) built into the stock Graphics " &
        "page (GraphicsSettingsTab._settingsContainer@0x98), " & $gDlrRefused &
        " refused. " & $gDlrSeeded & " of " & $gDlrBuiltN & " show the " &
        "player's CONFIG value; the other " & $(gDlrBuiltN - gDlrSeeded) &
        " show mods/dlss' DECLARED DEFAULT. " & dlrSeedSourceText() &
        " Nothing here applies anything: the " &
        "launcher's dlssapply.py step applies these before the next start " &
        "and prints the PASS/FAIL verdict in the boot log."
  # THE DROPDOWN CENSUS. Silence here would mean "the flag is off" and "the
  # flag is on and every dropdown refused" printed the same, which is the
  # failure shape this repo keeps paying for.
  if gDlrDropOn:
    if gDlrDropBuilt == gDlrDropWanted and gDlrDropWanted > 0:
      okLog "dlss rows: DROPDOWNS -- " & $gDlrDropBuilt & " of " &
            $gDlrDropWanted & " choice row(s) are real EFT.UI.DropDownBox " &
            "controls, cloned from GraphicsSettingsTab._dropDownTemplate@0xB0 " &
            "and filled by CALLING the game's own Show through the receiver's " &
            "own vtable slot 24. Their captions carry no '1 = .. / 2 = ..' " &
            "mapping because the box itself names the choice."
    else:
      warn "dlss rows: DROPDOWNS -- only " & $gDlrDropBuilt & " of " &
           $gDlrDropWanted & " choice row(s) became a dropdown; the rest are " &
           "the stepper SLIDER this file shipped before, which WORKS and is " &
           "not a missing control. Reason: " &
           (if gDlrDropWhy.len > 0: gDlrDropWhy
            else: "none was recorded, which is itself a defect") & "."
    # THE LABEL CENSUS, kept SEPARATE from the dropdown census above. The
    # 2026-09-04 defect was precisely that "the box was built and filled" and
    # "the box displays the right words" were reported by one line, so a box
    # reading "Blank item" was announced as a success.
    if gDlrLblVerified == gDlrLblAsked and gDlrLblAsked > 0:
      okLog "dlss rows: DROPDOWN LABELS -- " & $gDlrLblVerified & " of " &
            $gDlrLblAsked & " box(es) DISPLAY the chosen value: their own " &
            "DropDownBox._currentValueText@0xf0 reads the caption that " &
            "BaseDropDownBox::SetLabelText @0x16AEE60 was given, which is the " &
            "TMP the game's own SetTextInternal writes and not our store read " &
            "back. set_CurrentIndex alone never refreshes this -- MEASURED, " &
            "it is 'mov [rcx+0xE8], edx ; ret'."
    elif gDlrLblAsked > 0:
      warn "dlss rows: DROPDOWN LABELS -- " & $gDlrLblVerified & " of " &
           $gDlrLblAsked & " box(es) read back the chosen caption (" &
           $gDlrLblCalled & " call(s) made, " & $gDlrLblInconclusive &
           " INCONCLUSIVE -- could not be examined at all, which is neither a " &
           "pass nor a fail). A box that does not read back is still showing " &
           "the cloned prefab's authored caption, which is what the player " &
           "reported as 'Blank item'. First reason: " &
           (if gDlrLblWhy.len > 0: gDlrLblWhy
            else: "none was recorded, which is itself a defect") & "."
  if gDlrTipsOn:
    if gDlrTipVerified == gDlrTipAsked and gDlrTipAsked > 0:
      okLog "dlss rows: TOOLTIPS -- " & $gDlrTipVerified & " of " &
            $gDlrTipAsked & " row(s) READ BACK through " &
            "_tooltipSettingsHover@0x98 -> _tooltipData@0x20 -> Text@0x20 as " &
            "the exact string handed to SettingControl::SetTooltip @0x16FAC00. " &
            "That is the object the GAME built from our template, read through " &
            "the control -- not our own write read back."
    else:
      warn "dlss rows: TOOLTIPS -- " & $gDlrTipAsked & " asked, " &
           $gDlrTipCalled & " call(s) made, and only " & $gDlrTipVerified &
           " READ BACK as the string handed over. SetTooltip has three silent " &
           "no-op paths (_blocker@0x88 null, TryGetTooltip false, null data) " &
           "and no throw path, so a call that 'succeeded' proves nothing" &
           (if gDlrTipWhy.len > 0: ". " & gDlrTipWhy else: "") & "."
  if gDlrPlaced >= 0:
    okLog "dlss rows: PLACEMENT -- " & $gDlrPlaced & " of " & $gDlrBuiltN &
          " row(s) READ BACK through Transform::GetSiblingIndex at the index " &
          "they were asked to take, directly after the stock '" &
          DlrAnchorName & "' row. Any shortfall is a row that is still " &
          "wherever Instantiate appended it -- at the bottom of the page -- " &
          "not a row that is missing."
  else:
    warn "dlss rows: PLACEMENT DECLINED -- " &
         (if gDlrPlaceWhy.len > 0: gDlrPlaceWhy
          else: "no reason was recorded, which is itself a defect") &
         ". The rows are BUILT and usable; they sit at the BOTTOM of the " &
         "Graphics page instead of beside the stock DLSS pair. Nothing stock " &
         "was reordered."

## ---------------------------------------------------------------------------
## THE RESTART CONFIRMATION -- the GAME'S OWN modal, not a panel of ours
##
## Every one of these five settings takes effect on the next launch, and the
## game already has exactly the right dialog for that: changing texture quality
## and saving raises "... will be applied after game restart" with an OK
## button. MEASURED `il2cpp_resolve.py disasm 0x1714ea0 --len 520` --
## `GraphicsSettingsTab::ShowTextureQualityChangedMessage()` is
## `LocalizationManager::LocalizedValue(id)` ->
## `ItemUiContext::ShowMessageWindow(...)` @0x1517C00, guarded by
## `_textureMessageShown@0x141`. So the player gets BSG's window, BSG's
## localized text and BSG's OK button, on BSG's own ItemUiContext.
##
## IT FIRES ONLY ON A REAL EDIT. `sbdTakeSaved` is set in `sbdFlush`, which is
## the one place that knows a row was STAGED by the game's own
## `Slider::Set` / `Toggle::Set` event and has now been persisted -- the SAVE
## prefix itself fires on presses that changed nothing, and asking it would
## pop a restart dialog at every SAVE.
##
## WHAT THIS CANNOT ASSERT, and says so: `nuGfxShowRestartMessage` returning
## true means THE CALL WAS MADE. Whether a window appeared depends on
## `_textureMessageShown` (the game latches it once per screen visit) and on
## ItemUiContext being up. Neither is read back here, so the log line claims
## the call and never the window.
proc dlrOnSaved() =
  if not gDlrOn or gDlrOff or not gDlrBuilt: return
  if not sbdTakeSaved(DlrGuid): return
  let tab = dlrTab()
  if tab == nil:
    warn "dlss rows: a DLSS row was changed and SAVED, and the restart " &
         "confirmation was NOT raised -- the GraphicsSettingsTab component " &
         "could not be reached by walking from the live Graphics panel. The " &
         "setting IS written; the player was simply not told it needs a " &
         "restart."
    return
  if nuGfxShowRestartMessage(tab):
    gDlrRestartShown = gDlrRestartShown + 1
    okLog "dlss rows: a DLSS row was changed and SAVED, so the game's own " &
          "restart confirmation was requested (GraphicsSettingsTab::" &
          "ShowTextureQualityChangedMessage @0x1714EA0, call #" &
          $gDlrRestartShown & "). That is the SAME dialog, text and OK " &
          "button the game shows for texture quality. This line means the " &
          "CALL was made; the game suppresses the window if it has already " &
          "shown one this screen visit (_textureMessageShown@0x141), so it " &
          "is not proof a window appeared."
  else:
    warn "dlss rows: a DLSS row was changed and SAVED and the restart " &
         "confirmation call was REFUSED before it was made (the tab pointer " &
         "did not validate, or the ShowTextureQualityChangedMessage prologue " &
         "did not verify). Nothing was called."

proc dlrOnPanelUp(gfxUp: bool) =
  ## Called every tick from `gfxTickBody`, inside its existing guard. The
  ## steady state is two boolean tests.
  if not gDlrOn or gDlrOff: return
  if not gfxUp: return
  if not gDlrBuilt:
    if gDlrTried < 4:
      discard dlrBuild()
    return
  dlrVerdict()
  dlrOnSaved()

proc dlrOnScreenClosed() =
  ## The settings screen went away. Our rows are OURS -- the game's
  ## `CleanupCreatedControls` does not know about them -- so they are torn down
  ## here UNCONDITIONALLY and rebuilt on the next visit. That is what stops the
  ## section appearing twice, then three times, the way an owned row parented
  ## into a re-initialised stock container otherwise does.
  gDlrSaid = false
  if gDlrBuilt or gDlrRowGo.len > 0:
    let n = dlrDestroyAll()
    gDlrTried = 0
    if n > 0:
      okLog "dlss rows: the settings screen closed; " & $n & " row(s) of ours " &
            "were torn down and will be rebuilt on the next visit. Nothing " &
            "stale is left parented into the stock Graphics container."
