void aowlspt_nim_log(void){}
void aowlspt_nim_last_error(void){}
void aowlspt_nim_config_get(void){}
void aowlspt_nim_config_set(void){}
void aowlspt_nim_db_get(void){}
void aowlspt_nim_db_patch(void){}
void aowlspt_nim_route_register(void){}
void aowlspt_nim_event_subscribe(void){}
void aowlspt_nim_event_emit(void){}
void aowlspt_nim_call(void){}
void aowlspt_nim_resolve(void){}
void aowlspt_nim_handle_release(void){}
void aowlspt_nim_patch(void){}
void aowlspt_nim_schedule(void){}
void aowlspt_nim_invoke_main(void){}
void aowlspt_nim_now_ms(void){}
void aowlspt_nim_store_get(void){}
void aowlspt_nim_store_set(void){}
void aowlspt_nim_store_list(void){}
