## Whole item templates REAL BSG serves in `/client/items` that our pre-1.0
## `db.json` does not have at all.
##
## Why this exists
## ---------------
## `emu/itemsgaps` splices the `_props` MEMBERS BSG sends into item ids the
## database already ships -- and deliberately does NOT touch "the 1,154 ids BSG
## serves and we do not have". That omission is a referential hole: a served
## payload (battle-pass rewards, the seasonal event, the ending list, quest
## notes) can REFERENCE one of those absent ids, and when the client tries to
## resolve it against the item table it throws
##
##     Cannot find template with id '<tpl>' for item
##
## and hangs. Measured live 2026-08-28: `6a4fa628b4831242f306e8cd`, a battle-pass
## reward `itemId`, absent from this `db.json`, present in BSG's capture.
##
## What this table IS
## ------------------
## `data/post1/itemsadd.json`, a dict keyed by item id -> the WHOLE template
## object (`_id`,`_name`,`_parent`,`_type`,`_props`,`_proto`), copied VERBATIM
## from BSG's captured `/client/items` (`capture/raid1` seq 045, decoded). It is
## generated by `tools/gen_itemsadd.py`, which enumerates every item template a
## served payload references, subtracts what the database serves, and lifts the
## remainder from the capture. An id a payload references but the capture does
## NOT have is never written -- it is reported so the reference can be stripped
## from its payload, never fabricated (fact: currently zero such).
##
## What is NOT claimed
## -------------------
## That any of these is instantiated, or that their own `_props` filter
## references (grid/slot filters) all resolve. The claim is exactly the one the
## referential-integrity check (`tools/itemrefs.py`) asserts and no wider: every
## item template our served payloads reference now resolves to a served item.
##
## Never overwrites. An id the database already ships always wins, so
## re-importing a newer `db.json` retires this table id by id instead of being
## shadowed by a stale capture -- the same discipline `itemsgaps` follows.

import aowlspt
import aowlspt/server
import aowlspt/json
import post1

var gApplied = false
var gAddedItems = 0
var gCache = ""
var gCacheFor = ""

proc itemsAddCount*(): int = gAddedItems
proc itemsAddApplied*(): bool = gApplied

proc mergeInto(itemsText: string): string =
  let table = post1Table("itemsadd")
  if table.len == 0:
    # `post1Table` has already warned. Serving the database document unchanged
    # is the behaviour from before this module existed.
    return itemsText
  var add = parseObject(table)
  if not add.ok:
    warn "items: data/post1/itemsadd.json is not a JSON object; " &
         "the BSG-only whole item templates will NOT be served"
    return itemsText
  var doc = parseObject(itemsText)
  if not doc.ok:
    warn "items: the database document is not a JSON object; " &
         "the BSG-only whole item templates will NOT be served"
    return itemsText
  gAddedItems = 0
  for a in add.fields:
    if doc.has(a.name):
      continue                      # the database ships it already; it wins.
    setRaw(doc, a.name, a.value)
    inc gAddedItems
  gApplied = true
  if gAddedItems == 0:
    return itemsText
  result = text(doc)

proc applyItemsAdd*(itemsText: string): string =
  ## The item-template document with BSG's whole absent templates spliced in.
  ## Cached against the input text: the document is ~12.7 MB and is reparsed
  ## once, not once per request.
  if gCacheFor.len > 0 and gCacheFor == itemsText:
    return gCache
  let merged = mergeInto(itemsText)
  gCacheFor = itemsText
  gCache = merged
  result = merged

proc selfCheckItemsAdd*(into: var seq[string]): bool =
  ## Negative assertions about the FINISHED document (CLAUDE.md 9b). None
  ## re-reads this module's own write by comparing it to what it wrote.
  result = true
  let table = post1Table("itemsadd")
  if table.len == 0:
    into.add "items add: data/post1/itemsadd.json is not installed"
    return false
  let add = parseObject(table)
  if not add.ok or add.fields.len == 0:
    into.add "items add: itemsadd.json did not parse as a non-empty JSON object"
    return false

  # Every entry must itself be a valid JSON OBJECT carrying `_id` and `_props`
  # -- a whole template, not a fragment. Fact #122: "contains" is not "parses".
  var bad = 0
  for a in add.fields:
    let v = whole(a.value)
    if not v.exists or not v.isObject or not v.child("_id").exists or
       not v.child("_props").exists:
      inc bad
  if bad > 0:
    into.add $bad & " entr(ies) of itemsadd.json are not whole item templates"
    result = false

  # NEGATIVE, end to end, on a MINIATURE document that does NOT contain the
  # table's first id: after the merge that id is PRESENT, and the pre-existing
  # sibling survives. A stub returning its input unchanged fails the first; one
  # that rebuilt the doc from the add table alone fails the second.
  block:
    let id = add.fields[0].name
    let src = "{\"zzz\":{\"_id\":\"zzz\",\"_props\":{}}}"
    let saveCacheFor = gCacheFor
    let saveCache = gCache
    gCacheFor = ""
    let outText = applyItemsAdd(src)
    gCacheFor = saveCacheFor
    gCache = saveCache
    if not field(outText, id).exists:
      into.add "items add: the merged document is missing the id it was " &
               "supposed to add"
      result = false
    elif not field(outText, id).child("_props").exists:
      into.add "items add: the added item has no `_props` after the merge"
      result = false
    if not field(outText, "zzz").exists:
      into.add "items add: the merge dropped a sibling item"
      result = false

  # Never overwrite: an id the database already carries keeps its OWN value.
  block:
    let id = add.fields[0].name
    let src = "{\"" & id & "\":{\"_id\":\"" & id & "\",\"_props\":{\"MINE\":1}}}"
    let saveCacheFor = gCacheFor
    let saveCache = gCache
    gCacheFor = ""
    let outText = applyItemsAdd(src)
    gCacheFor = saveCacheFor
    gCache = saveCache
    if not field(outText, id).child("_props").child("MINE").exists:
      into.add "items add: the merge overwrote an id the database already had"
      result = false
