## The falsifiable half of `emu/planting`.
##
## It is a module of its own for the same reason `emu/mailcheck` is: the check
## needs `loot`, `bots` AND `planting`, and `planting` is imported by the first
## two, so it cannot live in any of them without a cycle.
##
## Every assertion here is over the **finished served payload**, never over the
## write that produced it. The one that matters most is the NEGATIVE control:
## with no planter subscribed, the payload for a given map and raid id must be
## byte-identical to the payload the same generation produced before the hook
## existed. That is asserted by generating the same raid twice -- once with the
## test planter refusing to answer that raid id, once after a planter has
## answered a DIFFERENT one -- and comparing the bytes. If planting could leak
## into an unanswered raid, this goes red.
##
## The test planter stays subscribed for the life of the process. It answers
## **only** the four raid ids below, which no real raid can mint (a real raid id
## is a 24-character mongo id), so it cannot plant anything into a real game.

import aowlspt
import aowlspt/server
import aowlspt/json
import planting
import lootconfig
import loot
import bots

const
  RaidPlant = "selfcheck-plant-raid"
  RaidNoPlant = "selfcheck-noplant-raid"
  RaidBadTpl = "selfcheck-badtpl-raid"
  RaidBots = "selfcheck-bots-raid"

  GoodTpl = "aaaaammo0000000000000001"
    ## In `loot.Fixture`'s `templates.items`.
  BadTpl = "nosuchtemplate0000000bad"
    ## Deliberately absent from it.

  PlantedId = "p1antedaaaaaaaaaaaaaaa01"
  PlantedBadId = "p1antedaaaaaaaaaaaaaaa02"

  NameA = "SelfcheckPlantedAlpha"
  NameB = "SelfcheckPlantedBravo"

var gTestPlanterOn = false

proc contains(haystack, needle: string): bool =
  if needle.len == 0 or needle.len > haystack.len:
    return false
  var i = 0
  while i <= haystack.len - needle.len:
    var k = 0
    while k < needle.len and haystack[i + k] == needle[k]:
      k = k + 1
    if k == needle.len:
      return true
    i = i + 1
  result = false

proc itemDoc(id, tpl: string; count: int; x, y, z: float): string =
  var d = newDoc()
  setText(d, "id", id)
  setText(d, "tpl", tpl)
  setNumber(d, "count", count)
  setNumber(d, "x", x)
  setNumber(d, "y", y)
  setNumber(d, "z", z)
  setText(d, "cacheId", "selfcheck-cache")
  result = text(d)

proc testLootPlanter(payload: string): string =
  ## A planter, exactly as `mods/basement` will be one: it reads the compose
  ## and emits the plant from inside the handler.
  result = ""
  if not gTestPlanterOn:
    return
  let rid = field(payload, "raidId").asText("")
  var items = newList()
  if rid == RaidPlant:
    items.add itemDoc(PlantedId, GoodTpl, 7, 11.5, 12.5, 13.5)
  elif rid == RaidBadTpl:
    items.add itemDoc(PlantedId, GoodTpl, 1, 1.0, 2.0, 3.0)
    items.add itemDoc(PlantedBadId, BadTpl, 1, 4.0, 5.0, 6.0)
  else:
    # RaidNoPlant and every real raid: answer nothing at all. This branch is
    # what makes the negative control a control.
    return
  var d = newDoc()
  setText(d, "raidId", rid)
  setRaw(d, "items", text(items))
  # NOT `broadcast`: the host does not deliver an emit back into the
  # emitting mod (see the seam note in `emu/planting`), so a self-check
  # planter must hand the plant to the same entry point the subscriber is.
  discard deliverLootPlant(text(d))

proc testBotPlanter(payload: string): string =
  result = ""
  if not gTestPlanterOn:
    return
  let rid = field(payload, "raidId").asText("")
  if rid != RaidBots:
    return
  var names = newList()
  names.add quoted(NameA)
  names.add quoted(NameB)
  var g = newDoc()
  setText(g, "groupId", "selfcheck-group-1")
  setText(g, "factionId", "selfcheck-faction-1")
  setText(g, "role", "assault")
  setNumber(g, "count", 2)
  setRaw(g, "names", text(names))
  var groups = newList()
  groups.add text(g)
  var d = newDoc()
  setText(d, "raidId", rid)
  setRaw(d, "groups", text(groups))
  discard deliverBotsPlant(text(d))

proc fail(into: var seq[string]; ok: bool; what: string) =
  if not ok:
    into.add "planting: FAIL " & what

proc selfCheckPlanting*(into: var seq[string]) =
  ## Appends one line per assertion that did NOT hold. Empty is the pass.
  if not installPlanting():
    into.add "planting: FAIL the plant subscribers could not be installed (" &
             lastError() & ")"
    return
  setLocalPlanters(testLootPlanter, testBotPlanter)

  let d = textDb(loot.Fixture)
  let cfg = defaultLootConfig()

  # Baselines taken with the planter DORMANT: this is the "before the hook
  # existed" payload, generated by the very same code path.
  gTestPlanterOn = false
  let basePlant = generateLoot(d, cfg, "testmap", RaidPlant)
  let baseNoPlant = generateLoot(d, cfg, "testmap", RaidNoPlant)
  let baseBad = generateLoot(d, cfg, "testmap", RaidBadTpl)

  gTestPlanterOn = true
  let withPlant = generateLoot(d, cfg, "testmap", RaidPlant)
  let withNoPlant = generateLoot(d, cfg, "testmap", RaidNoPlant)
  let withBad = generateLoot(d, cfg, "testmap", RaidBadTpl)

  # (a) the planted item is SERVED, at the planted position, with the planted
  #     template and count. Read off the finished array, not off the plant.
  var found = false
  var posOk = false
  var tplOk = false
  var countOk = false
  let entries = parseArray(withPlant)
  if entries.ok:
    for i in 0 ..< entries.len:
      let e = whole(entries.items[i])
      if e.field("Root").asText("") != PlantedId:
        continue
      found = true
      posOk = e.field("Position.x").asFloat(0.0) == 11.5 and
              e.field("Position.y").asFloat(0.0) == 12.5 and
              e.field("Position.z").asFloat(0.0) == 13.5
      let it = e.field("Items").at(0)
      tplOk = it.field("_tpl").asText("") == GoodTpl and
              it.field("_id").asText("") == PlantedId
      countOk = it.field("upd.StackObjectsCount").asInt(0) == 7
  fail(into, found, "the planted item is in the served Loot array")
  fail(into, posOk, "the planted item is at the position it was planted at")
  fail(into, tplOk, "the planted item carries the planted tpl and id")
  fail(into, countOk, "the planted count arrives as upd.StackObjectsCount")
  fail(into, withPlant != basePlant,
       "planting CHANGED the payload (if this passes vacuously nothing above " &
       "is a measurement)")

  # (b) the negative control. No planter answered this raid id, so the payload
  #     must be byte-identical to the one generated before any planter existed.
  fail(into, withNoPlant == baseNoPlant,
       "a raid no planter answered is byte-identical to the pre-hook payload")
  fail(into, not contains(withNoPlant, PlantedId),
       "no planted id leaks into a raid the planter did not answer")

  # (c) an unknown tpl is refused, and the GOOD item beside it still lands --
  #     a refusal that dropped the whole plant would pass a bare "absent" check.
  fail(into, not contains(withBad, BadTpl),
       "an unknown tpl is refused and never reaches the served payload")
  fail(into, not contains(withBad, PlantedBadId),
       "the refused item's id is not served either")
  fail(into, contains(withBad, PlantedId),
       "the valid item beside a refused one still lands")
  fail(into, withBad != baseBad,
       "the bad-tpl run still differs from its baseline (positive control)")

  # (d) bots: two named profiles, and exactly two.
  setRaidContext("testmap", RaidBots)
  var generated = 0
  let batch = bots.generate("{\"conditions\":[]}", generated)
  gTestPlanterOn = false
  fail(into, generated == 2,
       "a bots.plant of 2 adds exactly 2 profiles (got " & $generated & ")")
  fail(into, contains(batch, NameA) and contains(batch, NameB),
       "both planted nicknames appear in the served bot batch")
  # And the negative: an unanswered raid adds nothing.
  setRaidContext("testmap", "selfcheck-bots-none")
  var none = 0
  discard bots.generate("{\"conditions\":[]}", none)
  fail(into, none == 0,
       "with no planter answering, an empty bot request stays empty (got " &
       $none & ")")
  clearLocalPlanters()
