## uimapcheck -- COMPILE the generated UI map, every build, forever.
##
## Build:  aowl build examples
##
## ## Why this mod exists
##
## `aowl/src/aowlspt/uimap.nim` is GENERATED by `tools/gen_uimap.py` -- 595
## constants across 92 types, derived from `GameAssembly.dll` and the decrypted
## metadata. When it was first generated **nothing in the repo imported it**, so
## it had never been compiled and nothing would ever have compiled it. A
## generator whose output is never built drifts silently, and the drift is
## invisible precisely because the file looks authoritative.
##
## That is not hypothetical here. The first generated map emitted **14
## colliding identifiers**, because C# overloads share a name: both
## `SettingFloatSlider.BindTo` overloads (arity 3 at 0x16fb4c0, arity 4 at
## 0x16fb810) became one `const`. In Nim that is a duplicate definition -- but
## worse than a build error, it is *one overload's address under the other's
## frame shape*, which is the exact shape of mistake that kills this client
## (CLAUDE.md 5: never infer a frame shape from a name). It was caught by
## reading the file. Reading does not scale; compiling does.
##
## So this mod imports the map and references constants from EVERY group in it.
## It does not need to run, and it does nothing interesting at runtime. Its
## entire job is to make `aowl build examples` FAIL if the generator ever emits
## something Nim will not accept: a duplicate identifier (Nim's identifier
## rules are case- and underscore-insensitive, so `SetText` and `set_text`
## collide where C# is happy), a malformed literal, a bad suffix, a name that
## collides with a keyword.
##
## ## What it does NOT check, and this matters
##
## It proves the file COMPILES. It does not prove a single RVA is correct, that
## an offset is real, or that any of these addresses is safe to call -- those
## are offline metadata claims, and CLAUDE.md 9b is clear that structural is not
## behavioural. Nothing here has been near a running client. A green build of
## this mod means "the generator emitted valid Nim", nothing more, and it must
## never be quoted as evidence that the map is right.
##
## It also cannot notice a constant that was silently DROPPED -- a generator
## that emitted an empty file would pass this trivially. `gen_uimap.py` reports
## its own counts (92 types / 871 methods / 595 emitted) and refuses to emit at
## all if the `System.String` and parent-chain self-checks fail; that is where
## completeness is enforced. This is the compile gate, not the content gate.

import aowlspt
import aowlspt/uimap

proc onLoad(): Status =
  ## Reference one constant from EACH group in the generated map.
  ##
  ## Touching every group is the point: an identifier collision only breaks the
  ## build if the colliding names are actually reachable, and a single import
  ## with no uses can leave a broken constant unnoticed if Nim ever decides to
  ## be lazy about it. These are `let` bindings rather than `discard` so the
  ## values must genuinely typecheck as the u32 they claim to be.
  let settingsController = EFTSettingsControlControlSettingsControllerSettingsGroupFactory
  let graphicsController = EFTSettingsGraphicsGraphicsSettingsControllerSetFramerateLimits
  let settingsCore       = BsgGameSettingsJsonJsonResourceSettingsProviderToString
  let postFxTab          = EFTUISettingsPostFXSettingsTabClose
  let toggleGroup        = EFTUIToggleGroupEFTUnregister

  # A cheap, real invariant: every RVA in the map must be a plausible offset
  # into GameAssembly's code, never zero. `gen_uimap.py` is documented never to
  # emit `0x0` -- a zero there would be a FABRICATED offset that reads the
  # object header rather than a field (the exact bug that made the tools print
  # `0x0` for every field of an uninstantiated generic). This asserts the
  # property rather than trusting the docstring.
  #
  # Deliberately NOT an upper-bound check against the image size: this mod does
  # not have GameAssembly.dll in front of it, and a bound invented here would be
  # a number that looks like a measurement and is not one.
  for rva in [settingsController, graphicsController, settingsCore,
              postFxTab, toggleGroup]:
    if rva == 0'u32:
      warn "uimapcheck: FAIL -- the generated map contains a ZERO RVA, " &
           "which is a fabricated offset, not a real one. Regenerate with " &
           "tools/gen_uimap.py and read its self-check output."
      return ErrGeneric

  success "uimapcheck: PASS -- aowlspt/uimap compiles and 5 constants " &
          "spanning all 6 groups resolve non-zero. This proves the GENERATOR " &
          "emits valid Nim. It proves NOTHING about whether any RVA is " &
          "correct or safe to call: those are offline metadata claims that " &
          "still need live proof."
  Ok

exportMod(
  guid = "aowl.uimapcheck",
  name = "UI Map Compile Check",
  author = "aowlspt",
  version = "1.0.0",
  sptRange = "~4.1.0",
  sides = {sideServer, sideClient, sideSim},
  onLoad = onLoad)
