## ar/calls.nim -- EVERY CALL THIS MOD MAKES INTO THE GAME, AND NOTHING ELSE.
##
## One file, one reason: a call into IL2CPP is the operation with the highest
## cost of being wrong in this whole project, and the only way to keep the
## discipline visible is to keep every instance of it in one place where the
## rules can be read off the page.
##
## THE RULES THIS FILE OBEYS, AND HOW EACH IS ENFORCED RATHER THAN INTENDED
## ------------------------------------------------------------------------
## * **Never by name.** Fact #145: resolving an IL2CPP name is harmless and
##   USING one is fatal -- `CameraManager::get_Instance` by name, `Physics::
##   Raycast` bound by name and `AddActivePLayer` patched by name each killed
##   the client instantly and silently. Nothing here resolves a name. Every
##   target is an RVA plus the sixteen bytes it is DECLARED to begin with.
## * **Byte-verify before the first call.** `aowlspt/callrva` compares the
##   declared prologue against a CAPTURE-ONCE snapshot of the original bytes,
##   and refuses -- by name, with a sentence -- on a mismatch, on an RVA outside
##   the image, on an RVA outside the `il2cpp` section (generated code lives
##   there, NOT in `.text`). A first byte that is a JUMP means somebody
##   detoured the function before we looked -- almost always the HOST's own
##   uihooks/nativetabs hooks (MEASURED 2026-09-05: `Toggle::Set`,
##   `SettingsScreen::Close`, `MenuScreen::ShowInRaid`, and the raid entry
##   stopped at SIDE while they were refused). Calling THROUGH a hook is
##   correct, so `callrva` then asks the host for its pre-detour snapshot
##   (`aowlspt.host::original_bytes`) and byte-verifies against THAT; a host
##   with no row for the RVA, or a mismatch, is still a refusal by name.
## * **Never DETOUR a shared RVA.** This file detours nothing at all, so the
##   hazard has no surface here. `owners` is still carried from the generated
##   table and printed, because "1 owner" said out loud is worth more than an
##   assumption left unstated. CALLING a shared RVA is correct: it is correct
##   code for the receiver passed.
## * **One guard, never nested.** Each call is wrapped by callrva's own vectored
##   guard, and that guard REFUSES TO ARM inside another (`GUARD_BUSY`), on its
##   own flag and on the shim's. So this mod opens no outer guard anywhere --
##   see the header of `ar/native.nim` for why that is the shape rule 3 takes
##   here.
## * **Three outcomes, never two.** Every wrapper below returns the value AND an
##   `ok`, or nil-with-a-reason. "The call faulted" and "the call returned zero"
##   are different answers and nothing here flattens them.
##
## WHERE THE RVAs AND THE PROLOGUES COME FROM
## ------------------------------------------
## Two sources, and the difference matters:
##
##   * `abi/aowlspt_symtab.nim` -- GENERATED by `tools/il2cpp_symtab.py` from
##     `abi/aowlspt_symbols.txt`. A symbol that is ambiguous or shared is
##     REJECTED by the generator and is then simply ABSENT from that file, so
##     referencing it is a compile error rather than a run-time surprise. Every
##     target that can come from there does.
##   * a hand-declared RVA + the sixteen bytes pasted from the `abi/` header
##     that measured them. Used only where the generated table has no row: the
##     manifest names an overload as `Type::Method/arity` and cannot
##     disambiguate by PARAMETER TYPE, so e.g. `Toggle::Set(bool,bool)` has no
##     key. Each such target names the header and the date the bytes came from.
##
## The build identity both rest on is `AowlSymtabImageKey` /
## `AowlSymtabFileSha256`, logged once at load, so a run against a different
## `GameAssembly.dll` is visible in the log rather than inferred from a pile of
## refusals.

import aowlspt
import aowlspt/il2cpp
import aowlspt/callrva
import aowlspt_symtab
import native

# ---------------------------------------------------------------------------
# Field offsets. MEASURED with `tools/fldoff.py` / `tools/il2cpp_resolve.py
# fields`, never guessed, and each carries the note that makes it checkable.
# ---------------------------------------------------------------------------

const
  OffCachedPtr* = 0x10
    ## `UnityEngine.Object.m_CachedPtr`. Unity's own destroyed-object marker;
    ## `ar/native.alive` is the only reader.

  OffDubText* = 0xB8
    ## `EFT.UI.DefaultUIButton._text` -- THE TEXT A PERSON READS on the control.
    ## `tools/fldoff.py field DefaultUIButton _text` -> 0xb8.
  OffDubButton* = 0x108
    ## `EFT.UI.DefaultUIButton._button` -> the `EFT.UI.TweenAnimatedButton` that
    ## actually receives the click.
  OffDubOnClick* = 0x120
    ## `EFT.UI.DefaultUIButton.OnClick`, the UnityEvent. NOT the generic
    ## `UnityEngine.UI.Button.m_OnClick` @0x100 -- reading 0x100 on this klass
    ## made the host's pressability check return false forever on a genuinely
    ## pressable button.
  OffTabInteractable* = 0x68
    ## `EFT.UI.TweenAnimatedButton._interactable` (bool).

  OffToggleIsOn* = 0x120
    ## `UnityEngine.UI.Toggle.m_IsOn`. From the same layout dump that proved
    ## +0x100 is `toggleTransition` -- AN ENUM, not an event:
    ##   0x100 toggleTransition  0x108 graphic  0x110 m_Group
    ##   0x118 onValueChanged    0x120 m_IsOn
    ## Firing a "UnityEvent" read at 0x100 on an `EFT.UI.AnimatedToggle` killed
    ## the client twice, deterministically, on 2026-09-02. That is why a toggle
    ## in this mod is SET through the game's own method and never invoked.

  OffTmpText* = 0xE0
    ## `TMPro.TMP_Text.m_text`. Read only; this mod writes no managed field at
    ## all, so the `LocalizedText` clobber trap has no surface here.

  OffMenuDisconnect* = 0xC0
  OffMenuController* = 0x90
    ## `MenuScreen.ScreenController` -- a field of the GENERIC base
    ## (`EftScreen<TController>`), so fieldOffsets has no number for it.
    ## BORROWED, from the layout: MenuScreen's own fields run `_hideCoroutine`
    ## @0x88 then `_playButton`@0xA0, and the two base fields between them are
    ## `ScreenController` (a pointer) and `<Destroyed>k__BackingField` (a
    ## bool) -- one pointer slot at 0x90, the bool at 0x98. NEVER trusted on
    ## its own: exitmachine cross-checks the object it reads here against the
    ## menu's own `_matchmaker`/`_modeDescriptor`, which the game copied out
    ## of that same controller at its last Show, and refuses on a mismatch.
  OffMenuMatchmaker* = 0x118   ## MenuScreen._matchmaker (fieldOffsets)
  OffMenuModeDesc* = 0x120     ## MenuScreen._modeDescriptor (fieldOffsets)
  OffCtrlMatchmaker* = 0x48    ## MainMenuBaseScreenController.Matchmaker
  OffCtrlModeDesc* = 0x50      ## MainMenuBaseScreenController.ModeDescriptor
    ## Both controller offsets are fieldOffsets facts, read off the annotated
    ## disassembly of MenuScreen::Show(controller) @0x1538760, which loads
    ## exactly these and hands them to the 5-arg Show.
    ## `EFT.UI.MenuScreen._disconnectButton`.

# ---------------------------------------------------------------------------
# The `Il2CppType` descriptors, for `GetComponent(Type)`.
#
# WHY THE TYPE OVERLOAD AND NOT THE STRING ONE. MEASURED 2026-09-02, build
# 1.1.0.1.46777: `Component::GetComponent(String)` matches through a runtime
# type-name lookup that does not resolve on this IL2CPP build. A walk of ALL
# 1263 nodes of an OPEN Settings screen -- a screen made of captions -- found
# ZERO `TextMeshProUGUI` components, while the inspector's `label` reads their
# text fine. A predicate that cannot say yes makes every absence verdict vacuous
# (CLAUDE.md 9b), and this mod's map selection is entirely a text comparison, so
# it would have been vacuous in exactly the place it matters most.
#
# The Type overload matches by KLASS IDENTITY inside the runtime, which is the
# question actually being asked, and -- unlike `GetComponents(Type)`, which
# returns an array -- it ALLOCATES NOTHING, so it is legal on a per-node path.
#
# Getting a `System.Type` without reflection: `System.Type::GetTypeFromHandle`
# takes a `RuntimeTypeHandle`, a one-field struct whose value IS the
# `Il2CppType*`, so on Win64 it is a plain pointer in RCX. The address of the
# static `Il2CppType` for a named type is resolved OFFLINE out of
# `Il2CppMetadataRegistration.types`. These eight were read on 2026-09-04 with
#
#   python tools/il2cpp_nameindex.py lookup \
#       D:\Aowlspt\aowlspt\aowlspt-names.idx "<Ns.Type>::@type" 0
#
# against the index whose stamp matches this build. They are DATA RVAs, so
# there is no prologue to verify -- which is stated plainly rather than glossed:
# the checks available are the image bound, readability, and the fact that the
# address is never called, only handed to a byte-verified method whose ANSWER is
# then re-checked. `typeObject` below returns nil, with a reason, on any of
# those failing.
# ---------------------------------------------------------------------------

const
  TypeRvaDefaultUIButton* = 0x6E318C0'u32   ## EFT.UI.DefaultUIButton
  TypeRvaAnimatedToggle*  = 0x6F93120'u32   ## EFT.UI.AnimatedToggle
  TypeRvaUiButton*        = 0x6F93750'u32   ## UnityEngine.UI.Button
  TypeRvaSettingsScreen*  = 0x6F90B90'u32   ## EFT.UI.Settings.SettingsScreen
  TypeRvaMenuScreen*      = 0x6F90D00'u32   ## EFT.UI.MenuScreen
  TypeRvaTmpUgui*         = 0x6F91860'u32   ## TMPro.TextMeshProUGUI

# ---------------------------------------------------------------------------
# THE TARGETS ARE DECLARED BARE AND ASSIGNED INSIDE A PROC, and that is not a
# style choice. In a nimony `--app:lib` build a global INITIALISED BY A CALL is
# silently left ZEROED (`aowl/src/aowlspt/fast.nim`): `var t = rvaTarget(...)`
# at module scope does not fail, it produces an all-zero object whose RVA reads
# 0, and the first call then refuses with `@0x0`. It fails SAFE, which is why
# nobody notices -- the mod loads, the log says "refused", and the refusal names
# the wrong cause. `callrva.verify` detects the shape and says so, but the fix
# is to never write it: bare declarations here, one assignment site below.
# ---------------------------------------------------------------------------

var tChildCount: RvaTarget
var tGetChild: RvaTarget
var tActiveInHierarchy: RvaTarget
var tGetName: RvaTarget
var tCompGameObject: RvaTarget
var tCompTransform: RvaTarget
var tGetRoot: RvaTarget
var tUnityEventInvoke: RvaTarget
var tButtonPress: RvaTarget
var tTypeFromHandle: RvaTarget
var tGetComponentType: RvaTarget
var tToggleSet: RvaTarget
var tPointerClick: RvaTarget
var tSettingsClose: RvaTarget
var tShowInRaid: RvaTarget
var tMenuShowCtrl: RvaTarget

var gInstalled = false

proc hexOf(bs: openArray[uint8]): string =
  ## The generated table carries BYTES; `rvaTarget` declares a HEX STRING. One
  ## conversion here beats sixteen hand-typed bytes per target, and a hand-typed
  ## prologue is precisely what the generator exists to stop anyone writing.
  const digits = "0123456789abcdef"
  result = ""
  var i = 0
  while i < bs.len:
    if i > 0: result.add ' '
    result.add digits[int(bs[i] shr 4'u8)]
    result.add digits[int(bs[i] and 0x0F'u8)]
    inc i

proc installTargets() =
  if gInstalled: return
  gInstalled = true

  # ---- from the GENERATED table -------------------------------------------
  tChildCount = rvaTarget(
    AOWL_SYM_TF_GET_CHILD_COUNT_NAME & " -> int",
    AOWL_SYM_TF_GET_CHILD_COUNT,
    hexOf(AOWL_SYM_TF_GET_CHILD_COUNT_PROLOGUE),
    owners = int32(AOWL_SYM_TF_GET_CHILD_COUNT_OWNERS))

  tGetChild = rvaTarget(
    AOWL_SYM_TF_GET_CHILD_NAME & "(int index) -> Transform",
    AOWL_SYM_TF_GET_CHILD,
    hexOf(AOWL_SYM_TF_GET_CHILD_PROLOGUE),
    owners = int32(AOWL_SYM_TF_GET_CHILD_OWNERS))

  tActiveInHierarchy = rvaTarget(
    AOWL_SYM_GO_ACTIVE_IN_HIERARCHY_NAME & " -> bool",
    AOWL_SYM_GO_ACTIVE_IN_HIERARCHY,
    hexOf(AOWL_SYM_GO_ACTIVE_IN_HIERARCHY_PROLOGUE),
    owners = int32(AOWL_SYM_GO_ACTIVE_IN_HIERARCHY_OWNERS))

  tGetName = rvaTarget(
    AOWL_SYM_OBJ_GET_NAME_NAME & " -> string",
    AOWL_SYM_OBJ_GET_NAME,
    hexOf(AOWL_SYM_OBJ_GET_NAME_PROLOGUE),
    owners = int32(AOWL_SYM_OBJ_GET_NAME_OWNERS))

  tCompGameObject = rvaTarget(
    AOWL_SYMC_COMPONENT_GET_GAMEOBJECT_NAME & " -> GameObject",
    AOWL_SYMC_COMPONENT_GET_GAMEOBJECT,
    hexOf(AOWL_SYMC_COMPONENT_GET_GAMEOBJECT_PROLOGUE),
    owners = int32(AOWL_SYMC_COMPONENT_GET_GAMEOBJECT_OWNERS))

  tCompTransform = rvaTarget(
    AOWL_SYMC_COMPONENT_GET_TRANSFORM_NAME & " -> Transform",
    AOWL_SYMC_COMPONENT_GET_TRANSFORM,
    hexOf(AOWL_SYMC_COMPONENT_GET_TRANSFORM_PROLOGUE),
    owners = int32(AOWL_SYMC_COMPONENT_GET_TRANSFORM_OWNERS))

  tGetRoot = rvaTarget(
    AOWL_SYMC_TF_GET_ROOT_NAME & " -> Transform",
    AOWL_SYMC_TF_GET_ROOT,
    hexOf(AOWL_SYMC_TF_GET_ROOT_PROLOGUE),
    owners = int32(AOWL_SYMC_TF_GET_ROOT_OWNERS))

  tUnityEventInvoke = rvaTarget(
    AOWL_SYM_UNITYEVENT_INVOKE_NAME & "()",
    AOWL_SYM_UNITYEVENT_INVOKE,
    hexOf(AOWL_SYM_UNITYEVENT_INVOKE_PROLOGUE),
    owners = int32(AOWL_SYM_UNITYEVENT_INVOKE_OWNERS))

  tButtonPress = rvaTarget(
    AOWL_SYM_BUTTON_PRESS_NAME & "()",
    AOWL_SYM_BUTTON_PRESS,
    hexOf(AOWL_SYM_BUTTON_PRESS_PROLOGUE),
    owners = int32(AOWL_SYM_BUTTON_PRESS_OWNERS))

  tTypeFromHandle = rvaTarget(
    AOWL_SYM_TYPE_FROM_HANDLE_NAME & "(RuntimeTypeHandle) -> Type",
    AOWL_SYM_TYPE_FROM_HANDLE,
    hexOf(AOWL_SYM_TYPE_FROM_HANDLE_PROLOGUE),
    owners = int32(AOWL_SYM_TYPE_FROM_HANDLE_OWNERS))

  # ---- hand-declared, each naming the header that MEASURED its bytes -------

  # `abi/aowlspt_navui.h`, the inspector's `component` predicate. UNIQUE.
  # `UnityEngine.Component::GetComponent(Type)` -- arity 1:
  #   RCX = this (a Component; a Transform IS one), RDX = System.Type,
  #   R8 = MethodInfo*. THE TRAP (fact #68): this method is declared on
  #   Component, so handing it a GameObject puts the wrong `this` in RCX and
  #   FAULTS inside Unity. Every receiver this mod passes is a Transform,
  #   obtained from `Component::get_transform` or `Transform::GetChild`.
  tGetComponentType = rvaTarget(
    "UnityEngine.Component::GetComponent(Type) -> Component",
    0x52A45E0'u32,
    "48 89 5C 24 08 57 48 83 EC 20 48 8B 05 F7 FE E2",
    owners = 1'i32)

  # `abi/aowlspt_premenu.h` row [1]. UNIQUE, PRIVATE|HIDEBYSIG (non-virtual, so
  # a direct call at the RVA is the only dispatch and there is no override
  # hazard). arity 2: RCX = this (Toggle), DL = value, R8B = sendCallback,
  # R9 = MethodInfo*. `set_isOn` @0x55BA430 was considered and rejected: it is
  # an 11-byte tail-jump thunk into this same body, so it buys nothing and is
  # worse to reason about.
  tToggleSet = rvaTarget(
    "UnityEngine.UI.Toggle::Set(bool value, bool sendCallback)",
    0x55BA450'u32,
    "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 80",
    owners = 1'i32)

  # `abi/aowlspt_premenu.h` row [2]. UNIQUE. WHAT A PLAYER CLICKING A CARD
  # ACTUALLY RUNS, derived from the function's own sixteen bytes:
  #   cmp byte [rcx+0x68],0 ; je ; mov rcx,[rcx+0x70] ; test rcx,rcx ; je ; ...
  # It gates on `_interactable`, loads its `Action OnClick` and invokes it, and
  # NEVER READS the PointerEventData in RDX -- which is why NULL is a safe
  # argument, and is a statement about this disassembly rather than about Unity.
  # Going through the button's own entry point also makes an interactable=false
  # control a no-op BY CONSTRUCTION rather than something this mod has to model.
  tPointerClick = rvaTarget(
    "EFT.UI.TweenAnimatedButton::OnPointerClick(PointerEventData)",
    0x14359B0'u32,
    "80 79 68 00 74 18 48 8B 49 70 48 85 C9 74 0F 48",
    owners = 1'i32)

  # `abi/aowlspt_premenu.h` row [0]. UNIQUE, arity 0. CALLED, never detoured.
  tSettingsClose = rvaTarget(
    "EFT.UI.Settings.SettingsScreen::Close()",
    0x1720B10'u32,
    "40 53 48 83 EC 20 80 3D 02 D9 99 05 00 48 8B D9",
    owners = 1'i32)

  # `abi/aowlspt_premenu.h` row [3]. UNIQUE, arity 0. The SAME sixteen bytes
  # `abi/aowlspt_uihooks.h` site 7 verifies for its detour, so the two tables
  # cannot disagree about what this function starts with.
  tShowInRaid = rvaTarget(
    "EFT.UI.MenuScreen::ShowInRaid()",
    0x1539650'u32,
    "48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 48",
    owners = 1'i32)

  # MEASURED 2026-09-05, live Woods raid: a real ESC fires uihooks site 2 --
  # `MenuScreen::Show(5-arg)` with profile=NULL -- and site 7 (ShowInRaid)
  # never fires. The 5-arg Show's ONLY direct caller is this one-arg
  # `Show(MainMenuBaseScreenController)`, which loads Matchmaker@0x48,
  # ModeDescriptor@0x50, Profile@0x58, ExpansionsPlayerInfo@0x60 and
  # SeasonalRewardController@0x68 off the controller and calls it. UNIQUE,
  # arity 1, virtual -- but the receiver is a MenuScreen itself, never a
  # subclass, so calling this body directly is the body the game runs.
  # Bytes: `il2cpp_resolve.py bytes 0x1538760 16`.
  tMenuShowCtrl = rvaTarget(
    "EFT.UI.MenuScreen::Show(MainMenuBaseScreenController controller)",
    0x1538760'u32,
    "48 83 EC 48 48 85 D2 74 31 48 8B 42 68 4C 8B 4A",
    owners = 1'i32)

# ---------------------------------------------------------------------------
# Verification, ONCE, at load. Reading the code page is safe at mod init: it
# neither patches nor calls, and a target that refuses here refuses loudly with
# the reason instead of at the first press with a plausible silence.
# ---------------------------------------------------------------------------

type
  CallsState* = object
    tried*: bool
    ok*: int         ## targets that byte-verified
    bad*: int        ## targets that REFUSED, each already logged by name
    faults*: int     ## guarded calls that took an access violation
    disabled*: bool  ## the whole call surface is off for this session
    why*: string     ## the first refusal, for the one-line verdict

var gS: CallsState

const MaxCallFaults* = 8
  ## Rule 6, as a WHOLE-FILE budget rather than one per target. A wrong calling
  ## convention would not fault on only one channel, so a per-target budget
  ## would let the same underlying mistake spend eight lives instead of one.

proc note(t: var RvaTarget) =
  let v = verify(t)
  if v.kind == coOk:
    gS.ok = gS.ok + 1
    debug "AutoRaid: " & v.why
  else:
    gS.bad = gS.bad + 1
    if gS.why.len == 0: gS.why = v.why
    warn "AutoRaid: " & v.why & " -- this target is REFUSED for the whole " &
         "session and NOTHING will be called through it."

proc verifyAll*(): CallsState =
  ## Byte-verify every target. Idempotent. Returns the finished state, which is
  ## what the caller reports -- never "we called verify", which is not a fact
  ## about the client.
  if gS.tried: return gS
  gS.tried = true
  installTargets()
  note tChildCount
  note tGetChild
  note tActiveInHierarchy
  note tGetName
  note tCompGameObject
  note tCompTransform
  note tGetRoot
  note tUnityEventInvoke
  note tButtonPress
  note tTypeFromHandle
  note tGetComponentType
  note tToggleSet
  note tPointerClick
  note tSettingsClose
  note tShowInRaid
  note tMenuShowCtrl
  result = gS

proc callsDisabled*(): bool =
  ## The kill switch, read at the top of every tick. It trips on the SHARED
  ## fault counter callrva maintains process-wide, not on a counter of our own:
  ## a mod that invents its own would be measuring something else.
  if gS.disabled: return true
  if int(faultCount()) - gS.faults >= MaxCallFaults:
    gS.disabled = true
    warn "AutoRaid: SELF-DISABLED -- " & $MaxCallFaults & " guarded calls " &
         "into the game have faulted this session. Every feature of this mod " &
         "that touches the client is OFF for the rest of the run; the menu " &
         "and the settings still work and nothing further will be called."
    return true
  result = false

proc noteFaultBase*() =
  ## Record the process-wide fault count at arming time, so this mod's budget
  ## counts ITS OWN faults rather than inheriting another mod's.
  gS.faults = int(faultCount())

proc buildIdentity*(): string =
  ## The build every RVA in this file was measured against. Logged once at load
  ## so that a run on a different `GameAssembly.dll` is a visible statement in
  ## the log rather than something inferred from a pile of refusals.
  "imageKey 0x" & $AowlSymtabImageKey & ", GameAssembly.dll sha256 " &
  AowlSymtabFileSha256

# ---------------------------------------------------------------------------
# The wrappers. Each is the ONLY way this mod performs that operation.
# ---------------------------------------------------------------------------

#
# THE RECEIVER GATE, applied by every one of them and stated once here: a
# receiver must be READABLE and ALIVE. Readable is not alive -- a destroyed
# Unity object stays readable with `m_CachedPtr` zeroed (fact #182), and a
# managed call on that corpse faults inside Unity, which is the single most
# common way this mod could kill the client. The gate is repeated in each
# wrapper rather than factored into a "checked call" helper because the helper
# would have to be generic over slot shapes, and a generic call path is the one
# thing `callrva` deliberately refuses to be.

proc receiverOk(p: Il2CppPtr): bool =
  (not callsDisabled()) and readable(p, 0x20) and alive(p)

proc childCount*(tr: Il2CppPtr; ok: var bool): int =
  ## `Transform::get_childCount`. `ok` distinguishes "no children" from "could
  ## not look", which a bare 0 cannot -- and a walk that treats the second as
  ## the first reports an empty screen and calls it an answer.
  ok = false
  result = 0
  if not receiverOk(tr): return
  var a = callArgs()
  addPtr(a, tr)
  let o = callInt(tChildCount, a)
  if o.kind != coOk: return
  ok = true
  result = int(o.g)

proc childAt*(tr: Il2CppPtr; i, n: int): Il2CppPtr =
  ## `Transform::GetChild(index)`. THE INDEX IS BOUNDS-CHECKED HERE, against the
  ## `n` the caller just read, because `GetChild` THROWS on an out-of-range
  ## index and a managed exception thrown through a native frame is not
  ## something this mod can survive. `n` is passed in rather than re-read so
  ## that the bound and the loop cannot drift apart.
  result = nil
  if i < 0 or i >= n: return
  if not receiverOk(tr): return
  var a = callArgs()
  addPtr(a, tr)
  addInt(a, int64(i))
  let o = callPtr(tGetChild, a)
  if o.kind != coOk: return
  let c = asPtr(o)
  if c != nil and readable(c, 0x20): result = c

proc gameObjectOf*(comp: Il2CppPtr): Il2CppPtr =
  ## `Component::get_gameObject`. A Transform IS a Component, so this is the
  ## legal way from a walked node to the object `activeInHierarchy` is declared
  ## on. Going the other way -- calling a Component method with a GameObject in
  ## RCX -- is fact #68 and faults inside Unity.
  result = nil
  if not receiverOk(comp): return
  var a = callArgs()
  addPtr(a, comp)
  let o = callPtr(tCompGameObject, a)
  if o.kind != coOk: return
  let g = asPtr(o)
  if g != nil and readable(g, 0x20): result = g

proc transformOf*(comp: Il2CppPtr): Il2CppPtr =
  ## `Component::get_transform`. How a SCREEN RECEIVER -- which arrives as the
  ## screen's MonoBehaviour, not as a Transform -- becomes something the walkers
  ## can descend. Note this RVA has 15 owners; that is fine to CALL (it is
  ## correct code for the receiver passed) and would be catastrophic to detour,
  ## which this mod never does.
  result = nil
  if not receiverOk(comp): return
  var a = callArgs()
  addPtr(a, comp)
  let o = callPtr(tCompTransform, a)
  if o.kind != coOk: return
  let t = asPtr(o)
  if t != nil and readable(t, 0x20): result = t

proc rootOf*(tr: Il2CppPtr): Il2CppPtr =
  ## `Transform::get_root` -- THE ONE WAY THIS MOD REACHES A SCENE ROOT.
  ##
  ## The host walks `DontDestroyOnLoad`'s roots via `GameObject::
  ## get_scene_Injected` + `Scene::GetRootGameObjects`. This mod deliberately
  ## does not: `GetRootGameObjects` ALLOCATES (a List and an array), which is
  ## banned on a per-frame path, and MEASURED 2026-09-02 the enumeration is the
  ## LOCATION scene once a raid has loaded, so it cannot see the menu at all.
  ##
  ## Climbing from a receiver the game handed us is strictly better and is the
  ## repo's own rule: reach a container by WALKING from a verified live object,
  ## never by an enumeration that can legitimately be empty. `Common UI` is the
  ## root of the MenuScreen receiver; `Menu UI` is the root of the matchmaker
  ## screens. Both are therefore reachable in one call from something the game
  ## proved was alive.
  result = nil
  if not receiverOk(tr): return
  var a = callArgs()
  addPtr(a, tr)
  let o = callPtr(tGetRoot, a)
  if o.kind != coOk: return
  let r = asPtr(o)
  if r != nil and readable(r, 0x20): result = r

proc nodeName*(node: Il2CppPtr): string =
  ## `Object::get_name`, decoded by the fixed `System.String` layout. "" means
  ## NOT READABLE or genuinely empty; no caller may treat "" as a match.
  result = ""
  if not receiverOk(node): return
  var a = callArgs()
  addPtr(a, node)
  let o = callPtr(tGetName, a)
  if o.kind != coOk: return
  result = readString(asPtr(o))

proc activeInHierarchy*(node: Il2CppPtr; ok: var bool): bool =
  ## `GameObject::get_activeInHierarchy`, reached through `get_gameObject`.
  ##
  ## `ok` is the whole point. An INACTIVE control is NOT PRESSABLE (fact #72):
  ## pressing one returns success and does nothing. "Could not look" must never
  ## collapse into either answer, because "not active" makes the mod wait
  ## forever and "active" makes it press a corpse.
  ok = false
  result = false
  let go = gameObjectOf(node)
  if go == nil: return
  var a = callArgs()
  addPtr(a, go)
  let o = callBool(tActiveInHierarchy, a)
  if o.kind != coOk: return
  ok = true
  result = o.g != 0'i64

proc isActive*(node: Il2CppPtr): bool =
  ## The two-valued form, for the many places that want "definitely active".
  ## Deliberately FALSE when the read failed: a walk must not press something it
  ## could not confirm is on screen.
  var ok = false
  let a = activeInHierarchy(node, ok)
  result = ok and a

# ---- components -----------------------------------------------------------

proc typeObject*(typeRva: uint32; why: var string): Il2CppPtr =
  ## `System.Type::GetTypeFromHandle(Il2CppType*)`. No reflection anywhere in
  ## this chain: the handle is a static DATA address resolved offline, and the
  ## method is byte-verified like every other.
  ##
  ## Re-derived on every call rather than cached across frames: the runtime
  ## returns its OWN cached Type object, so this is a lookup and not an
  ## allocation, and re-deriving means a search that spans frames never carries
  ## a stale managed pointer across a GC.
  result = nil
  why = ""
  if callsDisabled():
    why = "the call surface is self-disabled for this session"
    return
  let td = dataAt(typeRva)
  if td == nil:
    why = "the offline Il2CppType address 0x" & $typeRva & " is not readable " &
          "here -- either GameAssembly.dll is not mapped yet, or this is not " &
          "the build those addresses were measured against"
    return
  var a = callArgs()
  addPtr(a, td)
  let o = callPtr(tTypeFromHandle, a)
  if o.kind != coOk:
    why = "System.Type::GetTypeFromHandle " & o.why
    return
  let t = asPtr(o)
  if t == nil or not readable(t, 0x20):
    why = "GetTypeFromHandle returned something that is not a usable " &
          "System.Type, so no component lookup was attempted"
    return
  result = t

proc componentOf*(node: Il2CppPtr; typeRva: uint32; why: var string): Il2CppPtr =
  ## `Component::GetComponent(Type)` on a Transform receiver.
  ##
  ## A NULL RETURN IS AN ANSWER, not a failure: it means this object has no
  ## component of that type. `why` distinguishes that from "nothing was called",
  ## and both call sites in this mod care about the difference.
  result = nil
  why = ""
  if not receiverOk(node):
    why = "the receiver is not readable, or its native half is null " &
          "(a destroyed object stays readable -- fact #182)"
    return
  let tobj = typeObject(typeRva, why)
  if tobj == nil: return
  var a = callArgs()
  addPtr(a, node)
  addPtr(a, tobj)
  let o = callPtr(tGetComponentType, a)
  if o.kind != coOk:
    why = "Component::GetComponent(Type) " & o.why
    return
  let c = asPtr(o)
  if c == nil:
    why = "GetComponent(Type) returned NULL -- an ANSWER: this object carries " &
          "no component of that type"
    return
  if not readable(c, 0x20):
    why = "GetComponent(Type) returned a pointer that is not readable"
    return
  result = c

# ---- the three press routes ----------------------------------------------
#
# THREE KLASSES, THREE ROUTES, EACH MEASURED. There is deliberately NO generic
# route, because the generic route is what faulted: `arOnClickOff` in the host
# returned the generic UnityEvent offset 0x100 for every klass that was not a
# DefaultUIButton, and on an `EFT.UI.AnimatedToggle` that offset is
# `toggleTransition` -- an ENUM. A small integer is not null, is not a
# GameObject and is not a known klass, so it passes every guard available, and
# is then CALLED as a UnityEvent. Two deterministic access violations.

proc toggleSet*(comp: Il2CppPtr; value, sendCallback: bool; why: var string): bool =
  ## `Toggle::Set(value, sendCallback)` -- THE GAME'S OWN WAY to turn a toggle
  ## on. `sendCallback = true` at every call site here on purpose: the point of
  ## pressing the control is to run the handler the screen attached to it.
  result = false
  why = ""
  if not receiverOk(comp):
    why = "the Toggle component is not readable, or its native half is null"
    return
  var a = callArgs()
  addPtr(a, comp)
  addBool(a, value)
  addBool(a, sendCallback)
  let o = callVoid(tToggleSet, a)
  if o.kind != coOk:
    why = o.why & ". The toggle was NOT set, and the old +0x100 UnityEvent " &
          "route is not a fallback -- it is the bug."
    return
  result = true

proc pointerClick*(tween: Il2CppPtr; why: var string): bool =
  ## `TweenAnimatedButton::OnPointerClick(NULL)` -- the button's OWN entry
  ## point, which is what a human click runs.
  result = false
  why = ""
  if not receiverOk(tween):
    why = "the TweenAnimatedButton is not readable, or its native half is null"
    return
  var a = callArgs()
  addPtr(a, tween)
  addPtr(a, nil)          # PointerEventData -- provably never read; see above
  let o = callVoid(tPointerClick, a)
  if o.kind != coOk:
    why = o.why
    return
  result = true

proc unityButtonPress*(comp: Il2CppPtr; why: var string): bool =
  ## `UnityEngine.UI.Button::Press()` -- the game's own click path for a plain
  ## `UnityEngine.UI.Button`. It re-checks IsActive and IsInteractable itself
  ## and then fires m_OnClick, exactly as a real click does. It is used INSTEAD
  ## of a UnityEvent read at an offset, because firing an event read at a
  ## guessed offset on a klass this mod has never handled is precisely the blind
  ## call it does not make.
  result = false
  why = ""
  if not receiverOk(comp):
    why = "the Button component is not readable, or its native half is null"
    return
  var a = callArgs()
  addPtr(a, comp)
  let o = callVoid(tButtonPress, a)
  if o.kind != coOk:
    why = o.why
    return
  result = true

proc unityEventInvoke*(ev: Il2CppPtr; why: var string): bool =
  ## `UnityEvent::Invoke()` -- the WEAKER path, used only as an announced
  ## fallback when a DefaultUIButton's own `_button` is unreachable. It reaches
  ## the same handler but SKIPS the button's interactable gate, and MEASURED
  ## 2026-09-02 that left the profile/mode screen half-transitioned with neither
  ## card clickable. Every caller says out loud that it took this route.
  ##
  ## The guard before it is a FLOOR, not proof: a managed object's first qword
  ## is its `Il2CppClass*`, so an object that is really there has a readable
  ## klass pointer whose own first pointer is readable too. That rejects a value
  ## which is not a live managed object at all -- the class of value that faults
  ## -- and it cannot certify that `ev` IS a UnityEvent. Saying which of those
  ## it is doing is the whole point of the sentence.
  result = false
  why = ""
  if ev == nil:
    why = "the OnClick UnityEvent slot read null"
    return
  if not readable(ev, 0x40):
    why = "the event pointer is not readable for 0x40 bytes, so it is not a " &
          "live managed object. Nothing was called."
    return
  let klass = readPtr(ev, 0)
  if klass == nil or not readable(klass, 0x40):
    why = "the object in the OnClick slot has no readable Il2CppClass* in its " &
          "first qword, so it is not a live managed object. Nothing was called."
    return
  var a = callArgs()
  addPtr(a, ev)
  let o = callVoid(tUnityEventInvoke, a)
  if o.kind != coOk:
    why = o.why
    return
  result = true

proc settingsClose*(comp: Il2CppPtr; why: var string): bool =
  ## `SettingsScreen::Close()`. MEASURED 2026-09-02: this HIDES the settings
  ## screen and does NOT restore the main menu, so it is a FALLBACK behind the
  ## screen's own BackButton and every caller asserts the menu coming back
  ## rather than the screen going away.
  result = false
  why = ""
  if not receiverOk(comp):
    why = "the SettingsScreen component is not readable, or its native half " &
          "is null"
    return
  var a = callArgs()
  addPtr(a, comp)
  let o = callVoid(tSettingsClose, a)
  if o.kind != coOk:
    why = o.why
    return
  result = true

proc menuShowWithController*(comp, ctrl: Il2CppPtr; why: var string): bool =
  ## `MenuScreen::Show(MainMenuBaseScreenController)` -- the body the ESC key
  ## reaches in a raid (MEASURED 2026-09-05, see `tMenuShowCtrl`). `ctrl` is
  ## read off the live MenuScreen by the caller and cross-checked there; this
  ## only refuses an unreadable receiver or controller.
  result = false
  why = ""
  if not receiverOk(comp):
    why = "the MenuScreen component is not readable, or its native half is null"
    return
  if ctrl == nil:
    why = "the controller is NULL; Show(controller) throws on a null " &
          "controller (the body's first test), so it was not called"
    return
  var a = callArgs()
  addPtr(a, comp)
  addPtr(a, ctrl)
  let o = callVoid(tMenuShowCtrl, a)
  if o.kind != coOk:
    why = o.why
    return
  result = true

proc menuShowInRaid*(comp: Il2CppPtr; why: var string): bool =
  ## `MenuScreen::ShowInRaid()`. MEASURED 2026-09-05 in a live Woods raid: it
  ## does NOT put the in-raid menu up. Its body reads `_environment@0x108`
  ## and works on the EnvironmentUI; it never reaches the 5-arg Show, and
  ## calling it left NOTHING active under the MenuScreen (the exit's
  ## DISCONNECT step then found nothing for 20 s). Kept as a call, unused by
  ## the exit path; `menuShowWithController` is what opens the menu.
  result = false
  why = ""
  if not receiverOk(comp):
    why = "the MenuScreen component is not readable, or its native half is null"
    return
  var a = callArgs()
  addPtr(a, comp)
  let o = callVoid(tShowInRaid, a)
  if o.kind != coOk:
    why = o.why
    return
  result = true
