## `aowl-coverage` -- generate the derived half of `docs/EMULATOR-COVERAGE.md`,
## and check it against the code.
##
##     aowl-coverage                    rewrite the generated regions in place
##     aowl-coverage --check            write nothing; fail if they are stale
##     aowl-coverage --repo D:\aowlspt
##     aowl-coverage -q                 findings only
##
## `docs/EMULATOR-COVERAGE.md` used to be rebuilt by hand: four shell commands
## re-run over `reference/` and `mods/tarkov`, and a three-bucket split joined
## by hand on top of them. Every headline in it was therefore only as current as
## the last person who remembered, and the failure was silent -- the table does
## not become obviously wrong, it becomes quietly out of date while still
## reading as measured. `docs/BACKLOG.md` carried that as B11.
##
## ## What is derived, and from what
##
## **The demand side** -- which operations exist at all -- is the `Callbacks`
## classes in `reference/spt-4.1-surface.txt`, swept exactly as the document's
## own "How it was derived" section says: from the first
## `class SPTarkov.Server.Core.Callbacks.*` to
## `static class SPTarkov.Server.Core.Constants`, members only, no `ctor`, and
## without the framework's own `OnLoadAsync` / `OnUpdateAsync` / `static ` /
## `Void Send` / `Void Process`. Three of those classes are the SPT server's own
## plumbing rather than client requests, and they are named in the input file
## rather than assumed here.
##
## **The supply side** is the mod: the routes `mods/tarkov/tarkov.nim`
## registers, and the item-event action names `mods/tarkov/emu/*.nim` dispatch
## on.
##
## **The join** -- which operation is answered by which route or action -- is
## the one thing no sweep can produce, and it lives in
## `docs/coverage-rows.json`, one row per callback method. That file is the only
## hand-maintained half, and it is checked in both directions: a method in the
## reference with no row is an error, and a row naming a method the reference
## does not have is an error.
##
## ## The bucket is not stored
##
## This is the part that used to drift. `docs/coverage-rows.json` does **not**
## say which of the three buckets an operation is in; the bucket is worked out
## here, from the code:
##
##  * a row that names no route and no action is **not served**;
##  * a row that names no action and whose every route is bound to a stock stub
##    -- `onNullData`, `onEmptyObject`, `onEmptyArray`, `onTrue` -- is **served,
##    deliberately empty**;
##  * everything else is **served and shaped**.
##
## So the split cannot disagree with `tarkov.nim` any more. Rebinding a route
## from a real handler to `onEmptyObject`, or the other way, moves the headline
## on the next run without anybody editing a number.
##
## ## And the cross-check, which is the point
##
## Rows and code are checked against each other in both directions:
##
##  * every route a row names is registered in `tarkov.nim`;
##  * every route `tarkov.nim` registers is named by some row, or is listed in
##    the input's `nonClientRoutes` -- and every entry in *that* list has to be a
##    route which is really registered, so the exemption cannot rot either;
##  * every action a row names appears as a string literal in the emulator's
##    source, with comments stripped, so a row cannot claim an arm that was
##    deleted or renamed.
##
## That is what converts "somebody remembered" into "the gate noticed".

import std/[strutils, syncio, cmdline]
import aowlsptinstall/[winfs, log]
import aowlspt/json

const
  Usage = """
aowl-coverage -- generate and check docs/EMULATOR-COVERAGE.md's derived tables

  aowl-coverage [--repo PATH] [--check] [-q]

  --repo PATH    the repository to work in (default: found from this exe, or
                 the current directory)
  --check        write nothing; exit non-zero and say what differs if the
                 document on disk is not what would be generated. This is the
                 mode `aowl test` runs.
  -q, --quiet    findings only
  -h, --help     this
"""

  BeginBuckets = "<!-- coverage:begin buckets -- generated by tools/coverage.nim, do not edit -->"
  EndBuckets = "<!-- coverage:end buckets -->"
  BeginCommands = "<!-- coverage:begin commands -- generated by tools/coverage.nim, do not edit -->"
  EndCommands = "<!-- coverage:end commands -->"
  BeginSweeps = "<!-- coverage:begin sweeps -- generated by tools/coverage.nim, do not edit -->"
  EndSweeps = "<!-- coverage:end sweeps -->"
    ## The *second* place the four figures appear: the prose that shows the
    ## commands a person would run by hand, with each command's answer written
    ## beside it. It was not generated, and it drifted -- the supply fence said
    ## 95 routes and 145 arms while the maintained table three hundred lines
    ## below said 99 and 152, in the same document, about the same greps. A
    ## figure quoted twice is maintained once; this makes the second copy the
    ## generator's too.

type
  Operation = object
    callback: string       ## the `Callbacks` class, without the suffix
    op: string             ## the method name
    routes: seq[string]
    actions: seq[string]
    note: string
    bucket: string         ## derived here, never read from the input

  Supply = object
    routes: seq[string]        ## every route `tarkov.nim` registers, in order
    stubbed: seq[string]       ## those bound to a stock stub handler
    armLines: int              ## lines matching `of "` under `emu/`
    code: string               ## `emu/*.nim` + `tarkov.nim`, comments stripped

var gFailures = 0
var gWarnings = 0
var gChecks = 0

proc check(what: string; condition: bool; detail = "") =
  inc gChecks
  if condition:
    ok what
  else:
    inc gFailures
    err what
    if detail.len > 0:
      line "      " & detail

# --------------------------------------------------------- small text helpers

proc has(items: seq[string]; want: string): bool =
  result = false
  for it in items:
    if it == want: return true

proc joined(items: seq[string]; sep: string): string =
  result = ""
  for it in items:
    if result.len > 0: result.add sep
    result.add it

proc firstN(items: seq[string]; n: int): string =
  ## The first `n` of a finding list, so a wholesale disagreement does not
  ## print two hundred lines before the reason for it.
  var shown: seq[string] = @[]
  var i = 0
  while i < items.len and i < n:
    shown.add items[i]
    inc i
  result = joined(shown, ", ")
  if items.len > n:
    result.add ", and " & $(items.len - n) & " more"

proc isIdentChar(c: char): bool =
  result = (c >= 'a' and c <= 'z') or (c >= 'A' and c <= 'Z') or
           (c >= '0' and c <= '9') or c == '_'

proc readOrDie(p: string): string =
  var text = ""
  if not readTextFile(p, text):
    fatal "cannot read " & p
  result = text

proc stripComments(src: string): string =
  ## Everything outside a `#` comment and outside a string literal. The action
  ## check needs this: `emu/customise.nim` names `CustomizationSet` in six
  ## comments and once in code, and a row may only be believed on the once.
  result = ""
  for ln in splitLines(src):
    var kept = ""
    var i = 0
    var quoted = false
    while i < ln.len:
      let c = ln[i]
      if quoted:
        kept.add c
        if c == '\\' and i + 1 < ln.len:
          inc i
          kept.add ln[i]
        elif c == '"':
          quoted = false
      elif c == '"':
        quoted = true
        kept.add c
      elif c == '#':
        break
      else:
        kept.add c
      inc i
    result.add kept
    result.add "\n"

# ------------------------------------------------- the reference dump's sweeps

proc callbackMethods(refText: string; classes: var seq[string];
                     methods: var seq[string]): int =
  ## The document's first command, spelled out. `classes[i]` is the class
  ## `methods[i]` was declared in, with the `Callbacks` suffix dropped, because
  ## that is how `docs/coverage-rows.json` names them.
  var inside = false
  var cls = ""
  result = 0
  for ln in splitLines(refText):
    if ln.startsWith("class SPTarkov.Server.Core.Callbacks."):
      inside = true
    elif ln.startsWith("static class SPTarkov.Server.Core.Constants"):
      inside = false
    if not inside: continue
    if ln.startsWith("class "):
      # `class SPTarkov.Server.Core.Callbacks.AchievementCallbacks` -> the tail.
      var name = ln.substr(6)
      let sp = name.find(' ')
      if sp >= 0: name = name.substr(0, sp - 1)
      var dot = -1
      var d = 0
      while d < name.len:
        if name[d] == '.': dot = d
        inc d
      if dot >= 0: name = name.substr(dot + 1)
      if name.endsWith("Callbacks"):
        name = name.substr(0, name.len - 10)
      cls = name
      continue
    if not ln.startsWith("    "): continue
    if ln.startsWith("    ctor"): continue
    if ln.contains("OnLoadAsync") or ln.contains("OnUpdateAsync") or
       ln.contains("static ") or ln.contains("Void Send") or
       ln.contains("Void Process"): continue
    # `    ValueTask<String> GetAchievements(String url, ...)`
    let body = ln.strip()
    let sp = body.find(' ')
    if sp < 0: continue
    var name = body.substr(sp + 1)
    let par = name.find('(')
    if par >= 0: name = name.substr(0, par - 1)
    name = name.strip()
    if name.len == 0: continue
    classes.add cls
    methods.add name
    inc result

proc itemEventActionCount(refText: string): int =
  ## The document's second command. Counted, not collected: the action *names*
  ## the emulator answers are checked against the code by row, and this number
  ## is only ever printed.
  var inside = false
  result = 0
  for ln in splitLines(refText):
    if ln.contains("Models.Enums.ItemEventActions"):
      inside = true
    elif ln.contains("Models.Enums.ItemTpl"):
      inside = false
    if inside and ln.contains("    field String"):
      inc result

# ------------------------------------------------------------ the mod's supply

proc scanRoutes(src: string; routes: var seq[string]; stubbed: var seq[string]): int =
  ## Every `serve("...")` and `servePrefix("...")` in `tarkov.nim`, and which of
  ## them are bound to a stock stub. The handler may be on the next line -- two
  ## of them are -- so this reads past the newline rather than per line.
  result = 0
  var i = 0
  while i < src.len:
    var mark = -1
    if src.substr(i).startsWith("servePrefix(\""): mark = i + 13
    elif src.substr(i).startsWith("serve(\""): mark = i + 7
    if mark < 0:
      inc i
      continue
    var j = mark
    while j < src.len and src[j] != '"': inc j
    if j >= src.len: break
    let route = src.substr(mark, j - 1)
    routes.add route
    inc result
    # The handler: skip `,` and any whitespace, then read the identifier.
    var k = j + 1
    while k < src.len and (src[k] == ',' or src[k] == ' ' or src[k] == '\n' or
                           src[k] == '\r' or src[k] == '\t'): inc k
    var h = ""
    while k < src.len and isIdentChar(src[k]):
      h.add src[k]
      inc k
    if h == "onNullData" or h == "onEmptyObject" or h == "onEmptyArray" or
       h == "onTrue":
      stubbed.add route
    i = j + 1

proc readSupply(repo: string): Supply =
  result = Supply(routes: @[], stubbed: @[], armLines: 0, code: "")
  let tarkov = readOrDie(joinPath(repo, "mods\\tarkov\\tarkov.nim"))
  discard scanRoutes(tarkov, result.routes, result.stubbed)
  result.code = stripComments(tarkov)

  let emuDir = joinPath(repo, "mods\\tarkov\\emu")
  var files: seq[string] = @[]
  var dirs: seq[string] = @[]
  collectEntries(emuDir, files, dirs)
  for rel in files:
    if not rel.endsWith(".nim"): continue
    let text = readOrDie(joinPath(emuDir, rel))
    for ln in splitLines(text):
      if ln.contains("of \""): inc result.armLines
    result.code.add stripComments(text)

# ---------------------------------------------------------------- the rows

proc textsOf(j: JsonRef): seq[string] =
  result = @[]
  if not j.exists or not j.isArray: return
  for it in each(j):
    let s = it.asText("")
    if s.len > 0: result.add s

proc readRows(text: string; ops: var seq[Operation];
              nonClient: var seq[string]; post1: var seq[string];
              excluded: var seq[string]): bool =
  let root = whole(text)
  if not root.exists or not root.isObject: return false
  nonClient = textsOf(root.child("nonClientRoutes"))
  post1 = textsOf(root.child("post1OnlyRoutes"))
  let ex = root.child("excludedCallbackClasses")
  if ex.exists and ex.isObject:
    for k in keys(ex): excluded.add k
  let arr = root.child("operations")
  if not arr.exists or not arr.isArray: return false
  for it in each(arr):
    var o = Operation(callback: "", op: "", routes: @[], actions: @[],
                      note: "", bucket: "")
    o.callback = it.child("callback").asText("")
    o.op = it.child("op").asText("")
    o.routes = textsOf(it.child("routes"))
    o.actions = textsOf(it.child("actions"))
    o.note = it.child("note").asText("")
    ops.add o
  result = true

proc bucketOf(o: Operation; stubbed: seq[string]): string =
  ## The whole of the served / empty / absent split, in nine lines, against the
  ## code rather than against anybody's memory.
  if o.routes.len == 0 and o.actions.len == 0:
    return "absent"
  if o.actions.len > 0:
    return "shaped"
  var allStub = true
  for r in o.routes:
    if not stubbed.has(r): allStub = false
  result = if allStub: "empty" else: "shaped"

# ------------------------------------------------------------- the two regions

proc bucketsRegion(shaped, empty, absent, total, methods: int;
                   excluded: seq[string]): string =
  var ticked: seq[string] = @[]
  for e in excluded: ticked.add "`" & e & "`"
  result = "| | operations | |\n"
  result.add "|---|---|---|\n"
  result.add "| **served, and shaped against the reference DTO** | " & $shaped &
             " | a route or an item-event arm of its own |\n"
  result.add "| **served, deliberately empty or flattened** | " & $empty &
             " | answered by a stock stub -- `onNullData`, `onEmptyObject`, " &
             "`onEmptyArray` or `onTrue` -- and named individually below |\n"
  result.add "| **not served** | " & $absent &
             " | 404s, and the client retries or does without |\n"
  result.add "| **client-facing operations** | " & $total &
             " | the " & $methods & " callback methods less the " &
             $(methods - total) & " in " & joined(ticked, ", ") &
             ", which are that server's own plumbing |\n"

proc commandsRegion(methods, actions, routes, arms: int): string =
  result = "| command | count |\n"
  result.add "|---|---:|\n"
  result.add "| the callback sweep over `reference/spt-4.1-surface.txt` | **" &
             $methods & "** methods |\n"
  result.add "| the `ItemEventActions` sweep over the same file | **" &
             $actions & "** fields |\n"
  result.add "| `grep -oE 'serve(Prefix)?\\(\"[^\"]+\"' mods/tarkov/tarkov.nim` | **" &
             $routes & "** routes |\n"
  result.add "| `grep -rn 'of \"' mods/tarkov/emu/*.nim` | **" & $arms &
             "** arms |\n"

proc sweepsRegion(actions, routes, arms: int): string =
  ## The "how it was derived" prose, counts and all. Prose inside a generated
  ## region is unusual and is the point: the sentences here exist only to carry
  ## the numbers, and a sentence that carries a number nobody recomputes is a
  ## sentence that will be wrong.
  result = $actions & " of them.\n"
  result.add "\n"
  result.add "**The supply side** is the mod:\n"
  result.add "\n"
  result.add "```\n"
  result.add "grep -oE 'serve(Prefix)?\\(\"[^\"]+\"' mods/tarkov/tarkov.nim   # " &
             $routes & " routes\n"
  result.add "grep -rn 'of \"' mods/tarkov/emu/*.nim                       # " &
             $arms & " action arms\n"
  result.add "```\n"

proc replaceRegion(doc: string; beginMark, endMark, body: string;
                   dest: var string): bool =
  ## Everything between the two markers, replaced. The markers themselves and
  ## every line outside them survive byte for byte, which is the point: the
  ## document is mostly prose that no generator could write.
  let b = doc.find(beginMark)
  if b < 0: return false
  let e = doc.find(endMark, b)
  if e < 0: return false
  dest = doc.substr(0, b + beginMark.len - 1) & "\n" & body &
         doc.substr(e)
  result = true

# ----------------------------------------------------------------------- main

proc looksLikeRepo(p: string): bool =
  result = isDirectory(joinPath(p, "docs")) and
           isDirectory(joinPath(p, "mods")) and
           isDirectory(joinPath(p, "tools"))

proc main(): int =
  var repo = ""
  var checkOnly = false
  var i = 1
  let n = paramCount()
  while i <= n:
    let a = paramStr(i)
    if a == "--repo":
      inc i
      if i <= n: repo = paramStr(i)
    elif a == "--check":
      checkOnly = true
    elif a == "--quiet" or a == "-q":
      setVerbosity vQuiet
    elif a == "--help" or a == "-h":
      echo Usage
      return 0
    elif a.startsWith("-"):
      fatal "unknown option: " & a
    elif repo.len == 0:
      repo = a
    inc i

  if repo.len == 0:
    var here = parentOf(absolutePathOf(paramStr(0)))
    var hops = 0
    while hops < 6 and here.len > 3:
      if looksLikeRepo(here):
        repo = here
        break
      here = parentOf(here)
      inc hops
  if repo.len == 0:
    repo = absolutePathOf(".")
  repo = absolutePathOf(repo)

  heading "aowl-coverage"
  line "  " & repo

  # --------------------------------------------------------------- the sweeps
  let refText = readOrDie(joinPath(repo, "reference\\spt-4.1-surface.txt"))
  var refClasses: seq[string] = @[]
  var refMethods: seq[string] = @[]
  let methodCount = callbackMethods(refText, refClasses, refMethods)
  let actionCount = itemEventActionCount(refText)
  let supply = readSupply(repo)

  heading "The four sweeps"
  line "  " & $methodCount & " callback methods"
  line "  " & $actionCount & " item-event action names"
  line "  " & $supply.routes.len & " routes registered"
  line "  " & $supply.armLines & " lines with an `of \"` arm under emu/"
  check("the callback sweep found something", methodCount > 0)
  check("the item-event sweep found something", actionCount > 0)
  check("`tarkov.nim` registers routes", supply.routes.len > 0)

  # ----------------------------------------------------------------- the rows
  let rowsPath = joinPath(repo, "docs\\coverage-rows.json")
  var ops: seq[Operation] = @[]
  var nonClient: seq[string] = @[]
  var post1: seq[string] = @[]
  var excluded: seq[string] = @[]
  if not readRows(readOrDie(rowsPath), ops, nonClient, post1, excluded):
    fatal "docs/coverage-rows.json does not parse as the expected object"

  heading "The rows against the reference"

  # Every callback the reference names, less the classes the input excludes,
  # must have exactly one row -- and no row may name anything else.
  var wanted: seq[string] = @[]
  var j = 0
  while j < refMethods.len:
    var skip = false
    for e in excluded:
      # The input names classes as they appear in the dump; the sweep has
      # already dropped the `Callbacks` suffix.
      var short = e
      if short.endsWith("Callbacks"): short = short.substr(0, short.len - 10)
      if refClasses[j] == short: skip = true
    if not skip:
      wanted.add refClasses[j] & "." & refMethods[j]
    inc j

  var have: seq[string] = @[]
  for o in ops: have.add o.callback & "." & o.op

  var missing: seq[string] = @[]
  for w in wanted:
    if not have.has(w): missing.add w
  var extra: seq[string] = @[]
  for h in have:
    if not wanted.has(h): extra.add h
  var dupes: seq[string] = @[]
  var a = 0
  while a < have.len:
    var b = a + 1
    while b < have.len:
      if have[a] == have[b] and not dupes.has(have[a]): dupes.add have[a]
      inc b
    inc a

  check("every client-facing callback method has a row (" & $wanted.len & ")",
        missing.len == 0,
        "no row for: " & firstN(missing, 8))
  check("every row names a callback method the reference has",
        extra.len == 0,
        "not in the reference: " & firstN(extra, 8))
  check("no callback method has two rows", dupes.len == 0,
        "twice: " & firstN(dupes, 8))

  # --------------------------------------------- the rows against the mod
  heading "The rows against the code"

  var unregistered: seq[string] = @[]
  var claimed: seq[string] = @[]
  for o in ops:
    for r in o.routes:
      if not claimed.has(r): claimed.add r
      if not supply.routes.has(r) and not unregistered.has(r):
        unregistered.add r
  check("every route a row names is registered in `tarkov.nim`",
        unregistered.len == 0,
        "claimed and never served: " & firstN(unregistered, 8))

  var unclaimed: seq[string] = @[]
  for r in supply.routes:
    if claimed.has(r) or nonClient.has(r) or post1.has(r) or unclaimed.has(r):
      continue
    unclaimed.add r
  check("every registered route is named by a row",
        unclaimed.len == 0,
        "served and in no row: " & firstN(unclaimed, 8))

  var staleExempt: seq[string] = @[]
  for r in nonClient:
    if not supply.routes.has(r): staleExempt.add r
  check("every `nonClientRoutes` exemption is a route that exists",
        staleExempt.len == 0,
        "exempted and not registered: " & firstN(staleExempt, 8))

  # The post-1.0-only exemption gets the same treatment, and for the same
  # reason: an exemption nobody checks is a hole that grows.
  var stalePost1: seq[string] = @[]
  for r in post1:
    if not supply.routes.has(r): stalePost1.add r
  check("every `post1OnlyRoutes` exemption is a route that exists",
        stalePost1.len == 0,
        "exempted and not registered: " & firstN(stalePost1, 8))

  var lostActions: seq[string] = @[]
  for o in ops:
    for act in o.actions:
      if not supply.code.contains("\"" & act & "\""):
        lostActions.add o.callback & "." & o.op & " -> " & act
  check("every action a row names appears in the emulator's source",
        lostActions.len == 0,
        "named by a row and in no arm: " & firstN(lostActions, 8))

  # ------------------------------------------------------------ the buckets
  var shaped = 0
  var empty = 0
  var absent = 0
  var emptyNames: seq[string] = @[]
  var k = 0
  while k < ops.len:
    let b = bucketOf(ops[k], supply.stubbed)
    ops[k].bucket = b
    if b == "shaped": inc shaped
    elif b == "empty":
      inc empty
      emptyNames.add ops[k].callback & "." & ops[k].op
    else: inc absent
    inc k

  heading "The split, derived"
  line "  served and shaped   " & $shaped
  line "  served but empty    " & $empty
  line "  not served          " & $absent
  line "  ----------------------------"
  line "  client-facing       " & $ops.len
  check("the three buckets sum to the operation count",
        shaped + empty + absent == ops.len)
  line "  the empty bucket is " & firstN(emptyNames, 6)

  # ------------------------------------------------------------- the document
  heading "docs/EMULATOR-COVERAGE.md"
  let docPath = joinPath(repo, "docs\\EMULATOR-COVERAGE.md")
  let doc = readOrDie(docPath)
  var next = ""
  if not replaceRegion(doc, BeginBuckets, EndBuckets,
                       bucketsRegion(shaped, empty, absent, ops.len,
                                     methodCount, excluded), next):
    fatal "the buckets markers are not in docs/EMULATOR-COVERAGE.md; add\n" &
          "      " & BeginBuckets & "\n      " & EndBuckets
  var next2 = ""
  if not replaceRegion(next, BeginCommands, EndCommands,
                       commandsRegion(methodCount, actionCount,
                                      supply.routes.len, supply.armLines),
                       next2):
    fatal "the commands markers are not in docs/EMULATOR-COVERAGE.md; add\n" &
          "      " & BeginCommands & "\n      " & EndCommands
  var next3 = ""
  if not replaceRegion(next2, BeginSweeps, EndSweeps,
                       sweepsRegion(actionCount, supply.routes.len,
                                    supply.armLines),
                       next3):
    fatal "the sweeps markers are not in docs/EMULATOR-COVERAGE.md; add\n" &
          "      " & BeginSweeps & "\n      " & EndSweeps

  if checkOnly:
    if next3 == doc:
      check("the generated regions are what the code says they are", true)
    else:
      # Say *what* differs, line by line, rather than "it differs". A stale
      # coverage document is nearly always one number, and printing the pair is
      # the difference between a gate that tells you and one that sends you
      # looking.
      var diffs: seq[string] = @[]
      let onDisk = splitLines(doc)
      let wantLines = splitLines(next3)
      # Capped, and deliberately. A generated table that gains or loses a row
      # shifts every line under it, so an uncapped line-by-line diff prints the
      # whole document and buries the one number that actually moved.
      var p = 0
      var beyond = 0
      while p < onDisk.len and p < wantLines.len:
        if onDisk[p] != wantLines[p]:
          if diffs.len < 8:
            diffs.add "line " & $(p + 1) & "\n        on disk:   " & onDisk[p] &
                      "\n        generated: " & wantLines[p]
          else:
            inc beyond
        inc p
      if beyond > 0:
        diffs.add $beyond & " further line(s) differ, most of them shifted " &
                  "by the lines above rather than changed"
      if onDisk.len != wantLines.len:
        diffs.add "the document is " & $onDisk.len & " lines and the " &
                  "generated one is " & $wantLines.len
      inc gChecks
      inc gFailures
      err "the generated regions are what the code says they are"
      for d in diffs:
        line "      " & d
      line "      run `aowl-coverage` to rewrite them"
  else:
    if next3 == doc:
      check("docs/EMULATOR-COVERAGE.md was already current", true)
    else:
      let r = writeTextFile(docPath, next3)
      check("docs/EMULATOR-COVERAGE.md rewritten", r.ok,
            "the write failed with error " & $r.err)

  heading "Result"
  line "  " & $gChecks & " checks"
  if gWarnings > 0:
    line "  " & $gWarnings & " warning(s)"
  if gFailures > 0:
    err $gFailures & " failed"
    return 1
  ok "the coverage document is derived from the code, and agrees with it"
  result = 0

quit(main())
