#!/usr/bin/env python3
"""fieldrefs.py -- generate `abi/aowlspt_fieldrefs.h` from the IL2CPP metadata.

WHY THIS EXISTS
===============
`docs/WRITE-AUDIT-2026-09-02.md` section 5 and `docs/INTERACTION-LAYER-MAP.md`
M3/M6: every host/mod store into game-owned memory today is handed a BARE
OFFSET, and its only guard is readability -- a test that CANNOT FAIL on the
IL2CPP GC heap, because the pages stay mapped after an object dies.

A bare offset also cannot answer the one question that produced the
`0x00000000FFFFFFFF` crash: *is this slot a REFERENCE?* A 4-byte store of -1
into a reference slot whose upper dword was already zero is producer (A) in
that audit, and nothing in the tree could refuse it.

So the offset stops being an integer literal in Nim and becomes a generated
descriptor:

    (type_name, field_name) -> (offset, width, is_reference, inst_size_min)

emitted as C, consumed by `abi/aowlspt_hostwrite.h`'s `aowl_fr_store_*`.
"Is 0x110 on this object an int or a ToggleGroup?" becomes a build artifact
instead of a comment.

THE SELF-CHECK IS MANDATORY (CLAUDE.md section 5)
=================================================
`tools/fldoff.py:self_check` re-derives `System.String._stringLength@0x10` and
`_firstChar@0x14` before anything is printed. This tool calls the SAME function
and additionally re-derives it as a FieldRef row, so the generated header is
never written from a resolver that failed its own sanity check. Failure prints
only the failure, writes nothing, and exits non-zero.

WHAT `inst_size_min` IS, AND WHAT IT IS NOT
==========================================
The metadata does NOT carry `Il2CppClass.instance_size`; that is built at
runtime. What is derivable offline is `max(offset + width)` over every INSTANCE
field of the type and its bases -- a LOWER BOUND on the real instance size.

That is the fail-closed direction (it can only refuse writes the real size
would have allowed, never allow one it would have refused), and it is stated
here rather than dressed up: for a FieldRef generated by this tool the bound
check is **weak by construction**, because the offset came out of the same
table. It is non-vacuous only against a hand-edited or stale header. The checks
that carry real weight are the REFERENCE-WIDTH rule and the klass-admission
rule; see `abi/aowlspt_hostwrite.h`.

VALUE-TYPE WIDTHS
=================
A primitive's width comes from its `Il2CppTypeEnum`. A VALUETYPE's (Color,
Vector2, an enum) is computed by recursing into ITS declared instance fields
and taking the same max(off+width), capped in depth. Measured on this build:
`UnityEngine.Color` -> 16 (four floats reported at 0x10/0x14/0x18/0x1c,
because a value type's fieldOffsets are OBJECT-HEADER-relative; the header is
subtracted, see `valuetype_size`). A width that cannot
be derived is emitted as 0, and `aowl_fr_store_*` REFUSES a FieldRef of width 0
rather than guessing.

USAGE
=====
    python tools/fieldrefs.py [GAMEASM] [METADEC] emit [--out abi/aowlspt_fieldrefs.h]
    python tools/fieldrefs.py [GAMEASM] [METADEC] print
    python tools/fieldrefs.py [GAMEASM] [METADEC] check   # regenerate + diff, exit 5 on drift

Exit codes: 0 ok, 1 self-check or resolve failure, 5 `check` found drift.
"""

import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.dirname(_HERE)
sys.path.insert(0, _HERE)

from il2cpp_resolve import Resolver          # noqa: E402
import fldoff                                # noqa: E402

OUT_DEFAULT = os.path.join(_REPO, "abi", "aowlspt_fieldrefs.h")

# ---------------------------------------------------------------------------
# THE MANIFEST -- one row per store site named in docs/WRITE-AUDIT-2026-09-02.md
# section 1. A site that is not in this table CANNOT be written through the
# typed helper, which is the point (audit section 5.4).
#
#   (SYMBOL, type name, field name, the audit site it serves)
# ---------------------------------------------------------------------------
MANIFEST = [
    ("BC_MAXBOTS",     "BotSpawner",              "<MaxBots>k__BackingField",
     "audit #1  botcap.nim   BotSpawner.MaxBots := 0"),
    ("BA_ISREADY",     "BotWeaponManager",        "<IsReady>k__BackingField",
     "audit #2  botai.nim    BotWeaponManager.IsReady := true"),
    ("GRAPHIC_COLOR",  "UnityEngine.UI.Graphic",  "m_Color",
     "audit #3  natesp.nim   Graphic.m_Color, four f32 channels (BUILD TIME only)"),
    ("TMP_FONTASSET",  "TMPro.TMP_Text",          "m_fontAsset",
     "audit #4  nativeui.nim TMP_Text.m_fontAsset := donor's font"),
    ("TMP_SHAREDMAT",  "TMPro.TMP_Text",          "m_sharedMaterial",
     "audit #4  nativeui.nim TMP_Text.m_sharedMaterial := donor's material"),
    ("GRAPHIC_MAT",    "UnityEngine.UI.Graphic",  "m_Material",
     "audit #4  nativeui.nim Graphic.m_Material := donor's material"),
    ("TOGGLE_GROUP",   "UnityEngine.UI.Toggle",   "m_Group",
     "audit #5  modstab.nim  -- NOW A CALL: Toggle::SetToggleGroup @0x55BA150"),
    ("TOGGLE_ISON",    "UnityEngine.UI.Toggle",   "m_IsOn",
     "audit #8  settings    -- NOW A CALL: Toggle::SetIsOnWithoutNotify @0x55BA440"),
    ("TMP_MTEXT",      "TMPro.TMP_Text",          "m_text",
     "audit #6/#9 settingswrite/invoke2/version brand: TMP_Text.m_text"),
    ("EB_PATH",        "Diz.Resources.EasyBundle", "_path",
     "audit #11 mods/textures/redirect.nim EasyBundle._path"),
    # --- APPENDED 2026-09-04, dlssrows.nim TOOLTIPS.
    #
    # `SettingsTooltipData` is the TEMPLATE argument of
    # `SettingControl::SetTooltip` @0x16FAC00. MEASURED `disasm 0x16fac00
    # --len 940`: SetTooltip does NOT keep the object it is handed -- it
    # constructs its OWN through `SettingsTooltipData::.ctor(ESettingsOption)`
    # @0x16FCD70 and copies the fields across (`mov rax,[rbp+0x20]` ->
    # `mov [rdi+0x20],rax` is Text). So the six stores below are into an
    # object THIS HOST allocated with `il2cpp_object_new` and which the game
    # has never seen -- but they go through the typed gate anyway, because the
    # klass the allocation was made against is borrowed from a live donor row
    # and "it read back plausibly" is not a fact (hostfieldwrite.nim header).
    #
    # Offsets MEASURED `tools/fldoff.py fields EFT.UI.Settings.SettingsTooltipData`
    # with the System.String self-check passing: Key@0x10 (ESettingsOption, an
    # enum -> 4 bytes, value type), Title@0x18 (string, REFERENCE), Text@0x20
    # (string, REFERENCE), UsageStyle@0x28 (EUsageStyle, 4), UsageProperty@0x2C
    # (EUsageProperty, 4), UsageText@0x30 (string, REFERENCE). Nothing here is
    # a literal in the Nim; the widths and the is-reference bits are derived by
    # this file from the metadata, which is what stops a 4-byte store landing
    # in a reference slot.
    ("TTD_KEY",        "EFT.UI.Settings.SettingsTooltipData", "Key",
     "dlssrows.nim tooltip template: SettingsTooltipData.Key (ESettingsOption)"),
    ("TTD_TITLE",      "EFT.UI.Settings.SettingsTooltipData", "Title",
     "dlssrows.nim tooltip template: SettingsTooltipData.Title (string)"),
    ("TTD_TEXT",       "EFT.UI.Settings.SettingsTooltipData", "Text",
     "dlssrows.nim tooltip template: SettingsTooltipData.Text (string)"),
    ("TTD_USAGESTYLE", "EFT.UI.Settings.SettingsTooltipData", "UsageStyle",
     "dlssrows.nim tooltip template: SettingsTooltipData.UsageStyle (EUsageStyle)"),
    ("TTD_USAGEPROP",  "EFT.UI.Settings.SettingsTooltipData", "UsageProperty",
     "dlssrows.nim tooltip template: SettingsTooltipData.UsageProperty (EUsageProperty)"),
    ("TTD_USAGETEXT",  "EFT.UI.Settings.SettingsTooltipData", "UsageText",
     "dlssrows.nim tooltip template: SettingsTooltipData.UsageText (string)"),
    # --- APPENDED 2026-09-04, mods/fov WRITE-AUDIT #12.
    #
    # This was baselined in tools/storelint.py as "NOT YET ROUTED; the field
    # type is INFERRED in the audit from two agreeing instruments, not from the
    # field table". THAT IS NO LONGER TRUE, and it is the reason the debt could
    # sit: the claim was never re-measured. MEASURED 2026-09-04,
    # `python tools/fldoff.py fields EFT.CameraControl.CameraManager` with the
    # System.String self-check passing:
    #
    #   0xf8  _fov  float  0x0001 private  EFT.CameraControl.CameraManager
    #
    # -- a declared, non-static, 4-byte VALUE field, so the width and the
    # is-reference bit come from the metadata here and are not fov.nim's
    # `OffCamMgrFov = 0xF8` literal restated. The disassembly of
    # `CameraManager::get_Fov` (`movss xmm0,[rcx+0xF8]; ret`) now agrees with a
    # third instrument rather than standing in for the missing one.
    #
    # THE OTHER HALF OF THAT AUDIT SITE HAS NO ROW AND MUST NOT BE GIVEN ONE:
    # `UnityEngine.Camera.fieldOfView` is NOT in fieldOffsets at all (measured
    # the same way -- Camera declares only m_CachedPtr and static literals; the
    # property is native-side, exactly like RectTransform's). There is nothing
    # to generate, and fov.nim already writes it by CALLING
    # `Camera::set_fieldOfView`, which is the correct route for a native
    # property. Inventing an offset for it would be the guess this file exists
    # to prevent.
    ("CM_FOV",         "EFT.CameraControl.CameraManager", "_fov",
     "audit #12 mods/fov/fov.nim CameraManager._fov (float)"),
    # --- APPENDED 2026-09-04, host/Aowlspt.Host.Il2Cpp/nativepostfx.nim
    # rows 2 and 3 (AO intensity / radius / blur iterations).
    #
    # These are the ONE part of the native POSTFX row set that is a STORE
    # rather than a call. Every other row drives the game's own applier
    # (SetSSAO, SetSharpen, TryUpdate*, ChangedShadowQuality), which is always
    # preferable -- but Prism's AO block has no applier: MEASURED
    # `tools/fldoff.py fields PrismEffects`, these are PUBLIC instance fields
    # that the Prism scripts read out of themselves every frame, and BSG's own
    # code sets them by plain assignment. There is no method to call.
    #
    #   0x27c  aoIntensity       float
    #   0x284  aoRadius          float
    #   0x290  aoBlurIterations  int
    #
    # So they go through the typed gate instead, and the gate is doing real
    # work here rather than ceremony. The receiver is reached by WALKING
    # `CameraManager.Instance -> _prismEffects@0xE8`, and that field is TYPED
    # `PrismEffects` while a nearly identical AO block also exists on
    # `PrismSSAO` at completely different offsets (`aoIntensity@0xA4`,
    # `aoRadius@0xAC`, `aoBlurIterations@0xB8` -- also measured). Writing
    # 0x27C on a PrismSSAO receiver would land in the middle of an unrelated
    # field and read back plausibly. `aowl_fr_recvok`'s klass admission is what
    # refuses that, and it is the reason these three are rows here rather than
    # three integer literals in the Nim.
    #
    # The widths and is-reference bits below are DERIVED by this file from the
    # metadata -- not restated from the offsets above -- which is what stops a
    # 4-byte store landing in a reference slot.
    ("PE_AO_INTENSITY", "PrismEffects", "aoIntensity",
     "nativepostfx.nim row 2: PrismEffects.aoIntensity (float)"),
    ("PE_AO_RADIUS",    "PrismEffects", "aoRadius",
     "nativepostfx.nim row 2: PrismEffects.aoRadius (float)"),
    ("PE_AO_BLURITER",  "PrismEffects", "aoBlurIterations",
     "nativepostfx.nim row 3: PrismEffects.aoBlurIterations (int)"),
]

# ---------------------------------------------------------------------------
# Il2CppTypeEnum -> (width, is_reference). Only the cases that can appear as a
# field type. Anything absent is answered UNKNOWN (0, ...) and refused, never
# guessed.
# ---------------------------------------------------------------------------
PRIM = {
    0x02: (1, 0),   # BOOLEAN
    0x03: (2, 0),   # CHAR
    0x04: (1, 0),   # I1
    0x05: (1, 0),   # U1
    0x06: (2, 0),   # I2
    0x07: (2, 0),   # U2
    0x08: (4, 0),   # I4
    0x09: (4, 0),   # U4
    0x0a: (8, 0),   # I8
    0x0b: (8, 0),   # U8
    0x0c: (4, 0),   # R4
    0x0d: (8, 0),   # R8
    0x18: (8, 0),   # I   (IntPtr)
    0x19: (8, 0),   # U   (UIntPtr)
}
REF = {
    0x0e: 8,        # STRING
    0x0f: 8,        # PTR
    0x12: 8,        # CLASS
    0x13: 8,        # VAR
    0x14: 8,        # ARRAY
    0x15: 8,        # GENERICINST -- see note in type_info()
    0x1c: 8,        # OBJECT
    0x1d: 8,        # SZARRAY
    0x1e: 8,        # MVAR
}
TE_VALUETYPE = 0x11


def type_byte(R, tidx):
    """The Il2CppTypeEnum of the Il2CppType at index `tidx`.

    Il2CppType is `{ union data; unsigned attrs:16, type:8, num_mods:6,
    byref:1, pinned:1 }`. `Resolver.field_attrs` already masks 0xFFFF out of
    the u32 at +8; the type byte is the next 8 bits of that same word."""
    tva = R.rq(R.TYPES_PTR + tidx * 8)
    import struct
    w = struct.unpack_from("<I", R.b, R.v2f(tva) + 8)[0]
    return (w >> 16) & 0xFF


def _decl_rows(R, tname):
    t = R.find_one(tname)
    return t, R.all_fields_ex(t)


def valuetype_size(R, tidx, depth=0):
    """Size of a VALUETYPE field, from its own declared instance fields.

    A GENERICINST valuetype has an all-zero fieldOffsets array (the
    GENERIC-NO-LAYOUT case) and is answered 0 = UNKNOWN, never 0 = empty."""
    if depth > 3:
        return 0
    tva = R.rq(R.TYPES_PTR + tidx * 8)
    import struct
    td = struct.unpack_from("<q", R.b, R.v2f(tva))[0]
    # For a VALUETYPE the `data` union holds the typeDefinitionIndex.
    if td < 0 or td >= R.NTYPES:
        return 0
    try:
        rows = R.declared_fields_ex(td)
    except Exception:
        return 0
    if not rows:
        return 0
    end = 0
    for r in rows:
        if r["static"] or not r["has_storage"]:
            continue
        if r["layout"] == "generic" or r["off"] is None:
            return 0
        w, _ref, _lbl = _width_of(R, r["fidx"], depth + 1)
        if w == 0:
            return 0
        end = max(end, r["off"] + w)
    # MEASURED on this build: a VALUE TYPE's own fieldOffsets entries are
    # OBJECT-HEADER-RELATIVE, not struct-relative -- UnityEngine.Color reports
    # r/g/b/a at 0x10/0x14/0x18/0x1c and UnityEngine.Vector2 reports x/y at
    # 0x10/0x14 (`python tools/fldoff.py fields UnityEngine.Color`). The struct
    # is therefore `end - sizeof(Il2CppObject)`; without this subtraction Color
    # comes back 32 bytes, i.e. DOUBLE, which as a store width would run 16
    # bytes past the field. Anything that does not clear the header is answered
    # UNKNOWN rather than a negative or a guess.
    if end <= 0x10:
        return 0
    return end - 0x10


def _fidx_typeindex(R, fidx):
    import struct
    _ni, ti = struct.unpack_from("<ii", R.m, R.FLD_OFF + fidx * 12)
    return ti


def _width_of(R, fidx, depth=0):
    """-> (width, is_reference, kind_label). width 0 means UNKNOWN."""
    ti = _fidx_typeindex(R, fidx)
    tb = type_byte(R, ti)
    if tb in REF:
        # GENERICINST is a reference ONLY when the open definition is a class.
        # We do not have a cheap offline answer for that, so a GENERICINST
        # field is emitted UNKNOWN rather than assumed. No manifest row needs
        # one today; if one does, measure it and add an explicit override.
        if tb == 0x15:
            return (0, 0, "genericinst(UNKNOWN)")
        return (REF[tb], 1, "reference")
    if tb in PRIM:
        w, r = PRIM[tb]
        return (w, r, "primitive")
    if tb == TE_VALUETYPE:
        return (valuetype_size(R, ti, depth), 0, "valuetype")
    return (0, 0, "unknown(0x%02x)" % tb)


def inst_size_min(R, rows):
    """max(off + width) over every INSTANCE field of the type and its bases.

    A LOWER BOUND on Il2CppClass.instance_size -- see the module docstring for
    exactly how weak that is. A field whose width is unknown is SKIPPED, which
    can only make the bound smaller, i.e. refuse more."""
    end = 0
    for r in rows:
        if r["static"] or not r["has_storage"] or r["off"] is None:
            continue
        if r["layout"] == "generic":
            continue
        w, _ref, _k = _width_of(R, r["fidx"])
        if w == 0:
            continue
        end = max(end, r["off"] + w)
    return end


def fieldref_self_check(R):
    """The second self-check, on THIS tool's own additions.

    `fldoff.self_check` proves the OFFSET scan. It says nothing about the
    width/is_reference decoder added here, which is where a silent lie would
    now live. So re-derive three rows whose answers are known independently:

        System.String._stringLength  0x10  width 4  reference 0
        System.String._firstChar     0x14  width 2  reference 0
        UnityEngine.UI.Toggle.m_Group 0x110 width 8 reference 1

    The last one is the falsifier that matters: if `type_byte` were wrong, a
    CLASS field would decode as a primitive and M4 (no narrow store into a
    reference slot) would silently stop applying to every reference in the
    table."""
    want = [("System.String", "_stringLength", 0x10, 4, 0),
            ("System.String", "_firstChar", 0x14, 2, 0),
            ("UnityEngine.UI.Toggle", "m_Group", 0x110, 8, 1)]
    bad = []
    for tname, fname, off, wid, ref in want:
        try:
            _t, rows = _decl_rows(R, tname)
            r = [x for x in rows if x["name"] == fname and not x["static"]][0]
            gw, gref, _k = _width_of(R, r["fidx"])
            got = (r["off"], gw, gref)
        except Exception as e:                       # noqa: BLE001
            got = ("error", str(e), "")
        if got != (off, wid, ref):
            bad.append((tname + "." + fname, got, (off, wid, ref)))
    if bad:
        print("FIELDREF SELF-CHECK FAILED: the width/is_reference decoder does "
              "not reproduce known rows -- refusing to emit any FieldRef.")
        for lbl, got, exp in bad:
            print("   %-34s got=%r exp=%r" % (lbl, got, exp))
        sys.exit(1)


def build(R):
    """-> list of dicts, one per manifest row. Raises SystemExit on any row
    that cannot be resolved to a real offset -- a header with a hole in it is
    worse than no header."""
    out = []
    for sym, tname, fname, note in MANIFEST:
        t, rows = _decl_rows(R, tname)
        hit = [r for r in rows if r["name"] == fname]
        if not hit:
            sys.exit("FIELDREFS FAILED: %s.%s does not exist on this build "
                     "(searched the full parent chain of %s)" %
                     (tname, fname, tname))
        r = hit[0]
        if r["static"]:
            sys.exit("FIELDREFS FAILED: %s.%s is STATIC -- it is not an "
                     "instance field and has no receiver-relative offset" %
                     (tname, fname))
        if not r["has_storage"]:
            sys.exit("FIELDREFS FAILED: %s.%s is a LITERAL (C# const): it has "
                     "no storage, and 0x0 is not its offset" % (tname, fname))
        if r["layout"] == "generic":
            sys.exit("FIELDREFS FAILED: %s is an UNINSTANTIATED GENERIC "
                     "definition; IL2CPP writes an all-zero fieldOffsets array "
                     "for it, so every offset it reports is fabricated" % tname)
        if r["off"] is None:
            sys.exit("FIELDREFS FAILED: %s.%s has no fieldOffsets entry" %
                     (tname, fname))
        w, isref, kind = _width_of(R, r["fidx"])
        if w == 0:
            sys.exit("FIELDREFS FAILED: %s.%s has type %r whose width is not "
                     "derivable offline (%s) -- refusing to guess it" %
                     (tname, fname, r["typename"], kind))
        ns, nm = R.tname(t)
        full = (ns + "." + nm) if ns else nm
        out.append({
            "sym": sym, "type": full, "field": fname, "off": r["off"],
            "width": w, "isref": isref, "instmin": inst_size_min(R, rows),
            "typename": r["typename"], "kind": kind,
            "declared_by": r.get("declared_by", full), "note": note,
        })
    return out


HDR = """/* abi/aowlspt_fieldrefs.h -- GENERATED by tools/fieldrefs.py. DO NOT EDIT.
 *
 * Regenerate:  python tools/fieldrefs.py emit
 * Verify:      python tools/fieldrefs.py check     (exit 5 = drift)
 *
 * Every row was produced by tools/il2cpp_resolve.py's fieldOffsets scan, AFTER
 * tools/fldoff.py:self_check re-derived System.String._stringLength@0x10 and
 * _firstChar@0x14 from the same resolver. No offset in this file was typed by
 * a human.
 *
 * `inst_size_min` is max(offset+width) over the type's instance fields and its
 * bases -- a LOWER BOUND on Il2CppClass.instance_size, which the metadata does
 * not carry. It is the fail-closed direction, and it is weak by construction
 * for the offsets in this very file. The load-bearing checks are the
 * reference-width rule (M4) and klass admission; see aowlspt_hostwrite.h.
 *
 * `klass` / `nklass` are the runtime KLASS ADMISSION SET, filled in by
 * aowl_fr_admit() from receivers the caller vouches for. Zero admitted klasses
 * means every store through this FieldRef is REFUSED.
 */
#ifndef AOWLSPT_FIELDREFS_H
#define AOWLSPT_FIELDREFS_H

#include <stdint.h>

#define AOWL_FR_MAX_KLASS 4

typedef struct AowlFieldRef {
    const char* type_name;      /* metadata type that DECLARES the field      */
    const char* field_name;
    int32_t     off;            /* receiver-relative, from fieldOffsets       */
    int32_t     width;          /* bytes; 0 is impossible here (generator     */
                                /* refuses a width it cannot derive)          */
    int32_t     is_reference;   /* 1 => a managed reference slot (M4 applies) */
    uint32_t    inst_size_min;  /* see the note above                         */
    void*       klass[AOWL_FR_MAX_KLASS];
    int32_t     nklass;
} AowlFieldRef;

"""

FTR = """
#endif /* AOWLSPT_FIELDREFS_H */
"""


def emit(refs, build_id=""):
    b = [HDR]
    if build_id:
        b.append("/* source: %s */\n\n" % build_id)
    for r in refs:
        b.append("/* %s\n"
                 " *   %s.%s : %s   (%s, declared by %s)\n"
                 " */\n" % (r["note"], r["type"], r["field"], r["typename"],
                            r["kind"], r["declared_by"]))
        b.append("static AowlFieldRef AOWL_FR_%s = {\n"
                 "    \"%s\", \"%s\", 0x%x, %d, %d, 0x%x, { 0, 0, 0, 0 }, 0\n"
                 "};\n\n" % (r["sym"], r["type"], r["field"], r["off"],
                             r["width"], r["isref"], r["instmin"]))
    # One accessor per row. Nim binds THESE, never the objects: `importc` on a
    # proc emits a CALL, so `(&AOWL_FR_X)` as a proc name compiles to
    # `(&AOWL_FR_X)()` -- "called object is not a function or function
    # pointer". Going through a real function also keeps `AowlFieldRef`'s
    # layout entirely on the C side, so Nim cannot be made to disagree with it.
    b.append("\n")
    for r in refs:
        b.append("static AowlFieldRef* aowl_fr_%s(void) { return &AOWL_FR_%s; }\n"
                 % (r["sym"].lower(), r["sym"]))
    b.append("\n")
    # The whole table, for the inspector's ADVISORY lookup. Nothing writes
    # through this array: it exists so a deliberately RAW write can be TOLD
    # what the metadata thinks of the address it is about to touch.
    b.append("static AowlFieldRef* AOWL_FR_ALL[] = {\n")
    for r in refs:
        b.append("    &AOWL_FR_%s,\n" % r["sym"])
    b.append("};\n")
    b.append("#define AOWL_FR_TABLE_ROWS %d\n" % len(refs))
    b.append(FTR)
    return "".join(b)


def main():
    argv = sys.argv[1:]
    gameasm, metadec, args = fldoff.resolve_args() if False else (None, None, None)
    # fldoff.resolve_args reads its own globals; do the same two-positional
    # parse here rather than importing its module state.
    pos = [a for a in argv if not a.startswith("--")]
    gameasm = fldoff.DEFAULT_GAMEASM
    metadec = fldoff.DEFAULT_METADEC
    while pos and (pos[0].lower().endswith(".dll") or pos[0].lower().endswith(".dat")):
        if pos[0].lower().endswith(".dll"):
            gameasm = pos.pop(0)
        else:
            metadec = pos.pop(0)
    cmd = pos[0] if pos else "print"
    out = OUT_DEFAULT
    if "--out" in argv:
        out = argv[argv.index("--out") + 1]

    R = Resolver(gameasm, metadec)
    fldoff.self_check(R)          # MANDATORY, before any offset is used
    fieldref_self_check(R)        # and on this tool's own width/ref decoder

    refs = build(R)
    text = emit(refs, os.path.basename(gameasm))

    if cmd == "print":
        for r in refs:
            print("%-14s %-28s %-26s off=0x%-4x w=%-2d ref=%d instmin=0x%x" %
                  (r["sym"], r["type"], r["field"], r["off"], r["width"],
                   r["isref"], r["instmin"]))
        return 0
    if cmd == "emit":
        with open(out, "w", newline="\n") as f:
            f.write(text)
        print("wrote %s (%d rows, %d bytes)" % (out, len(refs), len(text)))
        return 0
    if cmd == "check":
        if not os.path.exists(out):
            print("DRIFT: %s does not exist" % out)
            return 5
        with open(out, "r", newline="") as f:
            have = f.read().replace("\r\n", "\n")
        if have != text:
            print("DRIFT: %s does not match what the metadata says. "
                  "Run `python tools/fieldrefs.py emit`." % out)
            return 5
        print("fieldrefs: %s matches the metadata (%d rows)" % (out, len(refs)))
        return 0
    print(__doc__)
    return 1


if __name__ == "__main__":
    sys.exit(main())
