#!/usr/bin/env python3
"""Generate mods/tarkov/emu/lootcats.nim from the real database.

The category axis of the loot/bot weighting system is NOT a hand-written list.
Hand-written lists were how the previous five-slider version shipped an id
(57864ee62459775490116fbf) that resolves to nothing in this install -- a knob
that reweights an empty set and reports success.

Two axes are emitted, both derived:

  * HANDBOOK categories -- `templates.handbook.Categories`, the tree the client
    itself groups items by, with the parent chain flattened so a rule on a
    top-level node covers its children.
  * BASE CLASSES -- every distinct `_parent` seen on `templates.items`, which is
    the axis `templates.items.<id>._parent` walking already uses.

Names come from `locale_en.json` where it has one, and from `_name` otherwise;
a category with neither is emitted with its id as the name rather than dropped,
because dropping it would silently shrink the knob surface.

Usage:  python tools/gen_lootcats.py <db.json> <locale_en.json> <out.nim>
"""
import json
import sys
import collections


def main():
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    dbp, locp, outp = sys.argv[1:4]

    with open(dbp, "r", encoding="utf-8") as f:
        db = json.load(f)
    try:
        with open(locp, "r", encoding="utf-8") as f:
            loc = json.load(f)
    except Exception:
        loc = {}

    items = db.get("templates", {}).get("items", {})
    hb = db.get("templates", {}).get("handbook", {})
    cats = hb.get("Categories", [])
    hbitems = hb.get("Items", [])

    # --- base classes: every distinct _parent, with how many items it covers
    # directly.  Coverage is emitted so a rule can never be a knob over zero
    # items without that being visible in the generated file.
    direct = collections.Counter()
    parent_of = {}
    name_of = {}
    for tid, t in items.items():
        p = t.get("_parent", "")
        parent_of[tid] = p
        name_of[tid] = t.get("_name", "")
        if p:
            direct[p] += 1

    # transitive coverage: an item counts for every id on its parent chain.
    total = collections.Counter()
    for tid in items:
        cur = parent_of.get(tid, "")
        hops = 0
        seen = set()
        while cur and hops < 24 and cur not in seen:
            total[cur] += 1
            seen.add(cur)
            cur = parent_of.get(cur, "")
            hops += 1

    # A base class is an id that is somebody's _parent.  Keep only those with
    # transitive coverage > 0 -- by construction all of them, but the filter is
    # what makes "this knob touches nothing" unrepresentable rather than
    # merely unlikely.
    bases = []
    for bid in sorted(direct, key=lambda b: (-total[b], b)):
        if total[bid] <= 0:
            continue
        bases.append((bid, name_of.get(bid, "") or bid, total[bid]))

    # --- handbook categories, with item counts through the handbook index
    cat_parent = {c["Id"]: c.get("ParentId") or "" for c in cats}
    cat_items = collections.Counter()
    for e in hbitems:
        cid = e.get("ParentId") or ""
        hops = 0
        seen = set()
        while cid and hops < 12 and cid not in seen:
            cat_items[cid] += 1
            seen.add(cid)
            cid = cat_parent.get(cid, "")
            hops += 1

    def cat_name(cid):
        for k in (cid, cid + " Name"):
            v = loc.get(k)
            if isinstance(v, str) and v.strip():
                return v.strip()
        return cid

    catrows = []
    for c in cats:
        cid = c["Id"]
        catrows.append((cid, cat_name(cid), cat_parent.get(cid, ""),
                        cat_items.get(cid, 0)))
    catrows.sort(key=lambda r: (-r[3], r[0]))

    def slug(s):
        out = []
        up = True
        for ch in s:
            if ch.isalnum():
                out.append(ch.upper() if up else ch)
                up = False
            else:
                up = True
        t = "".join(out)
        return t if t and not t[0].isdigit() else "C" + t

    used = set()

    def uniq(base):
        k = base
        n = 2
        while k in used:
            k = base + str(n)
            n += 1
        used.add(k)
        return k

    L = []
    A = L.append
    A("## GENERATED by tools/gen_lootcats.py -- do not edit by hand.")
    A("##")
    A("## The category axis of the loot weighting system, derived from this")
    A("## install's own database rather than from a community id list. Each row")
    A("## carries the number of item templates the id ACTUALLY covers, so a knob")
    A("## over an empty set is visible in the table instead of being discovered")
    A("## when someone reports that a slider does nothing.")
    A("##")
    A("## Regenerate:")
    A("##   python tools/gen_lootcats.py <db.json> <locale_en.json> \\")
    A("##     mods/tarkov/emu/lootcats.nim")
    A("")
    A("type")
    A("  CatRow* = object")
    A("    key*: string      ## the settings key, `lootCat<Slug>`")
    A("    id*: string       ## the template/base-class or handbook category id")
    A("    label*: string    ## human name, for the settings page")
    A("    covers*: int      ## item templates reachable from this id")
    A("")
    A("const")
    A("  BaseClassRows*: array[%d, CatRow] = [" % len(bases))
    for i, (bid, nm, cov) in enumerate(bases):
        key = uniq("lootCat" + slug(nm))
        A('    CatRow(key: %s, id: %s, label: %s, covers: %d)%s'
          % (json.dumps(key), json.dumps(bid), json.dumps(nm), cov,
             "," if i + 1 < len(bases) else ""))
    A("  ]")
    A("")
    used.clear()
    A("  HandbookRows*: array[%d, CatRow] = [" % len(catrows))
    for i, (cid, nm, par, cov) in enumerate(catrows):
        key = uniq("lootHb" + slug(nm))
        A('    CatRow(key: %s, id: %s, label: %s, covers: %d)%s'
          % (json.dumps(key), json.dumps(cid), json.dumps(nm), cov,
             "," if i + 1 < len(catrows) else ""))
    A("  ]")
    A("")
    A("  HandbookParent*: array[%d, string] = [" % len(catrows))
    for i, (cid, nm, par, cov) in enumerate(catrows):
        A('    %s%s' % (json.dumps(par), "," if i + 1 < len(catrows) else ""))
    A("  ]")
    A("")

    with open(outp, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(L))

    sys.stderr.write(
        "gen_lootcats: %d base classes, %d handbook categories\n"
        % (len(bases), len(catrows)))
    sys.stderr.write(
        "gen_lootcats: base-class coverage max=%d min=%d\n"
        % (bases[0][2] if bases else 0, bases[-1][2] if bases else 0))


if __name__ == "__main__":
    main()
