#!/usr/bin/env python3
"""Embed reference/spt-config-settings.json into a nimony data module.

nimony has no compile-time file read (`staticRead`/`slurp` are runtime only),
so the settings-hub mod cannot read the SPT surface at build time the classic
way. Instead this emits the surface as escaped string chunks in
`mods/settingshub/sptsurface.nim`, which the mod compiles in and reassembles
once at load. Regenerate whenever tools/genspt_settings.py changes the surface.
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "reference", "spt-config-settings.json")
OUT = os.path.join(ROOT, "mods", "settingshub", "sptsurface.nim")
CH = 3000

BACKSLASH = chr(92)
QUOTE = chr(34)


def esc(s):
    out = []
    for ch in s:
        o = ord(ch)
        if ch == BACKSLASH:
            out.append(BACKSLASH + BACKSLASH)
        elif ch == QUOTE:
            out.append(BACKSLASH + QUOTE)
        elif ch == "\n":
            out.append(BACKSLASH + "n")
        elif ch == "\r":
            out.append(BACKSLASH + "r")
        elif ch == "\t":
            out.append(BACKSLASH + "t")
        elif o < 32 or o > 126:
            out.append(BACKSLASH + "x%02x" % o)
        else:
            out.append(ch)
    return "".join(out)


def main():
    with open(SRC, "r", encoding="utf-8") as f:
        data = json.load(f)
    compact = json.dumps(data, separators=(",", ":"), ensure_ascii=True)
    chunks = [compact[i:i + CH] for i in range(0, len(compact), CH)]
    lines = []
    lines.append("## GENERATED by tools/gen_sptsurface.py from "
                 "reference/spt-config-settings.json.")
    lines.append("## The full SPT server config surface, embedded as string "
                 "chunks so the")
    lines.append("## settings-hub mod carries it with no runtime file. Do not "
                 "edit by hand;")
    lines.append("## regenerate after tools/genspt_settings.py changes the "
                 "surface.")
    lines.append("")
    lines.append("const sptSurfaceChunks*: array[%d, string] = [" % len(chunks))
    for c in chunks:
        lines.append('  "%s",' % esc(c))
    lines.append("]")
    lines.append("")
    lines.append("proc sptSurfaceText*(): string =")
    lines.append("  ## The whole surface, reassembled once at load.")
    lines.append('  result = ""')
    lines.append("  for c in sptSurfaceChunks: result.add c")
    lines.append("")
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print("wrote %s: %d chunks, %d chars" % (OUT, len(chunks), len(compact)))


if __name__ == "__main__":
    main()
