"""Slice the F12 optimistic-display code out of abi/aowlspt_overlay.h.

Same contract as `gen_test_settings_ack.py`, and for the same reason: the
harness must exercise the SHIPPING functions, not a copy of them that can
drift. Every region is copied verbatim between two anchors and the script
refuses to write a partial header if an anchor has moved -- a smaller header
would still compile and would silently test less, which is the failure mode
this whole family of tools exists to prevent.

Run from the repo root:  python tools\\gen_test_settings_display.py
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "abi", "aowlspt_overlay.h")
OUT = os.path.join(ROOT, "tools", "test_settings_display.gen.h")

# (name, first line of the region, first line AFTER the region)
REGIONS = [
    ("the string formatter",
     "static void aowl_ov_fmt(char* out, int32_t cap, const char* fmt, ...) {",
     "static void aowl_ov_copy(char* dst, int32_t cap, const char* src) {"),
    ("the JSON reader",
     "static const char* aowl_ov_jws(const char* p, const char* e) {",
     "static void aowl_ov_jput(const char* o, const char* e, const char* key,"),
    ("the displayed-value derivation and the optimistic edit",
     "/* `value` (what the row prints) derived from `raw` (the JSON literal it",
     "/* One control object into one slot. Returns 1 on a usable row. */"),
    ("the write-acknowledgement verdict",
     "/* HOW LONG TO WAIT BEFORE CALLING A WRITE LOST -- AND WHY A CLOCK CANNOT",
     "static void aowl_ov_settings_set(const AowlOvCmd* cmd, char* buf, int32_t cap) {"),
]


def main():
    text = io.open(SRC, encoding="utf8").read()
    lines = text.split("\n")
    idx = {}
    for n, line in enumerate(lines):
        idx.setdefault(line.rstrip("\r"), n)

    out = ["/* GENERATED by tools/gen_test_settings_display.py -- do not edit.",
           " * Verbatim slices of abi/aowlspt_overlay.h. */"]
    bad = 0
    for name, start, stop in REGIONS:
        if start not in idx or stop not in idx:
            sys.stderr.write("anchor moved for %s:\n  %s\n  %s\n"
                             % (name, start if start in idx else "MISSING " + start,
                                stop if stop in idx else "MISSING " + stop))
            bad += 1
            continue
        a, b = idx[start], idx[stop]
        if b <= a:
            sys.stderr.write("region %s is inverted (%d..%d)\n" % (name, a, b))
            bad += 1
            continue
        out.append("")
        out.append("/* ---- %s (aowlspt_overlay.h:%d-%d) ---- */" % (name, a + 1, b))
        out.extend(l.rstrip("\r") for l in lines[a:b])
    if bad:
        sys.stderr.write("REFUSING to write a partial harness header.\n")
        return 2
    io.open(OUT, "w", encoding="utf8", newline="\n").write("\n".join(out) + "\n")
    print("wrote %s (%d lines)" % (OUT, len(out)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
