#!/usr/bin/env python3
"""gen_keycodes.py -- generate the KeyCode ordinal -> name table for the host.

WHY THIS EXISTS AND WHY IT IS GENERATED. A mod keybind arrives from
`/aowlspt/keybinds` as either a KeyCode NAME ("M") or a bare ORDINAL ("114").
Rendering "114" to a player is useless, and hand-copying a 328-member table is
a transcription with no check on it.

So the table is derived from the SAME `global-metadata` the running client
uses: `UnityEngine.KeyCode` is an enum, and its members are LITERAL fields with
their ordinal as the constant. If the game's enum ever changes, regenerating
tracks it; a hand-written copy would silently drift.

Usage:
    python tools/gen_keycodes.py <GameAssembly.dll> <global-metadata.dec.dat> \
        > host/Aowlspt.Host.Il2Cpp/keycodes.nim
"""
import re
import subprocess
import sys
import os


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        return 3
    here = os.path.dirname(os.path.abspath(__file__))
    out = subprocess.run(
        [sys.executable, os.path.join(here, "fldoff.py"),
         sys.argv[1], sys.argv[2], "fields", "UnityEngine.KeyCode"],
        capture_output=True, text=True, timeout=180)
    if out.returncode != 0:
        sys.stderr.write("fldoff failed: %s\n" % (out.stderr or "")[:300])
        return 3
    pairs = []
    seen = set()
    pat = re.compile(r"^\s*--\s+(\w+)\s+KeyCode\s+\S+\s+\S*LITERAL\S*\s+(-?\d+)\s")
    for line in out.stdout.splitlines():
        m = pat.match(line)
        if not m:
            continue
        name, val = m.group(1), int(m.group(2))
        # FIRST NAME WINS. Unity aliases several ordinals (e.g. Return/KeypadEnter
        # differ, but some platform names collide); taking the first keeps the
        # table deterministic instead of order-dependent on a dict.
        if val in seen:
            continue
        seen.add(val)
        pairs.append((val, name))
    if len(pairs) < 100:
        sys.stderr.write("only %d KeyCode member(s) parsed -- refusing to write "
                         "a table that is obviously short\n" % len(pairs))
        return 1
    pairs.sort()
    w = sys.stdout.write
    w("## keycodes.nim -- GENERATED by tools/gen_keycodes.py. Do not edit.\n")
    w("##\n")
    w("## `UnityEngine.KeyCode` ordinal -> name, read out of the SAME\n")
    w("## global-metadata the running client uses. %d member(s).\n" % len(pairs))
    w("##\n")
    w("## A mod keybind arrives as a NAME ('M') or a bare ORDINAL ('114');\n")
    w("## showing a player '114' is useless. Generated rather than transcribed\n")
    w("## so it cannot silently drift from the game's own enum.\n")
    w("\n")
    w("const NtKeyCodeNames: array[%d, (int32, string)] = [\n" % len(pairs))
    for val, name in pairs:
        w("  (%d'i32, \"%s\"),\n" % (val, name))
    w("]\n")
    w("\n")
    w("proc ntKeyCodeName*(v: int32): string =\n")
    w("  ## The name for an ordinal, or \"\" when it is not a KeyCode this build\n")
    w("  ## declares. Empty is deliberate: the caller shows `KeyCode <n>` so an\n")
    w("  ## unknown ordinal reads as an unknown ordinal, not as a wrong key.\n")
    w("  result = \"\"\n")
    w("  var i = 0\n")
    w("  while i < NtKeyCodeNames.len:\n")
    w("    if NtKeyCodeNames[i][0] == v:\n")
    w("      return NtKeyCodeNames[i][1]\n")
    w("    i = i + 1\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
