#!/usr/bin/env python3
"""gendocs.py -- generate the aowlspt reference pages from source.

The reference section of the docs site is GENERATED, never hand-written, because
hand-written reference prose drifts and this project has already paid for that
(docs/SAIN_RVA.md still asserts a blocker that was fixed weeks ago).

Every fact this emits is extracted from a file in this repo and is printed with
the file:line it came from, so a reader can check it and a future agent can see
immediately when it is stale.

Where a fact CANNOT be extracted mechanically, this tool writes UNKNOWN. It never
writes a plausible sentence in place of a measurement.

Usage:
    python tools/gendocs.py --out ../aoughwl-aoughwl.github.io/docs/aowlspt/reference
    python tools/gendocs.py --check      # non-zero exit if output would change

Inputs (all relative to the repo root):
    abi/aowlspt_*.h              the host C ABI, one header per subsystem
    host/Aowlspt.Host.Il2Cpp/*.nim   the readBoolKey/readIntKey/readStrKey call sites
    mods/*/config.json           each mod's settings, with its own doc comments
"""

import argparse
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

GENERATED_BANNER = (
    "<!-- GENERATED by tools/gendocs.py in the aowlspt repo. DO NOT EDIT BY HAND. -->\n"
    "<!-- Re-run: python tools/gendocs.py --out <site>/docs/aowlspt/reference -->\n"
)


def rel(p):
    return os.path.relpath(p, ROOT).replace("\\", "/")


def read(p):
    with open(p, "r", encoding="utf-8", errors="replace") as f:
        return f.read()


# --------------------------------------------------------------------------
# Host config flags
# --------------------------------------------------------------------------

# Matched against the host sources. Each reader has a different default rule,
# and conflating them is a known defect in tools/hostcfg.py: it assumes every
# flag defaults off, so it misreports every readBoolKeyDef flag.
FLAG_PATTERNS = [
    ("bool", "off", re.compile(r'readBoolKey\(\s*"([A-Za-z0-9_]+)"\s*\)')),
    ("bool", None, re.compile(
        r'readBoolKeyDef\(\s*"([A-Za-z0-9_]+)"\s*,\s*(true|false)\s*\)')),
    ("int", None, re.compile(
        r'readIntKey\(\s*"([A-Za-z0-9_]+)"\s*,\s*([-0-9]+)\s*\)')),
    ("string", '""', re.compile(r'readStrKey\(\s*"([A-Za-z0-9_]+)"\s*\)')),
]


def collect_flags():
    """Every host config key, from its READ SITE -- not from a key table.

    A key table is a second copy of a decision and goes stale; the call site is
    the thing the host actually executes.
    """
    found = {}
    hostdir = os.path.join(ROOT, "host")
    for dirpath, _, names in os.walk(hostdir):
        for n in sorted(names):
            if not n.endswith(".nim"):
                continue
            path = os.path.join(dirpath, n)
            for lineno, line in enumerate(read(path).splitlines(), 1):
                for kind, fixed_default, pat in FLAG_PATTERNS:
                    for m in pat.finditer(line):
                        key = m.group(1)
                        default = fixed_default
                        if default is None:
                            default = m.group(2)
                        entry = found.setdefault(key, {
                            "key": key, "kind": kind,
                            "default": default, "sites": [],
                        })
                        entry["sites"].append("%s:%d" % (rel(path), lineno))
    return found


def load_live_config():
    """The deployed aowlspt-host.json, if this machine has one.

    Used ONLY to cross-check: a key present in the JSON but read nowhere is
    inert, and a key read by the host but absent from the JSON falls back to its
    default. Neither is an error; both are worth showing.
    """
    for cand in (
        r"D:\Aowlspt\aowlspt\aowlspt-host.json",
        os.path.join(ROOT, "aowlspt-host.json"),
    ):
        if os.path.exists(cand):
            try:
                raw = json.loads(read(cand))
            except Exception:
                return None, cand, "present but did not parse as JSON"
            return raw, cand, None
    return None, None, "not found on this machine"


def page_flags():
    flags = collect_flags()
    live, live_path, live_err = load_live_config()

    out = [GENERATED_BANNER, "# Host configuration flags\n"]
    out.append(
        "Every key the host reads out of `aowlspt-host.json`, extracted from the\n"
        "`readBoolKey` / `readBoolKeyDef` / `readIntKey` / `readStrKey` **call sites**\n"
        "in `host/`. The call site is the only source of truth: it is what the host\n"
        "actually executes.\n")
    out.append(
        "::: warning `tools/hostcfg.py keys` is NOT a source of truth\n"
        "It carries a separate, stale key table and reports keys the host demonstrably\n"
        "reads as *\"silently ignored; typo?\"*. It also assumes every flag defaults\n"
        "off, so it misreports every `readBoolKeyDef` flag (`forceOfflinePractice`,\n"
        "for one, defaults **on**). This page is generated from the call sites instead.\n"
        ":::\n")

    counts = {}
    for f in flags.values():
        counts[f["kind"]] = counts.get(f["kind"], 0) + 1
    out.append("**%d keys total** — %s.\n" % (
        len(flags),
        ", ".join("%d %s" % (v, k) for k, v in sorted(counts.items()))))

    out.append("\n## Every key\n")
    out.append("| Key | Type | Default | Live value | Read at |")
    out.append("| --- | --- | --- | --- | --- |")
    for key in sorted(flags):
        f = flags[key]
        if live is None:
            livecell = "_UNKNOWN_"
        elif key in live:
            livecell = "`%s`" % json.dumps(live[key])
        else:
            livecell = "_(absent — falls back to the default)_"
        sites = "<br>".join("`%s`" % s for s in f["sites"])
        out.append("| `%s` | %s | `%s` | %s | %s |" % (
            key, f["kind"], f["default"], livecell, sites))

    out.append("\n## Cross-check against the deployed config\n")
    if live is None:
        out.append(
            "No `aowlspt-host.json` was readable when this page was generated "
            "(%s), so the live-value column is UNKNOWN throughout.\n" % live_err)
    else:
        out.append("Read from `%s`.\n" % live_path.replace("\\", "/"))
        inert = [k for k in live
                 if k not in flags and not k.startswith("//") and k != "//"]
        if inert:
            out.append(
                "\n### Keys in the file that no host source reads\n\n"
                "These are inert. They are not errors — a key may be read by a mod, "
                "may be left over from a removed feature, or may be a typo. This tool "
                "cannot tell which, so it reports the fact and not a cause.\n")
            for k in sorted(inert):
                out.append("- `%s` = `%s`" % (k, json.dumps(live[k])))
        missing = [k for k in sorted(flags) if k not in live]
        if missing:
            out.append(
                "\n### Keys the host reads that the file does not set\n\n"
                "Each falls back to the default in the table above.\n")
            for k in missing:
                out.append("- `%s` (default `%s`)" % (k, flags[k]["default"]))
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------
# The C ABI
# --------------------------------------------------------------------------

BANNER_RE = re.compile(r"\A\s*/\*(.*?)\*/", re.S)
# A definition in these headers is a file-scope `static` function. They are
# single-file C consumed by nimony through `importc` + `header`, so `static`
# is the unit of interface, not `extern`.
FUNC_RE = re.compile(
    r"^static\s+(?:const\s+)?([A-Za-z_][A-Za-z0-9_ *]*?)\s*\**\s*"
    r"\b(aowl[A-Za-z0-9_]*)\s*\(([^;{)]*)\)\s*[{]", re.M)
TYPEDEF_RE = re.compile(r"^typedef\s+struct\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{", re.M)
DEFINE_RE = re.compile(r"^#define\s+(AOWL[A-Za-z0-9_]*)\b", re.M)


def header_banner(text):
    """The leading block comment. These headers open with a real design note --
    often the only place a subsystem's rationale is written down -- so it is
    carried into the docs verbatim rather than paraphrased."""
    m = BANNER_RE.match(text)
    if not m:
        return None
    lines = []
    for ln in m.group(1).splitlines():
        ln = re.sub(r"^\s*\*ementity?", "", ln)
        ln = re.sub(r"^\s*\* ?", "", ln)
        lines.append(ln.rstrip())
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    return "\n".join(lines)


def fenced(text, lang="text"):
    """Wrap text in a fence long enough that the text cannot terminate it."""
    longest = 0
    for m in re.finditer(r"`+", text):
        longest = max(longest, len(m.group(0)))
    fence = "`" * max(3, longest + 1)
    return "%s%s\n%s\n%s\n" % (fence, lang, text.rstrip("\n"), fence)


def md_safe(text):
    """Escape prose so VitePress does not try to parse it as Vue markup.

    These headers are C, so their comments are full of `<stdint.h>`, `List<int>`
    and `->`. VitePress compiles every markdown file as a Vue SFC, so a bare
    `<int>` in prose is an unclosed element and fails the whole build.

    Backtick spans are left alone: VitePress escapes their contents already, and
    rewriting them would print `&lt;` to the reader verbatim.
    """
    out, i = [], 0
    for m in re.finditer(r"`[^`\n]*`", text):
        out.append(text[i:m.start()].replace("&", "&amp;")
                   .replace("<", "&lt;").replace(">", "&gt;"))
        out.append(m.group(0))
        i = m.end()
    out.append(text[i:].replace("&", "&amp;")
               .replace("<", "&lt;").replace(">", "&gt;"))
    return "".join(out)


def header_summary(h):
    """One-line summary for the index table.

    These banners conventionally open `aowlspt_foo.h - what it is`, sometimes
    wrapping onto the next line. So: take the first paragraph, strip a leading
    filename and its dash, collapse to one line, and truncate on a sentence
    boundary. Returns None when there is nothing to take, so the caller can say
    UNKNOWN rather than print an empty cell.
    """
    banner = h["banner"]
    if not banner:
        return None
    para = []
    for ln in banner.splitlines():
        if not ln.strip():
            if para:
                break
            continue
        para.append(ln.strip())
    if not para:
        return None
    text = " ".join(para)
    # Drop a leading `aowlspt_foo.h -` / `aowlspt_foo.h:` prefix.
    text = re.sub(r"^%s\s*[-:—]\s*" % re.escape(h["name"]), "", text)
    text = re.sub(r"^[-—]\s*", "", text).strip()
    if not text:
        return None
    # Truncate at the first sentence end, but only if that leaves something
    # substantial -- an abbreviation mid-sentence should not cut it to nothing.
    m = re.search(r"^(.{40,220}?[.!?])(\s|$)", text)
    if m:
        text = m.group(1)
    elif len(text) > 220:
        text = text[:217].rsplit(" ", 1)[0] + "..."
    return text[0].upper() + text[1:] if text else None


def collect_headers():
    abidir = os.path.join(ROOT, "abi")
    out = []
    for n in sorted(os.listdir(abidir)):
        if not n.endswith(".h"):
            continue
        path = os.path.join(abidir, n)
        text = read(path)
        funcs = []
        for m in FUNC_RE.finditer(text):
            ret, name, args = m.group(1).strip(), m.group(2), m.group(3).strip()
            args = re.sub(r"\s+", " ", args) or "void"
            lineno = text.count("\n", 0, m.start()) + 1
            funcs.append((name, ret, args, lineno))
        out.append({
            "name": n,
            "path": rel(path),
            "lines": text.count("\n") + 1,
            "banner": header_banner(text),
            "funcs": funcs,
            "structs": sorted(set(TYPEDEF_RE.findall(text))),
            "defines": sorted(set(DEFINE_RE.findall(text))),
        })
    return out


def slug(name):
    return name.replace(".h", "").replace("_", "-")


def page_abi_index(headers):
    out = [GENERATED_BANNER, "# The host C ABI\n"]
    out.append(
        "`abi/` is the host's C surface: one self-contained header per subsystem,\n"
        "each compiled into the host DLL and bound from nimony with `importc` +\n"
        "`header`. There is no `.c` file and no export table — the unit of interface\n"
        "is a file-scope `static` function, and a header owns its own state.\n")
    out.append(
        "%d headers, %d file-scope functions, %d lines of C in total.\n" % (
            len(headers),
            sum(len(h["funcs"]) for h in headers),
            sum(h["lines"] for h in headers)))
    out.append(
        "::: tip Read the header, not just this table\n"
        "Most of these headers open with a long design note explaining *why* the\n"
        "subsystem is shaped the way it is. Those notes are reproduced in full on each\n"
        "header's own page — they are frequently the only written record of a\n"
        "decision.\n:::\n")
    out.append("| Header | Functions | Lines | Summary |")
    out.append("| --- | --- | --- | --- |")
    for h in headers:
        first = header_summary(h)
        if first:
            first = md_safe(first).replace("|", "\\|")
        else:
            first = "_UNKNOWN — the header has no summary banner_"
        out.append("| [`%s`](./abi/%s) | %d | %d | %s |" % (
            h["name"], slug(h["name"]), len(h["funcs"]), h["lines"], first))
    return "\n".join(out) + "\n"


def page_abi_header(h):
    out = [GENERATED_BANNER, "# `%s`\n" % h["name"]]
    out.append("Source: [`%s`](https://github.com/aoughwl/aowlspt/blob/main/%s) — "
               "%d lines, %d file-scope functions.\n" % (
                   h["path"], h["path"], h["lines"], len(h["funcs"])))
    if h["banner"]:
        out.append("## What this header owns\n")
        out.append(
            "Reproduced verbatim from the header's own banner comment — these notes\n"
            "are frequently the only written record of why the subsystem is shaped the\n"
            "way it is.\n")
        # A fenced block, not a blockquote. Two reasons, both load-bearing:
        # these banners contain hand-aligned ASCII tables and diagrams that a
        # blockquote reflows into nonsense, and VitePress compiles every page as
        # a Vue SFC, so bare `<stdint.h>` or `List<int>` in prose is an unclosed
        # element that fails the entire site build.
        out.append(fenced(h["banner"]))
    else:
        out.append("## What this header owns\n\n_UNKNOWN — no banner comment._\n")

    if h["defines"]:
        out.append("## Constants\n")
        for d in h["defines"]:
            out.append("- `%s`" % d)
        out.append("")
    if h["structs"]:
        out.append("## Types\n")
        for s in h["structs"]:
            out.append("- `struct %s`" % s)
        out.append("")
    out.append("## Functions\n")
    if not h["funcs"]:
        out.append("_None at file scope. This header is types, constants or "
                   "inline macros only._\n")
    else:
        out.append("| Signature | Line |")
        out.append("| --- | --- |")
        for name, ret, args, lineno in h["funcs"]:
            sig = ("%s %s(%s)" % (ret, name, args)).replace("|", "\\|")
            out.append("| `%s` | %d |" % (sig, lineno))
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------
# Mods
# --------------------------------------------------------------------------

def parse_mod_config(path):
    """Pull (key, value, doc) out of a mod config.json.

    These files carry their own documentation in sibling keys -- either
    `_keyComment` / `_key` or `//key` -- immediately beside the key they
    describe. That convention is what makes this page generable at all.
    """
    try:
        raw = json.loads(read(path))
    except Exception as e:
        return None, str(e)
    if not isinstance(raw, dict):
        return None, "top level is not an object"

    docs, keys = {}, []
    for k, v in raw.items():
        if k.startswith("//") or k.startswith("_"):
            target = k.lstrip("/_")
            for suffix in ("Comment", ""):
                if suffix and target.endswith(suffix):
                    target = target[: -len(suffix)]
                    break
            if target and isinstance(v, str):
                # `_comment` / `//` are file-level, not key-level.
                if target.lower() in ("comment", ""):
                    docs.setdefault("__file__", []).append(v)
                else:
                    docs[target] = v
            continue
        keys.append((k, v))
    return {"keys": keys, "docs": docs}, None


def collect_mods():
    moddir = os.path.join(ROOT, "mods")
    out = []
    for n in sorted(os.listdir(moddir)):
        d = os.path.join(moddir, n)
        if not os.path.isdir(d):
            continue
        cfgpath = os.path.join(d, "config.json")
        cfg, err = (None, "no config.json")
        if os.path.exists(cfgpath):
            cfg, err = parse_mod_config(cfgpath)
        readme = os.path.join(d, "README.md")
        out.append({
            "name": n,
            "dir": rel(d),
            "config": cfg,
            "config_error": err,
            "config_path": rel(cfgpath) if os.path.exists(cfgpath) else None,
            "has_readme": os.path.exists(readme),
            "sources": sorted(
                f for f in os.listdir(d) if f.endswith(".nim")),
        })
    return out


def page_mods_index(mods):
    out = [GENERATED_BANNER, "# Mods\n"]
    out.append(
        "The %d mods under `mods/`. Each is a nimony library built against the host\n"
        "ABI, shipping a `config.json` whose keys are its settings surface.\n"
        % len(mods))
    documented = sum(1 for m in mods if m["config"])
    total_keys = sum(len(m["config"]["keys"]) for m in mods if m["config"])
    out.append(
        "%d of %d carry a parseable `config.json`, %d settings keys between them.\n"
        % (documented, len(mods), total_keys))
    out.append("| Mod | Settings keys | Sources | README |")
    out.append("| --- | --- | --- | --- |")
    for m in mods:
        nk = len(m["config"]["keys"]) if m["config"] else 0
        cell = str(nk) if m["config"] else "_none_"
        out.append("| [`%s`](./mods/%s) | %s | %s | %s |" % (
            m["name"], m["name"], cell,
            ", ".join("`%s`" % s for s in m["sources"]) or "_UNKNOWN_",
            "yes" if m["has_readme"] else "no"))
    return "\n".join(out) + "\n"


def page_mod(m):
    out = [GENERATED_BANNER, "# `%s`\n" % m["name"]]
    out.append("Source: [`%s`](https://github.com/aoughwl/aowlspt/blob/main/%s).\n"
               % (m["dir"], m["dir"]))
    if not m["config"]:
        out.append("## Settings\n\n_UNKNOWN — %s._\n" % m["config_error"])
        return "\n".join(out) + "\n"

    filedoc = m["config"]["docs"].get("__file__", [])
    if filedoc:
        out.append("## What it does\n")
        for d in filedoc:
            out.append("> %s\n" % md_safe(d).replace("\n", "\n> "))

    out.append("## Settings\n")
    out.append("Defined in [`%s`](https://github.com/aoughwl/aowlspt/blob/main/%s). "
               "The values shown are the **shipped defaults**, not what is currently "
               "deployed.\n" % (m["config_path"], m["config_path"]))
    for k, v in m["config"]["keys"]:
        out.append("### `%s`\n" % k)
        out.append("- **Default:** `%s`" % json.dumps(v))
        doc = m["config"]["docs"].get(k)
        if doc:
            out.append("\n%s\n" % md_safe(doc))
        else:
            out.append("\n_UNKNOWN — this key carries no doc comment in "
                       "`config.json`._\n")
        # Some configs document individual VALUES of a key with dotted doc keys
        # -- `//preset.filmic` beside `//preset`. That is real documentation and
        # dropping it silently would be exactly the kind of quiet loss this
        # generator exists to prevent.
        subs = sorted((dk, dv) for dk, dv in m["config"]["docs"].items()
                      if isinstance(dk, str) and dk.startswith(k + "."))
        if subs:
            out.append("\nAccepted values:\n")
            for dk, dv in subs:
                out.append("- **`%s`** — %s" % (dk[len(k) + 1:], md_safe(dv)))
            out.append("")
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------

def build():
    """Return {relative path: content} for the whole generated reference."""
    pages = {}
    headers = collect_headers()
    mods = collect_mods()

    pages["host-flags.md"] = page_flags()
    pages["abi.md"] = page_abi_index(headers)
    for h in headers:
        pages["abi/%s.md" % slug(h["name"])] = page_abi_header(h)
    pages["mods.md"] = page_mods_index(mods)
    for m in mods:
        pages["mods/%s.md" % m["name"]] = page_mod(m)

    pages["index.md"] = (
        GENERATED_BANNER
        + "# Reference\n\n"
        "Everything on these pages is **generated from source** by\n"
        "`tools/gendocs.py` in the aowlspt repo. Nothing here is hand-written, and\n"
        "nothing here should be edited in place — an edit will be overwritten on the\n"
        "next run, and worse, it will read as authoritative in the meantime.\n\n"
        "The generator was written because this project has repeatedly paid for\n"
        "hand-written reference prose that drifted out of date while still reading as\n"
        "authoritative. Where a fact cannot be extracted mechanically, these pages say\n"
        "**UNKNOWN** rather than guessing.\n\n"
        "## What is here\n\n"
        "- **[Host configuration flags](./host-flags)** — every key the host reads,\n"
        "  from its call site, with its type, default and read location.\n"
        "- **[The C ABI](./abi)** — every `abi/aowlspt_*.h`, what it owns, its\n"
        "  functions, types and constants.\n"
        "- **[Mods](./mods)** — every mod, every settings key, every doc comment.\n\n"
        "## Regenerating\n\n"
        "```bash\n"
        "cd aowlspt\n"
        "python tools/gendocs.py --out ../aoughwl.github.io/docs/aowlspt/reference\n"
        "```\n\n"
        "`--check` exits non-zero if the output would change, which is what a CI step\n"
        "should run so a source change that invalidates the docs fails loudly instead\n"
        "of drifting silently.\n"
        "\n## Sidebar\n\n"
        "The generator also emits `sidebar.json`, which `.vitepress/config.mjs`\n"
        "imports — so a new header or a new mod appears in the navigation without\n"
        "anyone editing the config by hand.\n")

    # The sidebar is generated too, so adding a header or a mod cannot leave an
    # orphan page that is reachable only by search.
    sidebar = [
        {"text": "Overview", "link": "/docs/aowlspt/reference/"},
        {"text": "Host configuration flags",
         "link": "/docs/aowlspt/reference/host-flags"},
        {"text": "The C ABI", "link": "/docs/aowlspt/reference/abi",
         "collapsed": True,
         "items": [{"text": h["name"],
                    "link": "/docs/aowlspt/reference/abi/%s" % slug(h["name"])}
                   for h in headers]},
        {"text": "Mods", "link": "/docs/aowlspt/reference/mods",
         "collapsed": True,
         "items": [{"text": m["name"],
                    "link": "/docs/aowlspt/reference/mods/%s" % m["name"]}
                   for m in mods]},
    ]
    pages["sidebar.json"] = json.dumps(sidebar, indent=2) + "\n"
    return pages


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", help="directory to write the reference pages into")
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the output would change")
    args = ap.parse_args()

    pages = build()
    if not args.out:
        for p in sorted(pages):
            print(p)
        return 0

    changed = []
    for relpath, content in sorted(pages.items()):
        dest = os.path.join(args.out, relpath)
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        old = read(dest) if os.path.exists(dest) else None
        if old != content:
            changed.append(relpath)
            if not args.check:
                with open(dest, "w", encoding="utf-8", newline="\n") as f:
                    f.write(content)

    if args.check:
        if changed:
            sys.stderr.write(
                "gendocs: %d page(s) are out of date with the source:\n  %s\n"
                % (len(changed), "\n  ".join(changed)))
            return 1
        print("gendocs: up to date (%d pages)" % len(pages))
        return 0

    print("gendocs: wrote %d page(s), %d changed" % (len(pages), len(changed)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
