#!/usr/bin/env python3
"""Count real, hand-written source lines in aowlspt.

Counts only files git tracks, so build output and untracked scratch never
inflate the number. Excludes, and reports separately, the four kinds of line
that are not hand-written product code:

  tests       tests/, examples/, and anything named *_test / test_* / *test.nim
  generated   a file whose first few lines say it was generated
  data        .json/.bin/.svg/... payloads, which are data, not code
  docs        .md and friends

Within a counted file, blank lines and whole-line comments are not code.

Usage:
  python tools/loc.py               summary by bucket, then by top-level dir
  python tools/loc.py --by-ext      also break the code total down by extension
  python tools/loc.py --files N     list the N largest counted files
  python tools/loc.py --json        machine-readable
"""
import argparse, json, os, re, subprocess, sys
from collections import defaultdict

ROOT = subprocess.run(["git", "rev-parse", "--show-toplevel"],
                      capture_output=True, text=True, check=True).stdout.strip()

# ext -> (line-comment prefixes, (block open, block close) or None)
LANG = {
    ".nim": (("#",), ("#[", "]#")),
    ".py":  (("#",), None),
    ".c":   (("//",), ("/*", "*/")),
    ".h":   (("//",), ("/*", "*/")),
    ".inc": (("//",), ("/*", "*/")),
    ".cs":  (("//",), ("/*", "*/")),
    ".js":  (("//",), ("/*", "*/")),
    ".hlsl":(("//",), ("/*", "*/")),
    ".ps1": (("#",), ("<#", "#>")),
    ".sh":  (("#",), None),
}
DOC_EXT  = {".md", ".txt", ".rst"}
DATA_EXT = {".json", ".bin", ".svg", ".csproj", ".sln", ".config", ".template",
            ".dll", ".gitignore", ".gitattributes", ".xml", ".yml", ".yaml"}

TEST_DIRS = ("tests/", "examples/", "reference/", ".claude/")
TEST_FILE = re.compile(r"(^|/)(test_[^/]+|[^/]*_test|[^/]*tests?)\.[a-z]+$")
# tools/ files that exist to test or generate, not to ship
GEN_NAME  = re.compile(r"(^|/)(gen_[^/]+|[^/]*_gen)\.[a-z]+$")
GEN_MARK  = re.compile(r"auto-?generated|generated by|do not edit|@generated", re.I)


def classify(path):
    ext = os.path.splitext(path)[1].lower()
    if ext in DOC_EXT:
        return "docs"
    if ext not in LANG:
        return "data"
    if path.startswith(TEST_DIRS) or TEST_FILE.search(path):
        return "tests"
    return "code"


def is_generated(abspath):
    try:
        with open(abspath, "r", encoding="utf-8", errors="replace") as f:
            head = "".join(next(f, "") for _ in range(8))
    except OSError:
        return False
    return bool(GEN_MARK.search(head))


def count(abspath, ext):
    """-> (code, comment, blank). Whole-line comments only; a trailing comment
    on a real statement still counts as code, which is the honest reading."""
    line_pfx, block = LANG[ext]
    code = com = blank = 0
    in_block = False
    try:
        f = open(abspath, "r", encoding="utf-8", errors="replace")
    except OSError:
        return 0, 0, 0
    with f:
        for raw in f:
            s = raw.strip()
            if in_block:
                com += 1
                if block and block[1] in s:
                    in_block = False
                continue
            if not s:
                blank += 1
            elif s.startswith(line_pfx):
                com += 1
            elif block and s.startswith(block[0]):
                com += 1
                if block[1] not in s[len(block[0]):]:
                    in_block = True
            else:
                code += 1
    return code, com, blank


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--by-ext", action="store_true")
    ap.add_argument("--files", type=int, default=0, metavar="N")
    ap.add_argument("--json", action="store_true")
    a = ap.parse_args()

    tracked = subprocess.run(["git", "-C", ROOT, "ls-files"],
                             capture_output=True, text=True, check=True).stdout.split("\n")

    buckets = defaultdict(lambda: [0, 0])          # bucket -> [files, lines]
    by_dir  = defaultdict(lambda: [0, 0])
    by_ext  = defaultdict(lambda: [0, 0])
    per_file = []
    tot_com = tot_blank = 0

    for rel in tracked:
        if not rel:
            continue
        abspath = os.path.join(ROOT, rel)
        if not os.path.isfile(abspath):
            continue
        kind = classify(rel)
        ext = os.path.splitext(rel)[1].lower()
        if kind != "code":
            n = sum(1 for _ in open(abspath, "rb")) if kind != "data" else 0
            buckets[kind][0] += 1
            buckets[kind][1] += n
            continue
        if GEN_NAME.search(rel) or is_generated(abspath):
            c, _, _ = count(abspath, ext)
            buckets["generated"][0] += 1
            buckets["generated"][1] += c
            continue
        c, cm, bl = count(abspath, ext)
        tot_com += cm
        tot_blank += bl
        buckets["code"][0] += 1
        buckets["code"][1] += c
        top = rel.split("/")[0] if "/" in rel else "(root)"
        by_dir[top][0] += 1
        by_dir[top][1] += c
        by_ext[ext][0] += 1
        by_ext[ext][1] += c
        per_file.append((c, rel))

    if a.json:
        print(json.dumps({
            "code_lines": buckets["code"][1],
            "code_files": buckets["code"][0],
            "comment_lines": tot_com, "blank_lines": tot_blank,
            "excluded": {k: {"files": v[0], "lines": v[1]}
                         for k, v in buckets.items() if k != "code"},
            "by_dir": {k: {"files": v[0], "lines": v[1]} for k, v in by_dir.items()},
            "by_ext": {k: {"files": v[0], "lines": v[1]} for k, v in by_ext.items()},
        }, indent=2))
        return

    print(f"aowlspt source lines (tracked files only)\n")
    print(f"  CODE            {buckets['code'][1]:>8,}  in {buckets['code'][0]:>4} files")
    print(f"    (+ comments   {tot_com:>8,}   blank {tot_blank:,})\n")
    print("  excluded:")
    for k in ("tests", "generated", "docs", "data"):
        f, n = buckets[k]
        shown = f"{n:>8,}" if n else "       -"
        print(f"    {k:<12}{shown}  in {f:>4} files")

    print("\n  code by top-level dir:")
    for d, (f, n) in sorted(by_dir.items(), key=lambda kv: -kv[1][1]):
        print(f"    {d:<14}{n:>8,}  ({f} files)")

    if a.by_ext:
        print("\n  code by extension:")
        for e, (f, n) in sorted(by_ext.items(), key=lambda kv: -kv[1][1]):
            print(f"    {e:<14}{n:>8,}  ({f} files)")

    if a.files:
        print(f"\n  {a.files} largest counted files:")
        for n, rel in sorted(per_file, reverse=True)[:a.files]:
            print(f"    {n:>7,}  {rel}")


if __name__ == "__main__":
    main()
