## aowlspt_symtab.nim -- GENERATED by tools/il2cpp_symtab.py. DO NOT EDIT.
##
## The Nim/Nimony face of abi/aowlspt_symtab.h. Same gates, same RVAs.
## A REJECTED symbol is simply ABSENT here: referencing it is an
## `undeclared identifier` compile error, and `il2cpp_symtab.py check`
## turns that into a message naming the file, line and reason.
##
## Edit abi/aowlspt_symbols.txt, never this file.

const
  AowlSymtabImageKey* = 0x6A7CA21C078F0000'u64
  AowlSymtabFileSha256* = "e0ea3ad3b76bc0b9da4a385ea0aa22b8158e98a380e105cb6e6cc44f73857483"
  AowlSymtabPrologueLen* = 16

const
  AOWL_SYM_GO_GET_TRANSFORM* = 0x052A8AE0'u32
    ## Transform get_transform()
    ## UnityEngine.GameObject::get_transform/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_GO_GET_TRANSFORM_ARITY* = 0
  AOWL_SYM_GO_GET_TRANSFORM_OWNERS* = 1
  AOWL_SYM_GO_GET_TRANSFORM_NAME* = "UnityEngine.GameObject::get_transform/0"
  AOWL_SYM_GO_GET_TRANSFORM_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0x93'u8, 0xBA'u8, 0xE2'u8, 0x01'u8, 0x48'u8, 0x8B'u8, 0xD9'u8]

const
  AOWL_SYM_GO_SET_ACTIVE* = 0x052A8BE0'u32
    ## void SetActive(bool value)
    ## UnityEngine.GameObject::SetActive/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_GO_SET_ACTIVE_ARITY* = 1
  AOWL_SYM_GO_SET_ACTIVE_OWNERS* = 1
  AOWL_SYM_GO_SET_ACTIVE_NAME* = "UnityEngine.GameObject::SetActive/1"
  AOWL_SYM_GO_SET_ACTIVE_PROLOGUE* = [0x48'u8, 0x89'u8, 0x5C'u8, 0x24'u8, 0x08'u8, 0x57'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0xA7'u8, 0xB9'u8, 0xE2'u8]

const
  AOWL_SYM_GO_ACTIVE_SELF* = 0x052A8C40'u32
    ## bool get_activeSelf()
    ## UnityEngine.GameObject::get_activeSelf/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_GO_ACTIVE_SELF_ARITY* = 0
  AOWL_SYM_GO_ACTIVE_SELF_OWNERS* = 1
  AOWL_SYM_GO_ACTIVE_SELF_NAME* = "UnityEngine.GameObject::get_activeSelf/0"
  AOWL_SYM_GO_ACTIVE_SELF_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0x53'u8, 0xB9'u8, 0xE2'u8, 0x01'u8, 0x48'u8, 0x8B'u8, 0xD9'u8]

const
  AOWL_SYM_GO_ACTIVE_IN_HIERARCHY* = 0x052A8C90'u32
    ## bool get_activeInHierarchy()
    ## UnityEngine.GameObject::get_activeInHierarchy/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_GO_ACTIVE_IN_HIERARCHY_ARITY* = 0
  AOWL_SYM_GO_ACTIVE_IN_HIERARCHY_OWNERS* = 1
  AOWL_SYM_GO_ACTIVE_IN_HIERARCHY_NAME* = "UnityEngine.GameObject::get_activeInHierarchy/0"
  AOWL_SYM_GO_ACTIVE_IN_HIERARCHY_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0x0B'u8, 0xB9'u8, 0xE2'u8, 0x01'u8, 0x48'u8, 0x8B'u8, 0xD9'u8]

const
  AOWL_SYM_GO_GET_LAYER* = 0x052A8B30'u32
    ## int get_layer()
    ## UnityEngine.GameObject::get_layer/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_GO_GET_LAYER_ARITY* = 0
  AOWL_SYM_GO_GET_LAYER_OWNERS* = 1
  AOWL_SYM_GO_GET_LAYER_NAME* = "UnityEngine.GameObject::get_layer/0"
  AOWL_SYM_GO_GET_LAYER_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0x4B'u8, 0xBA'u8, 0xE2'u8, 0x01'u8, 0x48'u8, 0x8B'u8, 0xD9'u8]

const
  AOWL_SYM_GO_GET_SCENE_INJECTED* = 0x052A92C0'u32
    ## void get_scene_Injected(Scene ret)
    ## UnityEngine.GameObject::get_scene_Injected/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_GO_GET_SCENE_INJECTED_ARITY* = 1
  AOWL_SYM_GO_GET_SCENE_INJECTED_OWNERS* = 1
  AOWL_SYM_GO_GET_SCENE_INJECTED_NAME* = "UnityEngine.GameObject::get_scene_Injected/1"
  AOWL_SYM_GO_GET_SCENE_INJECTED_PROLOGUE* = [0x48'u8, 0x89'u8, 0x5C'u8, 0x24'u8, 0x08'u8, 0x57'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0x27'u8, 0xB3'u8, 0xE2'u8]

const
  AOWL_SYM_OBJ_GET_NAME* = 0x052AD4B0'u32
    ## string get_name()
    ## UnityEngine.Object::get_name/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_OBJ_GET_NAME_ARITY* = 0
  AOWL_SYM_OBJ_GET_NAME_OWNERS* = 1
  AOWL_SYM_OBJ_GET_NAME_NAME* = "UnityEngine.Object::get_name/0"
  AOWL_SYM_OBJ_GET_NAME_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x80'u8, 0x3D'u8, 0x36'u8, 0x72'u8, 0xE2'u8, 0x01'u8, 0x00'u8, 0x48'u8, 0x8B'u8, 0xD9'u8]

const
  AOWL_SYM_OBJ_SET_NAME* = 0x052AD540'u32
    ## void set_name(string value)
    ## UnityEngine.Object::set_name/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_OBJ_SET_NAME_ARITY* = 1
  AOWL_SYM_OBJ_SET_NAME_OWNERS* = 1
  AOWL_SYM_OBJ_SET_NAME_NAME* = "UnityEngine.Object::set_name/1"
  AOWL_SYM_OBJ_SET_NAME_PROLOGUE* = [0x48'u8, 0x89'u8, 0x5C'u8, 0x24'u8, 0x08'u8, 0x57'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x80'u8, 0x3D'u8, 0xA3'u8, 0x71'u8, 0xE2'u8, 0x01'u8]

const
  AOWL_SYM_OBJ_GET_INSTANCE_ID* = 0x052ACFD0'u32
    ## int GetInstanceID()
    ## UnityEngine.Object::GetInstanceID/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_OBJ_GET_INSTANCE_ID_ARITY* = 0
  AOWL_SYM_OBJ_GET_INSTANCE_ID_OWNERS* = 1
  AOWL_SYM_OBJ_GET_INSTANCE_ID_NAME* = "UnityEngine.Object::GetInstanceID/0"
  AOWL_SYM_OBJ_GET_INSTANCE_ID_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x80'u8, 0x3D'u8, 0x12'u8, 0x77'u8, 0xE2'u8, 0x01'u8, 0x00'u8, 0x48'u8, 0x8B'u8, 0xD9'u8]

const
  AOWL_SYM_TF_GET_CHILD_COUNT* = 0x052B9CA0'u32
    ## int get_childCount()
    ## UnityEngine.Transform::get_childCount/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_TF_GET_CHILD_COUNT_ARITY* = 0
  AOWL_SYM_TF_GET_CHILD_COUNT_OWNERS* = 1
  AOWL_SYM_TF_GET_CHILD_COUNT_NAME* = "UnityEngine.Transform::get_childCount/0"
  AOWL_SYM_TF_GET_CHILD_COUNT_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0x03'u8, 0xAF'u8, 0xE1'u8, 0x01'u8, 0x48'u8, 0x8B'u8, 0xD9'u8]

const
  AOWL_SYM_TF_GET_CHILD* = 0x052BA180'u32
    ## Transform GetChild(int index)
    ## UnityEngine.Transform::GetChild/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_TF_GET_CHILD_ARITY* = 1
  AOWL_SYM_TF_GET_CHILD_OWNERS* = 1
  AOWL_SYM_TF_GET_CHILD_NAME* = "UnityEngine.Transform::GetChild/1"
  AOWL_SYM_TF_GET_CHILD_PROLOGUE* = [0x48'u8, 0x89'u8, 0x5C'u8, 0x24'u8, 0x08'u8, 0x57'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0x6F'u8, 0xAA'u8, 0xE1'u8]

const
  AOWL_SYM_TF_SET_AS_FIRST_SIBLING* = 0x052B9CF0'u32
    ## void SetAsFirstSibling()
    ## UnityEngine.Transform::SetAsFirstSibling/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_TF_SET_AS_FIRST_SIBLING_ARITY* = 0
  AOWL_SYM_TF_SET_AS_FIRST_SIBLING_OWNERS* = 1
  AOWL_SYM_TF_SET_AS_FIRST_SIBLING_NAME* = "UnityEngine.Transform::SetAsFirstSibling/0"
  AOWL_SYM_TF_SET_AS_FIRST_SIBLING_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0xBB'u8, 0xAE'u8, 0xE1'u8, 0x01'u8, 0x48'u8, 0x8B'u8, 0xD9'u8]

const
  AOWL_SYM_TF_GET_LOCAL_POSITION* = 0x052B71B0'u32
    ## Vector3 get_localPosition()
    ## UnityEngine.Transform::get_localPosition/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_TF_GET_LOCAL_POSITION_ARITY* = 0
  AOWL_SYM_TF_GET_LOCAL_POSITION_OWNERS* = 1
  AOWL_SYM_TF_GET_LOCAL_POSITION_NAME* = "UnityEngine.Transform::get_localPosition/0"
  AOWL_SYM_TF_GET_LOCAL_POSITION_PROLOGUE* = [0x48'u8, 0x89'u8, 0x5C'u8, 0x24'u8, 0x08'u8, 0x57'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x33'u8, 0xC0'u8, 0x48'u8, 0x8B'u8, 0xFA'u8, 0x48'u8]

const
  AOWL_SYM_TF_SET_LOCAL_POSITION* = 0x052B7220'u32
    ## void set_localPosition(Vector3 value)
    ## UnityEngine.Transform::set_localPosition/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_TF_SET_LOCAL_POSITION_ARITY* = 1
  AOWL_SYM_TF_SET_LOCAL_POSITION_OWNERS* = 1
  AOWL_SYM_TF_SET_LOCAL_POSITION_NAME* = "UnityEngine.Transform::set_localPosition/1"
  AOWL_SYM_TF_SET_LOCAL_POSITION_PROLOGUE* = [0x48'u8, 0x89'u8, 0x5C'u8, 0x24'u8, 0x08'u8, 0x57'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0xEF'u8, 0xD9'u8, 0xE1'u8]

const
  AOWL_SYM_TF_GET_LOCAL_SCALE* = 0x052B8100'u32
    ## Vector3 get_localScale()
    ## UnityEngine.Transform::get_localScale/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_TF_GET_LOCAL_SCALE_ARITY* = 0
  AOWL_SYM_TF_GET_LOCAL_SCALE_OWNERS* = 1
  AOWL_SYM_TF_GET_LOCAL_SCALE_NAME* = "UnityEngine.Transform::get_localScale/0"
  AOWL_SYM_TF_GET_LOCAL_SCALE_PROLOGUE* = [0x48'u8, 0x89'u8, 0x5C'u8, 0x24'u8, 0x08'u8, 0x57'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x33'u8, 0xC0'u8, 0x48'u8, 0x8B'u8, 0xFA'u8, 0x48'u8]

const
  AOWL_SYM_TF_SET_LOCAL_SCALE* = 0x052B8170'u32
    ## void set_localScale(Vector3 value)
    ## UnityEngine.Transform::set_localScale/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_TF_SET_LOCAL_SCALE_ARITY* = 1
  AOWL_SYM_TF_SET_LOCAL_SCALE_OWNERS* = 1
  AOWL_SYM_TF_SET_LOCAL_SCALE_NAME* = "UnityEngine.Transform::set_localScale/1"
  AOWL_SYM_TF_SET_LOCAL_SCALE_PROLOGUE* = [0x48'u8, 0x89'u8, 0x5C'u8, 0x24'u8, 0x08'u8, 0x57'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0xCF'u8, 0xCA'u8, 0xE1'u8]

const
  AOWL_SYM_RT_GET_RECT* = 0x052B5240'u32
    ## Rect get_rect()
    ## UnityEngine.RectTransform::get_rect/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_RT_GET_RECT_ARITY* = 0
  AOWL_SYM_RT_GET_RECT_OWNERS* = 1
  AOWL_SYM_RT_GET_RECT_NAME* = "UnityEngine.RectTransform::get_rect/0"
  AOWL_SYM_RT_GET_RECT_PROLOGUE* = [0x48'u8, 0x89'u8, 0x5C'u8, 0x24'u8, 0x08'u8, 0x57'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0xDF'u8, 0xF8'u8, 0xE1'u8]

const
  AOWL_SYM_RT_GET_ANCHOR_MIN* = 0x052B52B0'u32
    ## Vector2 get_anchorMin()
    ## UnityEngine.RectTransform::get_anchorMin/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_RT_GET_ANCHOR_MIN_ARITY* = 0
  AOWL_SYM_RT_GET_ANCHOR_MIN_OWNERS* = 1
  AOWL_SYM_RT_GET_ANCHOR_MIN_NAME* = "UnityEngine.RectTransform::get_anchorMin/0"
  AOWL_SYM_RT_GET_ANCHOR_MIN_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x33'u8, 0xC0'u8, 0x48'u8, 0x8B'u8, 0xD9'u8, 0x48'u8, 0x89'u8, 0x44'u8, 0x24'u8, 0x40'u8]

const
  AOWL_SYM_RT_SET_ANCHOR_MIN* = 0x052B5310'u32
    ## void set_anchorMin(Vector2 value)
    ## UnityEngine.RectTransform::set_anchorMin/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_RT_SET_ANCHOR_MIN_ARITY* = 1
  AOWL_SYM_RT_SET_ANCHOR_MIN_OWNERS* = 1
  AOWL_SYM_RT_SET_ANCHOR_MIN_NAME* = "UnityEngine.RectTransform::set_anchorMin/1"
  AOWL_SYM_RT_SET_ANCHOR_MIN_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x30'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0x23'u8, 0xF8'u8, 0xE1'u8, 0x01'u8, 0x48'u8, 0x8B'u8, 0xD9'u8]

const
  AOWL_SYM_RT_GET_ANCHOR_MAX* = 0x052B5370'u32
    ## Vector2 get_anchorMax()
    ## UnityEngine.RectTransform::get_anchorMax/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_RT_GET_ANCHOR_MAX_ARITY* = 0
  AOWL_SYM_RT_GET_ANCHOR_MAX_OWNERS* = 1
  AOWL_SYM_RT_GET_ANCHOR_MAX_NAME* = "UnityEngine.RectTransform::get_anchorMax/0"
  AOWL_SYM_RT_GET_ANCHOR_MAX_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x33'u8, 0xC0'u8, 0x48'u8, 0x8B'u8, 0xD9'u8, 0x48'u8, 0x89'u8, 0x44'u8, 0x24'u8, 0x40'u8]

const
  AOWL_SYM_RT_SET_ANCHOR_MAX* = 0x052B53D0'u32
    ## void set_anchorMax(Vector2 value)
    ## UnityEngine.RectTransform::set_anchorMax/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_RT_SET_ANCHOR_MAX_ARITY* = 1
  AOWL_SYM_RT_SET_ANCHOR_MAX_OWNERS* = 1
  AOWL_SYM_RT_SET_ANCHOR_MAX_NAME* = "UnityEngine.RectTransform::set_anchorMax/1"
  AOWL_SYM_RT_SET_ANCHOR_MAX_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x30'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0x73'u8, 0xF7'u8, 0xE1'u8, 0x01'u8, 0x48'u8, 0x8B'u8, 0xD9'u8]

const
  AOWL_SYM_RT_GET_ANCHORED_POS* = 0x052B5430'u32
    ## Vector2 get_anchoredPosition()
    ## UnityEngine.RectTransform::get_anchoredPosition/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_RT_GET_ANCHORED_POS_ARITY* = 0
  AOWL_SYM_RT_GET_ANCHORED_POS_OWNERS* = 1
  AOWL_SYM_RT_GET_ANCHORED_POS_NAME* = "UnityEngine.RectTransform::get_anchoredPosition/0"
  AOWL_SYM_RT_GET_ANCHORED_POS_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x33'u8, 0xC0'u8, 0x48'u8, 0x8B'u8, 0xD9'u8, 0x48'u8, 0x89'u8, 0x44'u8, 0x24'u8, 0x40'u8]

const
  AOWL_SYM_RT_SET_ANCHORED_POS* = 0x052B5490'u32
    ## void set_anchoredPosition(Vector2 value)
    ## UnityEngine.RectTransform::set_anchoredPosition/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_RT_SET_ANCHORED_POS_ARITY* = 1
  AOWL_SYM_RT_SET_ANCHORED_POS_OWNERS* = 1
  AOWL_SYM_RT_SET_ANCHORED_POS_NAME* = "UnityEngine.RectTransform::set_anchoredPosition/1"
  AOWL_SYM_RT_SET_ANCHORED_POS_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x30'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0xC3'u8, 0xF6'u8, 0xE1'u8, 0x01'u8, 0x48'u8, 0x8B'u8, 0xD9'u8]

const
  AOWL_SYM_RT_GET_SIZE_DELTA* = 0x052B54F0'u32
    ## Vector2 get_sizeDelta()
    ## UnityEngine.RectTransform::get_sizeDelta/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_RT_GET_SIZE_DELTA_ARITY* = 0
  AOWL_SYM_RT_GET_SIZE_DELTA_OWNERS* = 1
  AOWL_SYM_RT_GET_SIZE_DELTA_NAME* = "UnityEngine.RectTransform::get_sizeDelta/0"
  AOWL_SYM_RT_GET_SIZE_DELTA_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x33'u8, 0xC0'u8, 0x48'u8, 0x8B'u8, 0xD9'u8, 0x48'u8, 0x89'u8, 0x44'u8, 0x24'u8, 0x40'u8]

const
  AOWL_SYM_RT_SET_SIZE_DELTA* = 0x052B5550'u32
    ## void set_sizeDelta(Vector2 value)
    ## UnityEngine.RectTransform::set_sizeDelta/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_RT_SET_SIZE_DELTA_ARITY* = 1
  AOWL_SYM_RT_SET_SIZE_DELTA_OWNERS* = 1
  AOWL_SYM_RT_SET_SIZE_DELTA_NAME* = "UnityEngine.RectTransform::set_sizeDelta/1"
  AOWL_SYM_RT_SET_SIZE_DELTA_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x30'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0x13'u8, 0xF6'u8, 0xE1'u8, 0x01'u8, 0x48'u8, 0x8B'u8, 0xD9'u8]

const
  AOWL_SYM_RT_GET_PIVOT* = 0x052B55B0'u32
    ## Vector2 get_pivot()
    ## UnityEngine.RectTransform::get_pivot/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_RT_GET_PIVOT_ARITY* = 0
  AOWL_SYM_RT_GET_PIVOT_OWNERS* = 1
  AOWL_SYM_RT_GET_PIVOT_NAME* = "UnityEngine.RectTransform::get_pivot/0"
  AOWL_SYM_RT_GET_PIVOT_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x33'u8, 0xC0'u8, 0x48'u8, 0x8B'u8, 0xD9'u8, 0x48'u8, 0x89'u8, 0x44'u8, 0x24'u8, 0x40'u8]

const
  AOWL_SYM_RT_SET_PIVOT* = 0x052B5610'u32
    ## void set_pivot(Vector2 value)
    ## UnityEngine.RectTransform::set_pivot/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_RT_SET_PIVOT_ARITY* = 1
  AOWL_SYM_RT_SET_PIVOT_OWNERS* = 1
  AOWL_SYM_RT_SET_PIVOT_NAME* = "UnityEngine.RectTransform::set_pivot/1"
  AOWL_SYM_RT_SET_PIVOT_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x30'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0x63'u8, 0xF5'u8, 0xE1'u8, 0x01'u8, 0x48'u8, 0x8B'u8, 0xD9'u8]

const
  AOWL_SYM_CANVAS_GET_RENDER_MODE* = 0x05584080'u32
    ## RenderMode get_renderMode()
    ## UnityEngine.Canvas::get_renderMode/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_CANVAS_GET_RENDER_MODE_ARITY* = 0
  AOWL_SYM_CANVAS_GET_RENDER_MODE_OWNERS* = 1
  AOWL_SYM_CANVAS_GET_RENDER_MODE_NAME* = "UnityEngine.Canvas::get_renderMode/0"
  AOWL_SYM_CANVAS_GET_RENDER_MODE_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0x73'u8, 0x3E'u8, 0xB5'u8, 0x01'u8, 0x48'u8, 0x8B'u8, 0xD9'u8]

const
  AOWL_SYM_CANVAS_GET_SCALE_FACTOR* = 0x05584180'u32
    ## float get_scaleFactor()
    ## UnityEngine.Canvas::get_scaleFactor/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_CANVAS_GET_SCALE_FACTOR_ARITY* = 0
  AOWL_SYM_CANVAS_GET_SCALE_FACTOR_OWNERS* = 1
  AOWL_SYM_CANVAS_GET_SCALE_FACTOR_NAME* = "UnityEngine.Canvas::get_scaleFactor/0"
  AOWL_SYM_CANVAS_GET_SCALE_FACTOR_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0x8B'u8, 0x3D'u8, 0xB5'u8, 0x01'u8, 0x48'u8, 0x8B'u8, 0xD9'u8]

const
  AOWL_SYM_CANVAS_GET_SORT_ORDER* = 0x05584540'u32
    ## int get_sortingOrder()
    ## UnityEngine.Canvas::get_sortingOrder/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_CANVAS_GET_SORT_ORDER_ARITY* = 0
  AOWL_SYM_CANVAS_GET_SORT_ORDER_OWNERS* = 1
  AOWL_SYM_CANVAS_GET_SORT_ORDER_NAME* = "UnityEngine.Canvas::get_sortingOrder/0"
  AOWL_SYM_CANVAS_GET_SORT_ORDER_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0x23'u8, 0x3A'u8, 0xB5'u8, 0x01'u8, 0x48'u8, 0x8B'u8, 0xD9'u8]

const
  AOWL_SYM_CAMERA_GET_MAIN* = 0x05260400'u32
    ## Camera get_main()
    ## UnityEngine.Camera::get_main/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_CAMERA_GET_MAIN_ARITY* = 0
  AOWL_SYM_CAMERA_GET_MAIN_OWNERS* = 1
  AOWL_SYM_CAMERA_GET_MAIN_NAME* = "UnityEngine.Camera::get_main/0"
  AOWL_SYM_CAMERA_GET_MAIN_PROLOGUE* = [0x48'u8, 0x83'u8, 0xEC'u8, 0x28'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0xD5'u8, 0x27'u8, 0xE7'u8, 0x01'u8, 0x48'u8, 0x85'u8, 0xC0'u8, 0x75'u8, 0x18'u8]

const
  AOWL_SYM_TIME_GET_FRAME_COUNT* = 0x052B3400'u32
    ## int get_frameCount()
    ## UnityEngine.Time::get_frameCount/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_TIME_GET_FRAME_COUNT_ARITY* = 0
  AOWL_SYM_TIME_GET_FRAME_COUNT_OWNERS* = 1
  AOWL_SYM_TIME_GET_FRAME_COUNT_NAME* = "UnityEngine.Time::get_frameCount/0"
  AOWL_SYM_TIME_GET_FRAME_COUNT_PROLOGUE* = [0x48'u8, 0x83'u8, 0xEC'u8, 0x28'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0x5D'u8, 0x16'u8, 0xE2'u8, 0x01'u8, 0x48'u8, 0x85'u8, 0xC0'u8, 0x75'u8, 0x18'u8]

const
  AOWL_SYM_SCENE_GET_NAME* = 0x052C3A90'u32
    ## string GetNameInternal(int sceneHandle)
    ## UnityEngine.SceneManagement.Scene::GetNameInternal/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_SCENE_GET_NAME_ARITY* = 1
  AOWL_SYM_SCENE_GET_NAME_OWNERS* = 1
  AOWL_SYM_SCENE_GET_NAME_NAME* = "UnityEngine.SceneManagement.Scene::GetNameInternal/1"
  AOWL_SYM_SCENE_GET_NAME_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0x53'u8, 0x14'u8, 0xE1'u8, 0x01'u8, 0x8B'u8, 0xD9'u8, 0x48'u8]

const
  AOWL_SYM_SCENE_GET_IS_LOADED* = 0x052C3B40'u32
    ## bool GetIsLoadedInternal(int sceneHandle)
    ## UnityEngine.SceneManagement.Scene::GetIsLoadedInternal/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_SCENE_GET_IS_LOADED_ARITY* = 1
  AOWL_SYM_SCENE_GET_IS_LOADED_OWNERS* = 1
  AOWL_SYM_SCENE_GET_IS_LOADED_NAME* = "UnityEngine.SceneManagement.Scene::GetIsLoadedInternal/1"
  AOWL_SYM_SCENE_GET_IS_LOADED_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0xB3'u8, 0x13'u8, 0xE1'u8, 0x01'u8, 0x8B'u8, 0xD9'u8, 0x48'u8]

const
  AOWL_SYM_SCENE_GET_ROOT_COUNT* = 0x052C3BE0'u32
    ## int GetRootCountInternal(int sceneHandle)
    ## UnityEngine.SceneManagement.Scene::GetRootCountInternal/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_SCENE_GET_ROOT_COUNT_ARITY* = 1
  AOWL_SYM_SCENE_GET_ROOT_COUNT_OWNERS* = 1
  AOWL_SYM_SCENE_GET_ROOT_COUNT_NAME* = "UnityEngine.SceneManagement.Scene::GetRootCountInternal/1"
  AOWL_SYM_SCENE_GET_ROOT_COUNT_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0x23'u8, 0x13'u8, 0xE1'u8, 0x01'u8, 0x8B'u8, 0xD9'u8, 0x48'u8]

const
  AOWL_SYM_SCENEMGR_GET_COUNT* = 0x052C4830'u32
    ## int get_sceneCount()
    ## UnityEngine.SceneManagement.SceneManager::get_sceneCount/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_SCENEMGR_GET_COUNT_ARITY* = 0
  AOWL_SYM_SCENEMGR_GET_COUNT_OWNERS* = 1
  AOWL_SYM_SCENEMGR_GET_COUNT_NAME* = "UnityEngine.SceneManagement.SceneManager::get_sceneCount/0"
  AOWL_SYM_SCENEMGR_GET_COUNT_PROLOGUE* = [0x48'u8, 0x83'u8, 0xEC'u8, 0x28'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0x05'u8, 0x07'u8, 0xE1'u8, 0x01'u8, 0x48'u8, 0x85'u8, 0xC0'u8, 0x75'u8, 0x18'u8]

const
  AOWL_SYM_SCENEMGR_GET_AT* = 0x052C4A40'u32
    ## Scene GetSceneAt(int index)
    ## UnityEngine.SceneManagement.SceneManager::GetSceneAt/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_SCENEMGR_GET_AT_ARITY* = 1
  AOWL_SYM_SCENEMGR_GET_AT_OWNERS* = 1
  AOWL_SYM_SCENEMGR_GET_AT_NAME* = "UnityEngine.SceneManagement.SceneManager::GetSceneAt/1"
  AOWL_SYM_SCENEMGR_GET_AT_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x80'u8, 0x3D'u8, 0xFE'u8, 0x04'u8, 0xE1'u8, 0x01'u8, 0x00'u8, 0x8B'u8, 0xD9'u8, 0x75'u8]

const
  AOWL_SYM_UNITYEVENT_INVOKE* = 0x052C34A0'u32
    ## void Invoke()
    ## UnityEngine.Events.UnityEvent::Invoke/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_UNITYEVENT_INVOKE_ARITY* = 0
  AOWL_SYM_UNITYEVENT_INVOKE_OWNERS* = 1
  AOWL_SYM_UNITYEVENT_INVOKE_NAME* = "UnityEngine.Events.UnityEvent::Invoke/0"
  AOWL_SYM_UNITYEVENT_INVOKE_PROLOGUE* = [0x48'u8, 0x89'u8, 0x5C'u8, 0x24'u8, 0x18'u8, 0x48'u8, 0x89'u8, 0x6C'u8, 0x24'u8, 0x20'u8, 0x57'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x80'u8]

const
  AOWL_SYM_BUTTON_PRESS* = 0x0539A7A0'u32
    ## void Press()
    ## UnityEngine.UI.Button::Press/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_BUTTON_PRESS_ARITY* = 0
  AOWL_SYM_BUTTON_PRESS_OWNERS* = 1
  AOWL_SYM_BUTTON_PRESS_NAME* = "UnityEngine.UI.Button::Press/0"
  AOWL_SYM_BUTTON_PRESS_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x80'u8, 0x3D'u8, 0xCC'u8, 0xC5'u8, 0xD3'u8, 0x01'u8, 0x00'u8, 0x48'u8, 0x8B'u8, 0xD9'u8]

const
  AOWL_SYM_GRAPHIC_SET_RAYCAST* = 0x053AD7F0'u32
    ## void set_raycastTarget(bool value)
    ## UnityEngine.UI.Graphic::set_raycastTarget/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_GRAPHIC_SET_RAYCAST_ARITY* = 1
  AOWL_SYM_GRAPHIC_SET_RAYCAST_OWNERS* = 1
  AOWL_SYM_GRAPHIC_SET_RAYCAST_NAME* = "UnityEngine.UI.Graphic::set_raycastTarget/1"
  AOWL_SYM_GRAPHIC_SET_RAYCAST_PROLOGUE* = [0x48'u8, 0x89'u8, 0x5C'u8, 0x24'u8, 0x10'u8, 0x57'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x80'u8, 0x3D'u8, 0xDA'u8, 0x95'u8, 0xD2'u8, 0x01'u8]

const
  AOWL_SYM_SLIDER_SET_MIN* = 0x055B3250'u32
    ## void set_minValue(float value)
    ## UnityEngine.UI.Slider::set_minValue/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_SLIDER_SET_MIN_ARITY* = 1
  AOWL_SYM_SLIDER_SET_MIN_OWNERS* = 1
  AOWL_SYM_SLIDER_SET_MIN_NAME* = "UnityEngine.UI.Slider::set_minValue/1"
  AOWL_SYM_SLIDER_SET_MIN_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x30'u8, 0x80'u8, 0x3D'u8, 0xD4'u8, 0x4E'u8, 0xB2'u8, 0x01'u8, 0x00'u8, 0x48'u8, 0x8B'u8, 0xD9'u8]

const
  AOWL_SYM_SLIDER_SET_MAX* = 0x055B32D0'u32
    ## void set_maxValue(float value)
    ## UnityEngine.UI.Slider::set_maxValue/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_SLIDER_SET_MAX_ARITY* = 1
  AOWL_SYM_SLIDER_SET_MAX_OWNERS* = 1
  AOWL_SYM_SLIDER_SET_MAX_NAME* = "UnityEngine.UI.Slider::set_maxValue/1"
  AOWL_SYM_SLIDER_SET_MAX_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x30'u8, 0x80'u8, 0x3D'u8, 0x55'u8, 0x4E'u8, 0xB2'u8, 0x01'u8, 0x00'u8, 0x48'u8, 0x8B'u8, 0xD9'u8]

const
  AOWL_SYM_SLIDER_SET_NO_NOTIFY* = 0x055B3420'u32
    ## void SetValueWithoutNotify(float input)
    ## UnityEngine.UI.Slider::SetValueWithoutNotify/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_SLIDER_SET_NO_NOTIFY_ARITY* = 1
  AOWL_SYM_SLIDER_SET_NO_NOTIFY_OWNERS* = 1
  AOWL_SYM_SLIDER_SET_NO_NOTIFY_NAME* = "UnityEngine.UI.Slider::SetValueWithoutNotify/1"
  AOWL_SYM_SLIDER_SET_NO_NOTIFY_PROLOGUE* = [0x4C'u8, 0x8B'u8, 0x09'u8, 0x45'u8, 0x33'u8, 0xC0'u8, 0x49'u8, 0x8B'u8, 0x81'u8, 0x88'u8, 0x04'u8, 0x00'u8, 0x00'u8, 0x4D'u8, 0x8B'u8, 0x89'u8]

const
  AOWL_SYM_SLIDER_UPDATE_VISUALS* = 0x055B4610'u32
    ## void UpdateVisuals()
    ## UnityEngine.UI.Slider::UpdateVisuals/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_SLIDER_UPDATE_VISUALS_ARITY* = 0
  AOWL_SYM_SLIDER_UPDATE_VISUALS_OWNERS* = 1
  AOWL_SYM_SLIDER_UPDATE_VISUALS_NAME* = "UnityEngine.UI.Slider::UpdateVisuals/0"
  AOWL_SYM_SLIDER_UPDATE_VISUALS_PROLOGUE* = [0x48'u8, 0x89'u8, 0x5C'u8, 0x24'u8, 0x20'u8, 0x57'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x70'u8, 0x80'u8, 0x3D'u8, 0x17'u8, 0x3B'u8, 0xB2'u8, 0x01'u8]

const
  AOWL_SYM_TOGGLE_SET_IS_ON* = 0x055BA430'u32
    ## void set_isOn(bool value)
    ## UnityEngine.UI.Toggle::set_isOn/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_TOGGLE_SET_IS_ON_ARITY* = 1
  AOWL_SYM_TOGGLE_SET_IS_ON_OWNERS* = 1
  AOWL_SYM_TOGGLE_SET_IS_ON_NAME* = "UnityEngine.UI.Toggle::set_isOn/1"
  AOWL_SYM_TOGGLE_SET_IS_ON_PROLOGUE* = [0x45'u8, 0x33'u8, 0xC9'u8, 0x41'u8, 0xB0'u8, 0x01'u8, 0xE9'u8, 0x15'u8, 0x00'u8, 0x00'u8, 0x00'u8, 0xCC'u8, 0xCC'u8, 0xCC'u8, 0xCC'u8, 0xCC'u8]

const
  AOWL_SYM_TOGGLE_SET_NO_NOTIFY* = 0x055BA440'u32
    ## void SetIsOnWithoutNotify(bool value)
    ## UnityEngine.UI.Toggle::SetIsOnWithoutNotify/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_TOGGLE_SET_NO_NOTIFY_ARITY* = 1
  AOWL_SYM_TOGGLE_SET_NO_NOTIFY_OWNERS* = 1
  AOWL_SYM_TOGGLE_SET_NO_NOTIFY_NAME* = "UnityEngine.UI.Toggle::SetIsOnWithoutNotify/1"
  AOWL_SYM_TOGGLE_SET_NO_NOTIFY_PROLOGUE* = [0x45'u8, 0x33'u8, 0xC9'u8, 0x45'u8, 0x33'u8, 0xC0'u8, 0xE9'u8, 0x05'u8, 0x00'u8, 0x00'u8, 0x00'u8, 0xCC'u8, 0xCC'u8, 0xCC'u8, 0xCC'u8, 0xCC'u8]

const
  AOWL_SYM_TYPE_FROM_HANDLE* = 0x0458B020'u32
    ## Type GetTypeFromHandle(RuntimeTypeHandle handle)
    ## System.Type::GetTypeFromHandle/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_TYPE_FROM_HANDLE_ARITY* = 1
  AOWL_SYM_TYPE_FROM_HANDLE_OWNERS* = 1
  AOWL_SYM_TYPE_FROM_HANDLE_NAME* = "System.Type::GetTypeFromHandle/1"
  AOWL_SYM_TYPE_FROM_HANDLE_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x80'u8, 0x3D'u8, 0xC2'u8, 0x1E'u8, 0xB4'u8, 0x02'u8, 0x00'u8, 0x48'u8, 0x8B'u8, 0xD9'u8]

const
  AOWL_SYM_TMP_SET_TEXT* = 0x051BC1E0'u32
    ## void set_text(string value)
    ## TMPro.TMP_Text::set_text/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_TMP_SET_TEXT_ARITY* = 1
  AOWL_SYM_TMP_SET_TEXT_OWNERS* = 1
  AOWL_SYM_TMP_SET_TEXT_NAME* = "TMPro.TMP_Text::set_text/1"
  AOWL_SYM_TMP_SET_TEXT_PROLOGUE* = [0x48'u8, 0x89'u8, 0x5C'u8, 0x24'u8, 0x08'u8, 0x57'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x80'u8, 0xB9'u8, 0xE8'u8, 0x00'u8, 0x00'u8, 0x00'u8]

const
  AOWL_SYM_TMP_SET_PROPS_CHANGED* = 0x051BEA30'u32
    ## void set_havePropertiesChanged(bool value)
    ## TMPro.TMP_Text::set_havePropertiesChanged/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_TMP_SET_PROPS_CHANGED_ARITY* = 1
  AOWL_SYM_TMP_SET_PROPS_CHANGED_OWNERS* = 1
  AOWL_SYM_TMP_SET_PROPS_CHANGED_NAME* = "TMPro.TMP_Text::set_havePropertiesChanged/1"
  AOWL_SYM_TMP_SET_PROPS_CHANGED_PROLOGUE* = [0x38'u8, 0x91'u8, 0x78'u8, 0x03'u8, 0x00'u8, 0x00'u8, 0x74'u8, 0x1A'u8, 0x88'u8, 0x91'u8, 0x78'u8, 0x03'u8, 0x00'u8, 0x00'u8, 0x48'u8, 0x8B'u8]

const
  AOWL_SYM_TMP_SET_PARENT_ALIGN* = 0x051903A0'u32
    ## void SetParentAndAlign(GameObject child, GameObject parent)
    ## TMPro.TMP_DefaultControls::SetParentAndAlign/2 -- section il2cpp, owners 1, arity 2
  AOWL_SYM_TMP_SET_PARENT_ALIGN_ARITY* = 2
  AOWL_SYM_TMP_SET_PARENT_ALIGN_OWNERS* = 1
  AOWL_SYM_TMP_SET_PARENT_ALIGN_NAME* = "TMPro.TMP_DefaultControls::SetParentAndAlign/2"
  AOWL_SYM_TMP_SET_PARENT_ALIGN_PROLOGUE* = [0x48'u8, 0x89'u8, 0x5C'u8, 0x24'u8, 0x10'u8, 0x57'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x80'u8, 0x3D'u8, 0x68'u8, 0x13'u8, 0xF4'u8, 0x01'u8]

const
  AOWL_SYM_TMPUGUI_FORCE_MESH* = 0x05180F80'u32
    ## void ForceMeshUpdate(bool ignoreActiveState, bool forceTextReparsing)
    ## TMPro.TextMeshProUGUI::ForceMeshUpdate/2 -- section il2cpp, owners 1, arity 2
  AOWL_SYM_TMPUGUI_FORCE_MESH_ARITY* = 2
  AOWL_SYM_TMPUGUI_FORCE_MESH_OWNERS* = 1
  AOWL_SYM_TMPUGUI_FORCE_MESH_NAME* = "TMPro.TextMeshProUGUI::ForceMeshUpdate/2"
  AOWL_SYM_TMPUGUI_FORCE_MESH_PROLOGUE* = [0x48'u8, 0x89'u8, 0x5C'u8, 0x24'u8, 0x08'u8, 0x57'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x80'u8, 0x3D'u8, 0x2F'u8, 0x07'u8, 0xF5'u8, 0x01'u8]

const
  AOWL_SYM_TMPPRO_FORCE_MESH* = 0x05174690'u32
    ## void ForceMeshUpdate(bool ignoreActiveState, bool forceTextReparsing)
    ## TMPro.TextMeshPro::ForceMeshUpdate/2 -- section il2cpp, owners 1, arity 2
  AOWL_SYM_TMPPRO_FORCE_MESH_ARITY* = 2
  AOWL_SYM_TMPPRO_FORCE_MESH_OWNERS* = 1
  AOWL_SYM_TMPPRO_FORCE_MESH_NAME* = "TMPro.TextMeshPro::ForceMeshUpdate/2"
  AOWL_SYM_TMPPRO_FORCE_MESH_PROLOGUE* = [0x88'u8, 0x91'u8, 0xB4'u8, 0x06'u8, 0x00'u8, 0x00'u8, 0x33'u8, 0xD2'u8, 0xC6'u8, 0x81'u8, 0x78'u8, 0x03'u8, 0x00'u8, 0x00'u8, 0x01'u8, 0xE9'u8]

const
  AOWL_SYM_LOCTEXT_SET_LABEL* = 0x0140FE70'u32
    ## void SetLabelText(string text)
    ## EFT.UI.LocalizedText::SetLabelText/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_LOCTEXT_SET_LABEL_ARITY* = 1
  AOWL_SYM_LOCTEXT_SET_LABEL_OWNERS* = 1
  AOWL_SYM_LOCTEXT_SET_LABEL_NAME* = "EFT.UI.LocalizedText::SetLabelText/1"
  AOWL_SYM_LOCTEXT_SET_LABEL_PROLOGUE* = [0x48'u8, 0x89'u8, 0x5C'u8, 0x24'u8, 0x08'u8, 0x57'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x60'u8, 0x48'u8, 0x8B'u8, 0xFA'u8, 0x48'u8, 0x8B'u8, 0xD9'u8]

const
  AOWL_SYM_SETTINGSSCREEN_SHOW1* = 0x01720DE0'u32
    ## void ShowScreen(ESettingsGroup group)
    ## EFT.UI.Settings.SettingsScreen::ShowScreen/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_SETTINGSSCREEN_SHOW1_ARITY* = 1
  AOWL_SYM_SETTINGSSCREEN_SHOW1_OWNERS* = 1
  AOWL_SYM_SETTINGSSCREEN_SHOW1_NAME* = "EFT.UI.Settings.SettingsScreen::ShowScreen/1"
  AOWL_SYM_SETTINGSSCREEN_SHOW1_PROLOGUE* = [0x48'u8, 0x89'u8, 0x5C'u8, 0x24'u8, 0x08'u8, 0x48'u8, 0x89'u8, 0x74'u8, 0x24'u8, 0x10'u8, 0x57'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x30'u8, 0x80'u8]

const
  AOWL_SYM_SETTINGSTAB_SET_SEL* = 0x0171BCA0'u32
    ## void set_IsSelected(bool value)
    ## EFT.UI.Settings.SettingsTab::set_IsSelected/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_SETTINGSTAB_SET_SEL_ARITY* = 1
  AOWL_SYM_SETTINGSTAB_SET_SEL_OWNERS* = 1
  AOWL_SYM_SETTINGSTAB_SET_SEL_NAME* = "EFT.UI.Settings.SettingsTab::set_IsSelected/1"
  AOWL_SYM_SETTINGSTAB_SET_SEL_PROLOGUE* = [0x48'u8, 0x89'u8, 0x5C'u8, 0x24'u8, 0x10'u8, 0x56'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0x37'u8, 0x88'u8, 0x9B'u8]

const
  AOWL_SYM_GAMESETTINGSTAB_UPDATE* = 0x01703680'u32
    ## void Update()
    ## EFT.UI.Settings.GameSettingsTab::Update/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_GAMESETTINGSTAB_UPDATE_ARITY* = 0
  AOWL_SYM_GAMESETTINGSTAB_UPDATE_OWNERS* = 1
  AOWL_SYM_GAMESETTINGSTAB_UPDATE_NAME* = "EFT.UI.Settings.GameSettingsTab::Update/0"
  AOWL_SYM_GAMESETTINGSTAB_UPDATE_PROLOGUE* = [0x40'u8, 0x57'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x40'u8, 0x80'u8, 0x3D'u8, 0xE2'u8, 0xAC'u8, 0x9B'u8, 0x05'u8, 0x00'u8, 0x48'u8, 0x8B'u8, 0xF9'u8]

const
  AOWL_SYM_TARKOVAPP_UPDATE* = 0x00977B10'u32
    ## void Update()
    ## EFT.TarkovApplication::Update/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_TARKOVAPP_UPDATE_ARITY* = 0
  AOWL_SYM_TARKOVAPP_UPDATE_OWNERS* = 1
  AOWL_SYM_TARKOVAPP_UPDATE_NAME* = "EFT.TarkovApplication::Update/0"
  AOWL_SYM_TARKOVAPP_UPDATE_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x48'u8, 0x8B'u8, 0x99'u8, 0x10'u8, 0x01'u8, 0x00'u8, 0x00'u8, 0x48'u8, 0x85'u8, 0xDB'u8]

const
  AOWL_SYM_GAMEWORLD_REGISTER* = 0x025038C0'u32
    ## void RegisterPlayer(IPlayer iPlayer)
    ## EFT.GameWorld::RegisterPlayer/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_GAMEWORLD_REGISTER_ARITY* = 1
  AOWL_SYM_GAMEWORLD_REGISTER_OWNERS* = 1
  AOWL_SYM_GAMEWORLD_REGISTER_NAME* = "EFT.GameWorld::RegisterPlayer/1"
  AOWL_SYM_GAMEWORLD_REGISTER_PROLOGUE* = [0x40'u8, 0x56'u8, 0x41'u8, 0x57'u8, 0x48'u8, 0x81'u8, 0xEC'u8, 0x88'u8, 0x00'u8, 0x00'u8, 0x00'u8, 0x80'u8, 0x3D'u8, 0x42'u8, 0xF6'u8, 0xBB'u8]

const
  AOWL_SYM_GAMEWORLD_TICK_UPDATE* = 0x0251C6C0'u32
    ## void Update()
    ## EFT.GameWorldUnityTickListener::Update/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_GAMEWORLD_TICK_UPDATE_ARITY* = 0
  AOWL_SYM_GAMEWORLD_TICK_UPDATE_OWNERS* = 1
  AOWL_SYM_GAMEWORLD_TICK_UPDATE_NAME* = "EFT.GameWorldUnityTickListener::Update/0"
  AOWL_SYM_GAMEWORLD_TICK_UPDATE_PROLOGUE* = [0x40'u8, 0x57'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x80'u8, 0x3D'u8, 0xD0'u8, 0x68'u8, 0xBA'u8, 0x04'u8, 0x00'u8, 0x48'u8, 0x8B'u8, 0xF9'u8]

const
  AOWL_SYM_BOTSPAWNER_ADD_PLAYER* = 0x02563AE0'u32
    ## void AddPlayer(Player player)
    ## EFT.BotSpawner::AddPlayer/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_BOTSPAWNER_ADD_PLAYER_ARITY* = 1
  AOWL_SYM_BOTSPAWNER_ADD_PLAYER_OWNERS* = 1
  AOWL_SYM_BOTSPAWNER_ADD_PLAYER_NAME* = "EFT.BotSpawner::AddPlayer/1"
  AOWL_SYM_BOTSPAWNER_ADD_PLAYER_PROLOGUE* = [0x48'u8, 0x89'u8, 0x5C'u8, 0x24'u8, 0x18'u8, 0x57'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x80'u8, 0x3D'u8, 0x99'u8, 0xF6'u8, 0xB5'u8, 0x04'u8]

const
  AOWL_SYM_BOTOWNER_PREACTIVATE* = 0x00813F60'u32
    ## void PreActivate(BotZone zone, GameDateTime time, BotsGroup group, AICoversData covers, bool autoActivate)
    ## EFT.BotOwner::PreActivate/5 -- section il2cpp, owners 1, arity 5
  AOWL_SYM_BOTOWNER_PREACTIVATE_ARITY* = 5
  AOWL_SYM_BOTOWNER_PREACTIVATE_OWNERS* = 1
  AOWL_SYM_BOTOWNER_PREACTIVATE_NAME* = "EFT.BotOwner::PreActivate/5"
  AOWL_SYM_BOTOWNER_PREACTIVATE_PROLOGUE* = [0x48'u8, 0x89'u8, 0x5C'u8, 0x24'u8, 0x10'u8, 0x48'u8, 0x89'u8, 0x6C'u8, 0x24'u8, 0x18'u8, 0x48'u8, 0x89'u8, 0x74'u8, 0x24'u8, 0x20'u8, 0x57'u8]

const
  AOWL_SYM_BOTOWNER_UPDATE_MANUAL* = 0x0081B7C0'u32
    ## void UpdateManual()
    ## EFT.BotOwner::UpdateManual/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_BOTOWNER_UPDATE_MANUAL_ARITY* = 0
  AOWL_SYM_BOTOWNER_UPDATE_MANUAL_OWNERS* = 1
  AOWL_SYM_BOTOWNER_UPDATE_MANUAL_NAME* = "EFT.BotOwner::UpdateManual/0"
  AOWL_SYM_BOTOWNER_UPDATE_MANUAL_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x81'u8, 0xEC'u8, 0xA0'u8, 0x00'u8, 0x00'u8, 0x00'u8, 0x80'u8, 0x3D'u8, 0x08'u8, 0xCF'u8, 0x89'u8, 0x06'u8, 0x00'u8]

const
  AOWL_SYM_LODBIAS_ON_POST_RENDER* = 0x01263B10'u32
    ## void OnPostRender()
    ## EFT.CameraControl.CameraLodBiasController::OnPostRender/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_LODBIAS_ON_POST_RENDER_ARITY* = 0
  AOWL_SYM_LODBIAS_ON_POST_RENDER_OWNERS* = 1
  AOWL_SYM_LODBIAS_ON_POST_RENDER_NAME* = "EFT.CameraControl.CameraLodBiasController::OnPostRender/0"
  AOWL_SYM_LODBIAS_ON_POST_RENDER_PROLOGUE* = [0x48'u8, 0x83'u8, 0xEC'u8, 0x38'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0x4D'u8, 0xF7'u8, 0xE6'u8, 0x05'u8, 0x0F'u8, 0x29'u8, 0x74'u8, 0x24'u8, 0x20'u8]

const
  AOWL_SYM_ONRENDEROBJ_MANAGER* = 0x01F46910'u32
    ## void OnRenderObject()
    ## OnRenderObjectManager::OnRenderObject/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_ONRENDEROBJ_MANAGER_ARITY* = 0
  AOWL_SYM_ONRENDEROBJ_MANAGER_OWNERS* = 1
  AOWL_SYM_ONRENDEROBJ_MANAGER_NAME* = "OnRenderObjectManager::OnRenderObject/0"
  AOWL_SYM_ONRENDEROBJ_MANAGER_PROLOGUE* = [0x40'u8, 0x55'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x80'u8, 0x3D'u8, 0x83'u8, 0xA8'u8, 0x17'u8, 0x05'u8, 0x00'u8, 0x48'u8, 0x8B'u8, 0xE9'u8]

const
  AOWL_SYMC_COMPONENT_GET_GAMEOBJECT* = 0x011F57E0'u32
    ## GameObject get_gameObject()
    ## UnityEngine.Component::get_gameObject/0 -- section il2cpp, owners 52, arity 0
    ## CALL ONLY (52 owners). why: 52 owners: every Component subclass folds to this one two-instruction body. Reading a GameObject off a Component we already hold is correct for whatever the receiver is; a detour here would fire for the whole engine.
  AOWL_SYMC_COMPONENT_GET_GAMEOBJECT_ARITY* = 0
  AOWL_SYMC_COMPONENT_GET_GAMEOBJECT_OWNERS* = 52
  AOWL_SYMC_COMPONENT_GET_GAMEOBJECT_NAME* = "UnityEngine.Component::get_gameObject/0"
  AOWL_SYMC_COMPONENT_GET_GAMEOBJECT_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0xFB'u8, 0xEC'u8, 0xED'u8, 0x05'u8, 0x48'u8, 0x8B'u8, 0xD9'u8]

const
  AOWL_SYMC_COMPONENT_GET_TRANSFORM* = 0x0073B0F0'u32
    ## Transform get_transform()
    ## UnityEngine.Component::get_transform/0 -- section il2cpp, owners 15, arity 0
    ## CALL ONLY (15 owners). why: 15 owners, same folded accessor shape as get_gameObject. Call-only for the same reason.
  AOWL_SYMC_COMPONENT_GET_TRANSFORM_ARITY* = 0
  AOWL_SYMC_COMPONENT_GET_TRANSFORM_OWNERS* = 15
  AOWL_SYMC_COMPONENT_GET_TRANSFORM_NAME* = "UnityEngine.Component::get_transform/0"
  AOWL_SYMC_COMPONENT_GET_TRANSFORM_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0xE3'u8, 0x93'u8, 0x99'u8, 0x06'u8, 0x48'u8, 0x8B'u8, 0xD9'u8]

const
  AOWL_SYMC_BEHAVIOUR_SET_ENABLED* = 0x00C4C760'u32
    ## void set_enabled(bool value)
    ## UnityEngine.Behaviour::set_enabled/1 -- section il2cpp, owners 32, arity 1
    ## CALL ONLY (32 owners). why: 32 owners. Enabling the Behaviour instance we are holding is correct code; detouring it would intercept every enable in the process.
  AOWL_SYMC_BEHAVIOUR_SET_ENABLED_ARITY* = 1
  AOWL_SYMC_BEHAVIOUR_SET_ENABLED_OWNERS* = 32
  AOWL_SYMC_BEHAVIOUR_SET_ENABLED_NAME* = "UnityEngine.Behaviour::set_enabled/1"
  AOWL_SYMC_BEHAVIOUR_SET_ENABLED_PROLOGUE* = [0x48'u8, 0x89'u8, 0x5C'u8, 0x24'u8, 0x08'u8, 0x57'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0x4F'u8, 0x7D'u8, 0x48'u8]

const
  AOWL_SYMC_TF_GET_ROOT* = 0x052B9C50'u32
    ## Transform get_root()
    ## UnityEngine.Transform::get_root/0 -- section il2cpp, owners 2, arity 0
    ## CALL ONLY (2 owners). why: 2 owners. Walking up from a live Transform to its Canvas root is the debug overlay parenting step, and the receiver decides the answer.
  AOWL_SYMC_TF_GET_ROOT_ARITY* = 0
  AOWL_SYMC_TF_GET_ROOT_OWNERS* = 2
  AOWL_SYMC_TF_GET_ROOT_NAME* = "UnityEngine.Transform::get_root/0"
  AOWL_SYMC_TF_GET_ROOT_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0x4B'u8, 0xAF'u8, 0xE1'u8, 0x01'u8, 0x48'u8, 0x8B'u8, 0xD9'u8]

const
  AOWL_SYMC_SCREEN_GET_WIDTH* = 0x0501B760'u32
    ## int get_width()
    ## UnityEngine.Screen::get_width/0 -- section il2cpp, owners 2, arity 0
    ## CALL ONLY (2 owners). why: 2 owners, a static with no receiver at all. Reading the backbuffer width cannot be wrong for a caller; only a detour could be.
  AOWL_SYMC_SCREEN_GET_WIDTH_ARITY* = 0
  AOWL_SYMC_SCREEN_GET_WIDTH_OWNERS* = 2
  AOWL_SYMC_SCREEN_GET_WIDTH_NAME* = "UnityEngine.Screen::get_width/0"
  AOWL_SYMC_SCREEN_GET_WIDTH_PROLOGUE* = [0x48'u8, 0x83'u8, 0xEC'u8, 0x28'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0x9D'u8, 0x78'u8, 0x0B'u8, 0x02'u8, 0x48'u8, 0x85'u8, 0xC0'u8, 0x75'u8, 0x18'u8]

const
  AOWL_SYMC_SCREEN_GET_HEIGHT* = 0x0501B7B0'u32
    ## int get_height()
    ## UnityEngine.Screen::get_height/0 -- section il2cpp, owners 2, arity 0
    ## CALL ONLY (2 owners). why: 2 owners, static, exactly as get_width. Used together with it for the overlay layout.
  AOWL_SYMC_SCREEN_GET_HEIGHT_ARITY* = 0
  AOWL_SYMC_SCREEN_GET_HEIGHT_OWNERS* = 2
  AOWL_SYMC_SCREEN_GET_HEIGHT_NAME* = "UnityEngine.Screen::get_height/0"
  AOWL_SYMC_SCREEN_GET_HEIGHT_PROLOGUE* = [0x48'u8, 0x83'u8, 0xEC'u8, 0x28'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0x55'u8, 0x78'u8, 0x0B'u8, 0x02'u8, 0x48'u8, 0x85'u8, 0xC0'u8, 0x75'u8, 0x18'u8]

const
  AOWL_SYMC_TF_GET_PARENT* = 0x052B81D0'u32
    ## Transform get_parent()
    ## UnityEngine.Transform::get_parent/0 -- section il2cpp, owners 3, arity 0
    ## CALL ONLY (3 owners). why: 3 owners -- the generator caught this one; it was written as a plain symbol first and rejected. Walking up from a live Transform is receiver-decided and safe to call.
  AOWL_SYMC_TF_GET_PARENT_ARITY* = 0
  AOWL_SYMC_TF_GET_PARENT_OWNERS* = 3
  AOWL_SYMC_TF_GET_PARENT_NAME* = "UnityEngine.Transform::get_parent/0"
  AOWL_SYMC_TF_GET_PARENT_PROLOGUE* = [0x40'u8, 0x53'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x20'u8, 0x48'u8, 0x8B'u8, 0x05'u8, 0xB3'u8, 0xC9'u8, 0xE1'u8, 0x01'u8, 0x48'u8, 0x8B'u8, 0xD9'u8]

const
  AOWL_SYM_SAIN_MOVER_SPRINT* = 0x01A2D700'u32
    ## void Sprint(bool val, bool withDebugCallback)
    ## BotMover::Sprint/2 -- section il2cpp, owners 1, arity 2
  AOWL_SYM_SAIN_MOVER_SPRINT_ARITY* = 2
  AOWL_SYM_SAIN_MOVER_SPRINT_OWNERS* = 1
  AOWL_SYM_SAIN_MOVER_SPRINT_NAME* = "BotMover::Sprint/2"
  AOWL_SYM_SAIN_MOVER_SPRINT_PROLOGUE* = [0x48'u8, 0x89'u8, 0x5C'u8, 0x24'u8, 0x08'u8, 0x57'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x30'u8, 0x0F'u8, 0xB6'u8, 0xFA'u8, 0x48'u8, 0x8B'u8, 0xD9'u8]

const
  AOWL_SYM_SAIN_MOVER_STOP* = 0x01A2D600'u32
    ## void Stop()
    ## BotMover::Stop/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_SAIN_MOVER_STOP_ARITY* = 0
  AOWL_SYM_SAIN_MOVER_STOP_OWNERS* = 1
  AOWL_SYM_SAIN_MOVER_STOP_NAME* = "BotMover::Stop/0"
  AOWL_SYM_SAIN_MOVER_STOP_PROLOGUE* = [0x48'u8, 0x83'u8, 0xEC'u8, 0x28'u8, 0x48'u8, 0x8B'u8, 0x81'u8, 0x80'u8, 0x00'u8, 0x00'u8, 0x00'u8, 0xC6'u8, 0x81'u8, 0x38'u8, 0x01'u8, 0x00'u8]

const
  AOWL_SYM_SAIN_STEERING_LOOKTO* = 0x01A3B690'u32
    ## void LookToPoint(Vector3 point)
    ## BotSteering::LookToPoint/1 -- section il2cpp, owners 1, arity 1
  AOWL_SYM_SAIN_STEERING_LOOKTO_ARITY* = 1
  AOWL_SYM_SAIN_STEERING_LOOKTO_OWNERS* = 1
  AOWL_SYM_SAIN_STEERING_LOOKTO_NAME* = "BotSteering::LookToPoint/1"
  AOWL_SYM_SAIN_STEERING_LOOKTO_PROLOGUE* = [0x48'u8, 0x83'u8, 0xEC'u8, 0x28'u8, 0x48'u8, 0x8B'u8, 0x41'u8, 0x10'u8, 0x48'u8, 0x85'u8, 0xC0'u8, 0x74'u8, 0x3C'u8, 0x48'u8, 0x8B'u8, 0x40'u8]

const
  AOWL_SYM_SAIN_SHOOTDATA_SHOOT* = 0x01AF7940'u32
    ## bool Shoot()
    ## ShootData::Shoot/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_SAIN_SHOOTDATA_SHOOT_ARITY* = 0
  AOWL_SYM_SAIN_SHOOTDATA_SHOOT_OWNERS* = 1
  AOWL_SYM_SAIN_SHOOTDATA_SHOOT_NAME* = "ShootData::Shoot/0"
  AOWL_SYM_SAIN_SHOOTDATA_SHOOT_PROLOGUE* = [0x48'u8, 0x89'u8, 0x5C'u8, 0x24'u8, 0x20'u8, 0x57'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x40'u8, 0x80'u8, 0x3D'u8, 0x0A'u8, 0x81'u8, 0x5C'u8, 0x05'u8]

const
  AOWL_SYM_SAIN_BOTOWNER_STOPMOVE* = 0x0081C970'u32
    ## void StopMove()
    ## EFT.BotOwner::StopMove/0 -- section il2cpp, owners 1, arity 0
  AOWL_SYM_SAIN_BOTOWNER_STOPMOVE_ARITY* = 0
  AOWL_SYM_SAIN_BOTOWNER_STOPMOVE_OWNERS* = 1
  AOWL_SYM_SAIN_BOTOWNER_STOPMOVE_NAME* = "EFT.BotOwner::StopMove/0"
  AOWL_SYM_SAIN_BOTOWNER_STOPMOVE_PROLOGUE* = [0x48'u8, 0x83'u8, 0xEC'u8, 0x28'u8, 0x48'u8, 0x8B'u8, 0x81'u8, 0xD0'u8, 0x03'u8, 0x00'u8, 0x00'u8, 0x48'u8, 0x85'u8, 0xC0'u8, 0x74'u8, 0x30'u8]

const
  AOWL_SYM_SAIN_NAVMESH_SAMPLE* = 0x05238930'u32
    ## bool SamplePosition(Vector3 sourcePosition, NavMeshHit hit, float maxDistance, int areaMask)
    ## UnityEngine.AI.NavMesh::SamplePosition/4 -- section il2cpp, owners 1, arity 4
  AOWL_SYM_SAIN_NAVMESH_SAMPLE_ARITY* = 4
  AOWL_SYM_SAIN_NAVMESH_SAMPLE_OWNERS* = 1
  AOWL_SYM_SAIN_NAVMESH_SAMPLE_NAME* = "UnityEngine.AI.NavMesh::SamplePosition/4"
  AOWL_SYM_SAIN_NAVMESH_SAMPLE_PROLOGUE* = [0x48'u8, 0x89'u8, 0x5C'u8, 0x24'u8, 0x08'u8, 0x48'u8, 0x89'u8, 0x74'u8, 0x24'u8, 0x10'u8, 0x57'u8, 0x48'u8, 0x83'u8, 0xEC'u8, 0x30'u8, 0x48'u8]

