/* abi/aowlspt_fieldrefs.h -- GENERATED by tools/fieldrefs.py. DO NOT EDIT.
 *
 * Regenerate:  python tools/fieldrefs.py emit
 * Verify:      python tools/fieldrefs.py check     (exit 5 = drift)
 *
 * Every row was produced by tools/il2cpp_resolve.py's fieldOffsets scan, AFTER
 * tools/fldoff.py:self_check re-derived System.String._stringLength@0x10 and
 * _firstChar@0x14 from the same resolver. No offset in this file was typed by
 * a human.
 *
 * `inst_size_min` is max(offset+width) over the type's instance fields and its
 * bases -- a LOWER BOUND on Il2CppClass.instance_size, which the metadata does
 * not carry. It is the fail-closed direction, and it is weak by construction
 * for the offsets in this very file. The load-bearing checks are the
 * reference-width rule (M4) and klass admission; see aowlspt_hostwrite.h.
 *
 * `klass` / `nklass` are the runtime KLASS ADMISSION SET, filled in by
 * aowl_fr_admit() from receivers the caller vouches for. Zero admitted klasses
 * means every store through this FieldRef is REFUSED.
 */
#ifndef AOWLSPT_FIELDREFS_H
#define AOWLSPT_FIELDREFS_H

#include <stdint.h>

#define AOWL_FR_MAX_KLASS 4

typedef struct AowlFieldRef {
    const char* type_name;      /* metadata type that DECLARES the field      */
    const char* field_name;
    int32_t     off;            /* receiver-relative, from fieldOffsets       */
    int32_t     width;          /* bytes; 0 is impossible here (generator     */
                                /* refuses a width it cannot derive)          */
    int32_t     is_reference;   /* 1 => a managed reference slot (M4 applies) */
    uint32_t    inst_size_min;  /* see the note above                         */
    void*       klass[AOWL_FR_MAX_KLASS];
    int32_t     nklass;
} AowlFieldRef;

/* source: GameAssembly.dll */

/* audit #1  botcap.nim   BotSpawner.MaxBots := 0
 *   EFT.BotSpawner.<MaxBots>k__BackingField : int   (primitive, declared by EFT.BotSpawner)
 */
static AowlFieldRef AOWL_FR_BC_MAXBOTS = {
    "EFT.BotSpawner", "<MaxBots>k__BackingField", 0xc0, 4, 0, 0xd8, { 0, 0, 0, 0 }, 0
};

/* audit #2  botai.nim    BotWeaponManager.IsReady := true
 *   BotWeaponManager.<IsReady>k__BackingField : bool   (primitive, declared by BotWeaponManager)
 */
static AowlFieldRef AOWL_FR_BA_ISREADY = {
    "BotWeaponManager", "<IsReady>k__BackingField", 0x80, 1, 0, 0x95, { 0, 0, 0, 0 }, 0
};

/* audit #3  natesp.nim   Graphic.m_Color, four f32 channels (BUILD TIME only)
 *   UnityEngine.UI.Graphic.m_Color : Color   (valuetype, declared by UnityEngine.UI.Graphic)
 */
static AowlFieldRef AOWL_FR_GRAPHIC_COLOR = {
    "UnityEngine.UI.Graphic", "m_Color", 0x28, 16, 0, 0xa1, { 0, 0, 0, 0 }, 0
};

/* audit #4  nativeui.nim TMP_Text.m_fontAsset := donor's font
 *   TMPro.TMP_Text.m_fontAsset : TMP_FontAsset   (reference, declared by TMPro.TMP_Text)
 */
static AowlFieldRef AOWL_FR_TMP_FONTASSET = {
    "TMPro.TMP_Text", "m_fontAsset", 0x100, 8, 1, 0x6d0, { 0, 0, 0, 0 }, 0
};

/* audit #4  nativeui.nim TMP_Text.m_sharedMaterial := donor's material
 *   TMPro.TMP_Text.m_sharedMaterial : Material   (reference, declared by TMPro.TMP_Text)
 */
static AowlFieldRef AOWL_FR_TMP_SHAREDMAT = {
    "TMPro.TMP_Text", "m_sharedMaterial", 0x118, 8, 1, 0x6d0, { 0, 0, 0, 0 }, 0
};

/* audit #4  nativeui.nim Graphic.m_Material := donor's material
 *   UnityEngine.UI.Graphic.m_Material : Material   (reference, declared by UnityEngine.UI.Graphic)
 */
static AowlFieldRef AOWL_FR_GRAPHIC_MAT = {
    "UnityEngine.UI.Graphic", "m_Material", 0x20, 8, 1, 0xa1, { 0, 0, 0, 0 }, 0
};

/* audit #5  modstab.nim  -- NOW A CALL: Toggle::SetToggleGroup @0x55BA150
 *   UnityEngine.UI.Toggle.m_Group : ToggleGroup   (reference, declared by UnityEngine.UI.Toggle)
 */
static AowlFieldRef AOWL_FR_TOGGLE_GROUP = {
    "UnityEngine.UI.Toggle", "m_Group", 0x110, 8, 1, 0x121, { 0, 0, 0, 0 }, 0
};

/* audit #8  settings    -- NOW A CALL: Toggle::SetIsOnWithoutNotify @0x55BA440
 *   UnityEngine.UI.Toggle.m_IsOn : bool   (primitive, declared by UnityEngine.UI.Toggle)
 */
static AowlFieldRef AOWL_FR_TOGGLE_ISON = {
    "UnityEngine.UI.Toggle", "m_IsOn", 0x120, 1, 0, 0x121, { 0, 0, 0, 0 }, 0
};

/* audit #6/#9 settingswrite/invoke2/version brand: TMP_Text.m_text
 *   TMPro.TMP_Text.m_text : string   (reference, declared by TMPro.TMP_Text)
 */
static AowlFieldRef AOWL_FR_TMP_MTEXT = {
    "TMPro.TMP_Text", "m_text", 0xe0, 8, 1, 0x6d0, { 0, 0, 0, 0 }, 0
};

/* audit #11 mods/textures/redirect.nim EasyBundle._path
 *   Diz.Resources.EasyBundle._path : string   (reference, declared by Diz.Resources.EasyBundle)
 */
static AowlFieldRef AOWL_FR_EB_PATH = {
    "Diz.Resources.EasyBundle", "_path", 0x20, 8, 1, 0x71, { 0, 0, 0, 0 }, 0
};

/* dlssrows.nim tooltip template: SettingsTooltipData.Key (ESettingsOption)
 *   EFT.UI.Settings.SettingsTooltipData.Key : ESettingsOption   (valuetype, declared by EFT.UI.Settings.SettingsTooltipData)
 */
static AowlFieldRef AOWL_FR_TTD_KEY = {
    "EFT.UI.Settings.SettingsTooltipData", "Key", 0x10, 4, 0, 0x38, { 0, 0, 0, 0 }, 0
};

/* dlssrows.nim tooltip template: SettingsTooltipData.Title (string)
 *   EFT.UI.Settings.SettingsTooltipData.Title : string   (reference, declared by EFT.UI.Settings.SettingsTooltipData)
 */
static AowlFieldRef AOWL_FR_TTD_TITLE = {
    "EFT.UI.Settings.SettingsTooltipData", "Title", 0x18, 8, 1, 0x38, { 0, 0, 0, 0 }, 0
};

/* dlssrows.nim tooltip template: SettingsTooltipData.Text (string)
 *   EFT.UI.Settings.SettingsTooltipData.Text : string   (reference, declared by EFT.UI.Settings.SettingsTooltipData)
 */
static AowlFieldRef AOWL_FR_TTD_TEXT = {
    "EFT.UI.Settings.SettingsTooltipData", "Text", 0x20, 8, 1, 0x38, { 0, 0, 0, 0 }, 0
};

/* dlssrows.nim tooltip template: SettingsTooltipData.UsageStyle (EUsageStyle)
 *   EFT.UI.Settings.SettingsTooltipData.UsageStyle : EUsageStyle   (valuetype, declared by EFT.UI.Settings.SettingsTooltipData)
 */
static AowlFieldRef AOWL_FR_TTD_USAGESTYLE = {
    "EFT.UI.Settings.SettingsTooltipData", "UsageStyle", 0x28, 4, 0, 0x38, { 0, 0, 0, 0 }, 0
};

/* dlssrows.nim tooltip template: SettingsTooltipData.UsageProperty (EUsageProperty)
 *   EFT.UI.Settings.SettingsTooltipData.UsageProperty : EUsageProperty   (valuetype, declared by EFT.UI.Settings.SettingsTooltipData)
 */
static AowlFieldRef AOWL_FR_TTD_USAGEPROP = {
    "EFT.UI.Settings.SettingsTooltipData", "UsageProperty", 0x2c, 4, 0, 0x38, { 0, 0, 0, 0 }, 0
};

/* dlssrows.nim tooltip template: SettingsTooltipData.UsageText (string)
 *   EFT.UI.Settings.SettingsTooltipData.UsageText : string   (reference, declared by EFT.UI.Settings.SettingsTooltipData)
 */
static AowlFieldRef AOWL_FR_TTD_USAGETEXT = {
    "EFT.UI.Settings.SettingsTooltipData", "UsageText", 0x30, 8, 1, 0x38, { 0, 0, 0, 0 }, 0
};

/* audit #12 mods/fov/fov.nim CameraManager._fov (float)
 *   EFT.CameraControl.CameraManager._fov : float   (primitive, declared by EFT.CameraControl.CameraManager)
 */
static AowlFieldRef AOWL_FR_CM_FOV = {
    "EFT.CameraControl.CameraManager", "_fov", 0xf8, 4, 0, 0x160, { 0, 0, 0, 0 }, 0
};

/* nativepostfx.nim row 2: PrismEffects.aoIntensity (float)
 *   PrismEffects.aoIntensity : float   (primitive, declared by PrismEffects)
 */
static AowlFieldRef AOWL_FR_PE_AO_INTENSITY = {
    "PrismEffects", "aoIntensity", 0x27c, 4, 0, 0x2e0, { 0, 0, 0, 0 }, 0
};

/* nativepostfx.nim row 2: PrismEffects.aoRadius (float)
 *   PrismEffects.aoRadius : float   (primitive, declared by PrismEffects)
 */
static AowlFieldRef AOWL_FR_PE_AO_RADIUS = {
    "PrismEffects", "aoRadius", 0x284, 4, 0, 0x2e0, { 0, 0, 0, 0 }, 0
};

/* nativepostfx.nim row 3: PrismEffects.aoBlurIterations (int)
 *   PrismEffects.aoBlurIterations : int   (primitive, declared by PrismEffects)
 */
static AowlFieldRef AOWL_FR_PE_AO_BLURITER = {
    "PrismEffects", "aoBlurIterations", 0x290, 4, 0, 0x2e0, { 0, 0, 0, 0 }, 0
};


static AowlFieldRef* aowl_fr_bc_maxbots(void) { return &AOWL_FR_BC_MAXBOTS; }
static AowlFieldRef* aowl_fr_ba_isready(void) { return &AOWL_FR_BA_ISREADY; }
static AowlFieldRef* aowl_fr_graphic_color(void) { return &AOWL_FR_GRAPHIC_COLOR; }
static AowlFieldRef* aowl_fr_tmp_fontasset(void) { return &AOWL_FR_TMP_FONTASSET; }
static AowlFieldRef* aowl_fr_tmp_sharedmat(void) { return &AOWL_FR_TMP_SHAREDMAT; }
static AowlFieldRef* aowl_fr_graphic_mat(void) { return &AOWL_FR_GRAPHIC_MAT; }
static AowlFieldRef* aowl_fr_toggle_group(void) { return &AOWL_FR_TOGGLE_GROUP; }
static AowlFieldRef* aowl_fr_toggle_ison(void) { return &AOWL_FR_TOGGLE_ISON; }
static AowlFieldRef* aowl_fr_tmp_mtext(void) { return &AOWL_FR_TMP_MTEXT; }
static AowlFieldRef* aowl_fr_eb_path(void) { return &AOWL_FR_EB_PATH; }
static AowlFieldRef* aowl_fr_ttd_key(void) { return &AOWL_FR_TTD_KEY; }
static AowlFieldRef* aowl_fr_ttd_title(void) { return &AOWL_FR_TTD_TITLE; }
static AowlFieldRef* aowl_fr_ttd_text(void) { return &AOWL_FR_TTD_TEXT; }
static AowlFieldRef* aowl_fr_ttd_usagestyle(void) { return &AOWL_FR_TTD_USAGESTYLE; }
static AowlFieldRef* aowl_fr_ttd_usageprop(void) { return &AOWL_FR_TTD_USAGEPROP; }
static AowlFieldRef* aowl_fr_ttd_usagetext(void) { return &AOWL_FR_TTD_USAGETEXT; }
static AowlFieldRef* aowl_fr_cm_fov(void) { return &AOWL_FR_CM_FOV; }
static AowlFieldRef* aowl_fr_pe_ao_intensity(void) { return &AOWL_FR_PE_AO_INTENSITY; }
static AowlFieldRef* aowl_fr_pe_ao_radius(void) { return &AOWL_FR_PE_AO_RADIUS; }
static AowlFieldRef* aowl_fr_pe_ao_bluriter(void) { return &AOWL_FR_PE_AO_BLURITER; }

static AowlFieldRef* AOWL_FR_ALL[] = {
    &AOWL_FR_BC_MAXBOTS,
    &AOWL_FR_BA_ISREADY,
    &AOWL_FR_GRAPHIC_COLOR,
    &AOWL_FR_TMP_FONTASSET,
    &AOWL_FR_TMP_SHAREDMAT,
    &AOWL_FR_GRAPHIC_MAT,
    &AOWL_FR_TOGGLE_GROUP,
    &AOWL_FR_TOGGLE_ISON,
    &AOWL_FR_TMP_MTEXT,
    &AOWL_FR_EB_PATH,
    &AOWL_FR_TTD_KEY,
    &AOWL_FR_TTD_TITLE,
    &AOWL_FR_TTD_TEXT,
    &AOWL_FR_TTD_USAGESTYLE,
    &AOWL_FR_TTD_USAGEPROP,
    &AOWL_FR_TTD_USAGETEXT,
    &AOWL_FR_CM_FOV,
    &AOWL_FR_PE_AO_INTENSITY,
    &AOWL_FR_PE_AO_RADIUS,
    &AOWL_FR_PE_AO_BLURITER,
};
#define AOWL_FR_TABLE_ROWS 20

#endif /* AOWLSPT_FIELDREFS_H */
